### PR TITLE
Node: Fix cyclic dep. in transaction payload

### LINKED ISSUE #1249: Node: Nested payload in TransactionDataPayload is not properly typed
### Issue description

parsing nested TransactionDataPayload causes class-transformer to stop due to cyclic parsing.

resulting in 
```
Block data: Block {
  protocolVersion: 2,
  parents: [
    '0x3689742bb257ffec5b9789022bb0af90c23574b605d208b84d2abd083d54085d'
  ],
  payload: {
    essence: {
      type: 1,
      networkId: '1856588631910923207',
      inputs: [Array],
      inputsCommitment: '0xff6bd7f6aeb9c6926da84267d859cf08ce44c228c13fb67b8893d642030a2f51',
      outputs: [Array],
      payload: [Object]
    },
    unlocks: [ [Object] ]
  },
  nonce: '233605'
} 
```

instead of 
```
Block data: Block {
payload: TransactionPayload {
    type: 6,
    essence: RegularTransactionEssence {
      type: 1,
      networkId: '1856588631910923207',
      inputsCommitment: '0xff6bd7f6aeb9c6926da84267d859cf08ce44c228c13fb67b8893d642030a2f51',
      inputs: [Array],
      outputs: [Array],
      payload: [Object]
    },
    unlocks: [ [SignatureUnlock] ]
  },
  nonce: '233605'
} 
```

possible fix: Custom @transform with a new `plainToInstance` call like here:
https://github.com/typestack/class-transformer/issues/212#issuecomment-451066261

### Version

1.1

### Expected behaviour

nested payload has a type

### Actual behaviour

no type

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. Change client 07 example to look up a transaction with payload type 6
2. yarn run-example ./client/07-get-block-data.ts
3. see that block data isnt typed

### Errors

_No response_

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### PR DESCRIPTION
**Pull request by abdulmth**
Fixes https://github.com/iotaledger/iota-sdk/issues/1249
replaces https://github.com/iotaledger/iota-sdk/pull/1253

The issue actually is not a cyclic dependency in class transformer, it's cyclic dependency in our code. Since `PayloadDiscriminator` depends on → `TransactionPayload` → `RegularTransactionEssence` → `PayloadDiscrminator` so the last would be replaced with 
`undefined`  by JavaScript.

### CODE REVIEW

File: bindings/nodejs/lib/types/block/payload/transaction/essence.ts [hunk 1]
```diff
@@ -57,10 +60,7 @@ class RegularTransactionEssence extends TransactionEssence {
     })
     outputs: Output[];
 
-    @Type(() => Payload, {
-        discriminator: PayloadDiscriminator,
-    })
-    payload: Payload | undefined;
+    payload?: unknown;
```
Comment (thibault-martinez) [inline bindings/nodejs/lib/types/block/payload/transaction/essence.ts]: I know nothing about TS but this looks sus :(

Comment (abdulmth) [reply bindings/nodejs/lib/types/block/payload/transaction/essence.ts]: `unknown` is a special type in TS, from [w3schools](https://www.w3schools.com/typescript/typescript_special_types.php#:~:text=unknown%20is%20best%20used%20when,is%20of%20the%20casted%20type.) 

> unknown is best used when you don't know the type of data being typed. To add a type later, you'll need to cast it.
Casting is when we use the "as" keyword to say property or variable is of the casted type.

And this is what we want here because we don't know what type `payload` will be.  Also using `Payload` isn't really of any use because it's an abstract class that shouldn't be constructed but used internally to cast to the subclasses.

**Review by kwek20 — DISMISSED** [review]

File: bindings/nodejs/lib/types/block/payload/transaction/essence.ts [hunk 2]
```diff
@@ -39,6 +41,18 @@ abstract class TransactionEssence {
     }
 }
 
+const PayloadDiscriminator = {
```
Comment (Thoralf-M) [inline bindings/nodejs/lib/types/block/payload/transaction/essence.ts:45]:
```suggestion
/**
 * PayloadDiscriminator for payloads inside of a TransactionEssence.
 */
const PayloadDiscriminator = {
```
so it doesn't get misused for payloads in a block

File: bindings/nodejs/lib/types/block/payload/transaction/essence.ts [hunk 3]
```diff
@@ -39,6 +41,18 @@ abstract class TransactionEssence {
...
+    property: 'type',
+    subTypes: [
+        { value: MilestonePayload, name: PayloadType.Milestone as any },
+        { value: TaggedDataPayload, name: PayloadType.TaggedData as any },
+        {
+            value: TreasuryTransactionPayload,
+            name: PayloadType.TreasuryTransaction as any,
+        },
```
Comment (Thoralf-M) [inline bindings/nodejs/lib/types/block/payload/transaction/essence.ts]:
```suggestion
        { value: TaggedDataPayload, name: PayloadType.TaggedData as any },
```

**Review by Thoralf-M — DISMISSED** [review]

File: bindings/nodejs/CHANGELOG.md [hunk 4]
```diff
@@ -19,6 +19,12 @@ and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0
 
 ### Security -->
 
+## 1.0.12 - 2023-mm-dd
```
Comment (thibault-martinez) [inline bindings/nodejs/CHANGELOG.md]:
```suggestion
## 1.0.12 - 2023-09-25
```

**Review by thibault-martinez — APPROVED** [review]

**Review by kwek20 — APPROVED** [review]

**Review by Thoralf-M — APPROVED** [review]
