### PR TITLE
Fix optional transaction note

### LINKED ISSUE #569: Fix optional transaction note
## Description

Fix optional transaction note, currently it's just always set to None https://github.com/iotaledger/iota-sdk/blob/bf7e2a8c9895d3fb88d83ffdf2ce94b1f778c406/sdk/src/wallet/account/operations/transaction/mod.rs#L179
instead it should use what's provided in the TransactionOptions https://github.com/iotaledger/iota-sdk/blob/bf7e2a8c9895d3fb88d83ffdf2ce94b1f778c406/sdk/src/wallet/account/operations/transaction/options.rs#L31

A test should be added which sends a transaction with a note and then checks if the note is set

### PR DESCRIPTION
**Pull request by thibault-martinez**
Fixes https://github.com/iotaledger/iota-sdk/issues/569

### CODE REVIEW

File: sdk/tests/wallet/transactions.rs [hunk 1]
```diff
@@ -162,3 +162,37 @@ async fn send_nft() -> Result<()> {
...
+                amount,
+            )?],
+            Some(TransactionOptions {
+                note: Some(String::from("send_with_note")),
+                ..Default::default()
+            }),
+        )
+        .await?;
+
+    account_0
```
Comment (kwek20) [inline sdk/tests/wallet/transactions.rs]: retry isnt needed here, makes the test longer, but consistent i guess?

Comment (thibault-martinez) [reply sdk/tests/wallet/transactions.rs]: I just copy pasted a test, I can remove it

Comment (thibault-martinez) [reply sdk/tests/wallet/transactions.rs]: Done

**Review by kwek20 — APPROVED** [review]

**Review by DaughterOfMars — APPROVED** [review]
