### PR TITLE
Fix balance locking

### LINKED ISSUE #2113: Fix balance in wasm
https://github.com/iotaledger/iota-sdk/pull/2077 made it panic in wasm

```
iota_sdk_wasm.js:846 panicked at /iota-sdk/sdk/src/wallet/operations/balance.rs:36:9:
there is no reactor running, must be called from the context of a Tokio 1.x runtime
```

### PR DESCRIPTION
**Pull request by DaughterOfMars**
# Description of change

Hopefully this fixes the issue with balance.

### CODE REVIEW

File: sdk/src/wallet/operations/balance.rs [hunk 1]
```diff
@@ -22,340 +22,345 @@ where
...
+            tokio::task::spawn_blocking(move || tokio::runtime::Handle::current().block_on(wallet.balance_inner()))
+                .await?
+        }
+        #[cfg(target_family = "wasm")]
+        {
+            self.balance_inner().await
+        }
+    }
+
+    async fn balance_inner(&self) -> Result<Balance> {
```
Comment (Thoralf-M) [inline sdk/src/wallet/operations/balance.rs]: This all isn't needed as it changes nothing? Not sure how we ended up like this, but looks like it works perfectly fine without any weird task spawning/blocking now
```suggestion
```

Comment (DaughterOfMars) [reply sdk/src/wallet/operations/balance.rs]: It works of course but the entire purpose of blocking here was to avoid deadlocking because we're doing some very unsafe operations

Comment (Thoralf-M) [reply sdk/src/wallet/operations/balance.rs]: But is this actually still the case? To me it looks like we don't have anything after `let wallet_ledger` that could result in a deadlock

Comment (DaughterOfMars) [reply sdk/src/wallet/operations/balance.rs]: the call to the client can

Comment (Thoralf-M) [reply sdk/src/wallet/operations/balance.rs]: It just returns a reference, no lock involved?

Comment (DaughterOfMars) [reply sdk/src/wallet/operations/balance.rs]: I meant the call using the client to the API 😆

**Review by Thoralf-M — DISMISSED** [review]

**Review by Thoralf-M — DISMISSED** [review]

File: sdk/src/wallet/operations/balance.rs [hunk 2]
```diff
@@ -24,334 +26,328 @@ impl<S: 'static + SecretManage> Wallet<S> {
...
+                Output::Account(account) => {
+                    // Add amount
+                    balance.base_coin.total += account.amount();
+                    balance.mana.total += output.decayed_mana(
+                        &protocol_parameters,
+                        output_id.transaction_id().slot_index(),
+                        slot_index,
+                    )?;
+                    // Add mana rewards
+                    reward_outputs.insert(*output_id);
```
Comment (thibault-martinez) [inline sdk/src/wallet/operations/balance.rs]: Should we check if it's staking? Accounts are going to be used a lot but very few of them will be staking, less API calls?

Comment (DaughterOfMars) [reply sdk/src/wallet/operations/balance.rs]: sure, why not

Comment (DaughterOfMars) [reply sdk/src/wallet/operations/balance.rs]: done

**Review by Thoralf-M — APPROVED** [review]

**Review by thibault-martinez — APPROVED** [review]
