### PR TITLE
Replace reissue_transaction_until_included() with wait_for_transaction_acceptance()

### LINKED ISSUE #1930: Change reissue_transaction_until_included() to await_block_inclusion()?
Change reissue_transaction_until_included() to something like await_block_inclusion()? Reissuing doesn't work the same way anymore as before (if one block was already successfully sent) and requires more mana which needs to be alloted first, therefore it's probably better to just wait for inclusion of the block and if the tx doesn't get confirmed create a new one.

### PR DESCRIPTION
**Pull request by Thoralf-M**
# Description of change

Replace reissue_transaction_until_included() with wait_for_transaction_acceptance() because we can't simply reissue blocks anymore, since they cost Mana. So now it only issues the block once when there was no block issued yet (should happen only very rarely because of some node/network issue) and then just checks the transaction acceptance.
Also changed the interval to milliseconds and set the default to 500, so it can return faster.

## Links to any relevant issues

Closes [#1930](https://github.com/iotaledger/iota-sdk/issues/1930)

## Type of change

- Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How the change has been tested

Running this example

```Rust
use iota_sdk::{
    types::block::output::{
        unlock_condition::{AddressUnlockCondition, ExpirationUnlockCondition},
        NftOutputBuilder, UnlockCondition,
    },
    wallet::Result,
    Wallet,
};

#[tokio::main]
async fn main() -> Result<()> {
    let logger_output_config = fern_logger::LoggerOutputConfigBuilder::new()
        .name("wallet.log")
        .target_exclusions(&["h2", "hyper", "rustls"])
        .level_filter(log::LevelFilter::Debug);

    let config = fern_logger::LoggerConfig::build()
        .with_output(logger_output_config)
        .finish();

    fern_logger::logger_init(config).unwrap();
    // This example uses secrets in environment variables for simplicity which should not be done in production.
    dotenvy::dotenv().ok();

    let wallet = Wallet::builder()
        .with_storage_path(&"./cli/stardust-cli-wallet-db")
        .finish()
        .await?;

    // May want to ensure the wallet is synced before sending a transaction.
    let balance = wallet.sync(None).await?;

    // Get the first nft
    if let Some(nft_id) = balance.nfts().first() {
        // Set the stronghold password
        wallet.set_stronghold_password("test".to_string()).await?;

        let nft = NftOutputBuilder::new_with_amount(1_000_000, *nft_id)
            .with_unlock_conditions([
                UnlockCondition::Address(AddressUnlockCondition::new(wallet.address().await)),
                UnlockCondition::Expiration(ExpirationUnlockCondition::new(
                    wallet.address().await,
                    wallet.client().get_slot_index().await? + 5000,
                )?),
            ])
            .finish_output()?;

        let transaction = wallet.send_outputs(vec![nft], None).await?;
        println!("Transaction sent: {}", transaction.transaction_id);

        println!("Tx: {:?}", transaction);

        let block_id = wallet
            .wait_for_transaction_acceptance(&transaction.transaction_id, Some(1), None)
            .await?;

        println!("Block included: /block/{}", block_id);
    } else {
        println!("No available NFTs");
    }

    Ok(())
}
```

### CODE REVIEW

File: bindings/nodejs/lib/types/error.ts [hunk 1]
```diff
@@ -44,7 +44,7 @@ export type ClientErrorName =
     | 'secretManagerMismatch'
     | 'healthyNodePoolEmpty'
     | 'taggedData'
-    | 'tangleInclusion'
+    | 'TransactionAcceptance'
```
Comment (DaughterOfMars) [inline bindings/nodejs/lib/types/error.ts]: casing?

File: sdk/src/client/error.rs [hunk 2]
```diff
@@ -113,9 +113,9 @@ pub enum Error {
     /// Error when building tagged_data blocks
     #[error("error when building tagged_data block: {0}")]
     TaggedData(String),
-    /// The block cannot be included into the Tangle
-    #[error("block ID `{0}` couldn't get included into the Tangle")]
-    TangleInclusion(String),
+    /// The transaction could not get accepted
+    #[error("transaction ID `{0}` couldn't get accepted")]
```
Comment (DaughterOfMars) [inline sdk/src/client/error.rs]:
```suggestion
    /// The transaction could not be accepted
    #[error("transaction ID `{0}` couldn't be accepted")]
```

File: sdk/src/wallet/operations/reissue.rs [hunk 3]
```diff
@@ -16,48 +16,69 @@ use crate::{
...
 
-        if let Some(transaction) = transaction {
-            if transaction.inclusion_state == InclusionState::Confirmed {
-                return transaction.block_id.ok_or(Error::MissingParameter("block id"));
-            }
+        if transaction.inclusion_state == InclusionState::Accepted
+            || transaction.inclusion_state == InclusionState::Confirmed
+            || transaction.inclusion_state == InclusionState::Finalized
+        {
+            return transaction.block_id.ok_or(Error::MissingParameter("block id"));
```
Comment (DaughterOfMars) [inline sdk/src/wallet/operations/reissue.rs]: is it possible to get the block ID if it's missing somehow?

File: sdk/src/wallet/operations/reissue.rs [hunk 4]
```diff
@@ -16,48 +16,69 @@ use crate::{
...
+            None => {
+                let wallet_data = self.data().await;
+                let issuer_id = transaction
+                    .payload
+                    .transaction()
+                    .allotments()
+                    .first()
+                    .map(|a| *a.account_id())
+                    .or_else(|| wallet_data.first_account_id())
+                    .ok_or(Error::AccountNotFound)?;
```
Comment (DaughterOfMars) [inline sdk/src/wallet/operations/reissue.rs]: This feels very iffy to me. Maybe we should pass the id in instead?

Comment (Thoralf-M) [reply sdk/src/wallet/operations/reissue.rs]: But if it's a different one than allotted it could burn the mana from the wrong account

File: bindings/nodejs/lib/types/error.ts (hunk 1 above)
Comment (Thoralf-M) [inline bindings/nodejs/lib/types/error.ts]:
```suggestion
    | 'transactionAcceptance'
```

File: sdk/src/wallet/operations/reissue.rs (hunk 3 above)
Comment (Thoralf-M) [reply sdk/src/wallet/operations/reissue.rs]: It should never be missing because we set it when we set the inclusion_state to confirmed (the others we currently never set, but we will also have the block id then)
So we could probably unwrap, but error seems better in case we mess something up at some point

Independent of the above, we could try to get it, but then it's also not guaranteed since it might be pruned

File: sdk/src/wallet/operations/reissue.rs (hunk 4 above)
Comment (DaughterOfMars) [reply sdk/src/wallet/operations/reissue.rs]: but there's no guarantee that this is right either :c

Comment (Thoralf-M) [reply sdk/src/wallet/operations/reissue.rs]: You said we have some issue with the reissuing part in syncing (because of the secret manager or something), don't we have the same issue here?
Because then I maybe just remove this part here?

File: bindings/nodejs/examples/how_tos/advanced_transactions/advanced_transaction.ts [hunk 5]
```diff
@@ -63,7 +63,7 @@ async function run() {
         console.log(`Transaction sent: ${transaction.transactionId}`);
 
         console.log('Waiting until included in block...');
```
Comment (thibault-martinez) [inline bindings/nodejs/examples/how_tos/advanced_transactions/advanced_transaction.ts]: :trollface:

File: bindings/nodejs/examples/how_tos/wallet/consolidate-outputs.ts [hunk 6]
```diff
@@ -68,7 +68,7 @@ async function run() {
         console.log('Transaction sent: %s', transaction.transactionId);
 
         // Wait for the consolidation transaction to get confirmed
-        const blockId = wallet.reissueTransactionUntilIncluded(
+        const blockId = wallet.awaitTransactionAcceptance(
```
Comment (thibault-martinez) [inline bindings/nodejs/examples/how_tos/wallet/consolidate-outputs.ts]: May want to change L76?

File: bindings/python/examples/how_tos/wallet/consolidate_outputs.py [hunk 7]
```diff
@@ -50,7 +50,7 @@
 print('Transaction sent: ', transaction.transaction_id)
 
 # Wait for the consolidation transaction to get confirmed
-block_id = wallet.reissue_transaction_until_included(
+block_id = wallet.await_transaction_acceptance(
```
Comment (thibault-martinez) [inline bindings/python/examples/how_tos/wallet/consolidate_outputs.py]: Change L57?

File: bindings/python/iota_sdk/wallet/wallet.py [hunk 8]
```diff
@@ -717,10 +717,10 @@ def prepare_transaction(
...
-    def reissue_transaction_until_included(
+    def await_transaction_acceptance(
             self, transaction_id: TransactionId, interval=None, max_attempts=None) -> BlockId:
-        """Reissues a transaction sent from the wallet for a provided transaction id until it's
-        included (referenced by a milestone). Returns the included block id.
+        """Checks the transaction state for a provided transaction id until it's accepted. Interval in milliseconds. Returns the block id that
+        contains this transaction.
         """
         return BlockId(self._call_method(
             'reissueTransactionUntilIncluded', {
```
Comment (thibault-martinez) [inline bindings/python/iota_sdk/wallet/wallet.py]: :trollface:

File: sdk/src/wallet/operations/reissue.rs (hunk 3 above)
Comment (Alex6323) [reply sdk/src/wallet/operations/reissue.rs]: sounds like if `block id` isn't there then it's a bug in the sdk? so panicking is probably what we want then.

File: bindings/nodejs/examples/how_tos/advanced_transactions/advanced_transaction.ts (hunk 5 above)
Comment (Thoralf-M) [reply bindings/nodejs/examples/how_tos/advanced_transactions/advanced_transaction.ts]: Not really wrong though `'accepted': the transaction is included.`:trollface:

File: sdk/src/wallet/operations/reissue.rs [hunk 9]
```diff
@@ -16,48 +16,69 @@ use crate::{
...
+            .ok_or_else(|| Error::TransactionNotFound(*transaction_id))?;
 
-        if let Some(transaction) = transaction {
-            if transaction.inclusion_state == InclusionState::Confirmed {
-                return transaction.block_id.ok_or(Error::MissingParameter("block id"));
-            }
+        if transaction.inclusion_state == InclusionState::Accepted
+            || transaction.inclusion_state == InclusionState::Confirmed
+            || transaction.inclusion_state == InclusionState::Finalized
+        {
```
Comment (Alex6323) [inline sdk/src/wallet/operations/reissue.rs]: would it make sense to add an `is_accepted` method (and maybe others), that returns true if `self == Accepted | Confirmed | Finalized` (pseudocode) since certain states imply others?

Comment (Thoralf-M) [reply sdk/src/wallet/operations/reissue.rs]: Currently I think it's not worth it, so far this is the only place where it's like that and in other places you probably want to differentiate more

File: sdk/src/wallet/operations/reissue.rs (hunk 3 above)
Comment (thibault-martinez) [reply sdk/src/wallet/operations/reissue.rs]: I am not super opinionated but I'm fine with panicking if the others prefer that

File: sdk/src/wallet/operations/reissue.rs [hunk 10]
```diff
@@ -66,76 +87,43 @@ where
...
-                            ClientError::TangleInclusion(first_block_id.to_string())
-                        } else {
-                            e
-                        }
-                    })?;
-                    return Ok(included_block.id(&protocol_parameters));
-                }
+                })?;
+                let protocol_parameters = self.client().get_protocol_parameters().await?;
+                return Ok(included_block.id(&protocol_parameters));
```
Comment (Alex6323) [inline sdk/src/wallet/operations/reissue.rs]: maybe we can put this in an anonymous function, for example:
```rust
let handle_failed = || { ... }
```
and call this in L109 instead of this `failed` boolean. Bit annoying with the `return` but if it's not too ugly then might be worth it.

File: sdk/src/wallet/operations/reissue.rs [hunk 11]
```diff
@@ -16,48 +16,69 @@ use crate::{
...
 where
     Error: From<S::Error>,
     crate::client::Error: From<S::Error>,
 {
-    /// Reissues a transaction sent from the account for a provided transaction id until it's
-    /// included (referenced by a milestone). Returns the included block id.
-    pub async fn reissue_transaction_until_included(
+    /// Checks the transaction state for a provided transaction id until it's accepted. Interval in milliseconds.
+    /// Returns the block id that contains this transaction.
+    pub async fn await_transaction_acceptance(
```
Comment (Alex6323) [inline sdk/src/wallet/operations/reissue.rs]: bit nitpicky but maybe the `await_` prefix is not so good since it's one of Rust's keywords and `await_transaction_acceptance.await?` reads weird. Therefore I suggest something like:
```rust
async fn block_on_transaction_acceptance(...)
```

File: sdk/src/wallet/operations/reissue.rs (hunk 10 above)
Comment (Thoralf-M) [reply sdk/src/wallet/operations/reissue.rs]: I'm not sure what that's supposed to achieve, can you maybe do a full code suggestion?

File: sdk/src/wallet/operations/reissue.rs (hunk 4 above)
Comment (Thoralf-M) [reply sdk/src/wallet/operations/reissue.rs]: Removed it

File: sdk/src/wallet/operations/reissue.rs (hunk 3 above)
Comment (Thoralf-M) [reply sdk/src/wallet/operations/reissue.rs]: Changed

File: sdk/src/wallet/operations/reissue.rs (hunk 11 above)
Comment (thibault-martinez) [reply sdk/src/wallet/operations/reissue.rs]: I don't know about that tbh... that function doesn't really block, that's what await means. Whether it's blocking or not depends on the caller.

Comment (Thoralf-M) [reply sdk/src/wallet/operations/reissue.rs]: I don't really care, can also undo, maybe let's wait for an opinion from @DaughterOfMars

Comment (Alex6323) [reply sdk/src/wallet/operations/reissue.rs]: `await` means that it cannot make immediate progress, hence is blocked by some other resource to become available. It could be blocked by some required client request to be answered or some lock to become available. Typically if there are other tasks, then the runtime switches to another, which means that the overall application isn't blocked, but I get your point. I called it like that because in most examples in order to continue with it we need to wait for the transaction to get accepted, hence the example is blocked from further continuing until that happened. I still think you're probably right, and it should be named differently. Maybe there's no good alternative :shrug:

Comment (thibault-martinez) [reply sdk/src/wallet/operations/reissue.rs]: > I called it like that because in most examples in order to continue with it we need to wait for the transaction to get accepted, hence the example is blocked from further continuing until that happened.

That's exactly what I'm saying, this is a caller behaviour. If `block_on` is in the name, I understand that it doesn't yield control to the scheduler, but it absolutely does here. But maybe it's just me, idk.

Comment (Alex6323) [reply sdk/src/wallet/operations/reissue.rs]: yup, I agree that `block_on` can't be used anymore in another context. So that would be confusing. Maybe `wait_on`, but that's almost not any better than the `await_` prefix? So ... :shrug:

File: sdk/src/wallet/operations/reissue.rs (hunk 9 above)
Comment (Alex6323) [reply sdk/src/wallet/operations/reissue.rs]: okay

File: sdk/src/wallet/operations/reissue.rs (hunk 10 above)
Comment (Alex6323) [reply sdk/src/wallet/operations/reissue.rs]: hmm, had a 2nd look and what I suggested is not even necessary. Can you not just move that code executed if `failed == true` into the `TransactionState::Failed` match branch itself?

File: sdk/src/wallet/operations/reissue.rs (hunk 11 above)
Comment (Alex6323) [reply sdk/src/wallet/operations/reissue.rs]: Please revert :trollface:

File: sdk/src/wallet/operations/reissue.rs (hunk 10 above)
Comment (Thoralf-M) [reply sdk/src/wallet/operations/reissue.rs]: Makes sense, done

File: sdk/src/wallet/operations/reissue.rs (hunk 4 above)
Comment (DaughterOfMars) [reply sdk/src/wallet/operations/reissue.rs]: well that issue is probably not an issue here, but ok

**Comment by DaughterOfMars** [comment]
I don't really like `BlockOnTransactionAcceptance`, what about `WaitForTransactionAcceptance`?

**Comment by thibault-martinez** [comment]
> I don't really like `BlockOnTransactionAcceptance`, what about `WaitForTransactionAcceptance`?

@DaughterOfMars it has been discussed here https://github.com/iotaledger/iota-sdk/pull/1979#discussion_r1485938851 if you want to comment

File: sdk/src/wallet/operations/reissue.rs (hunk 11 above)
Comment (DaughterOfMars) [reply sdk/src/wallet/operations/reissue.rs]: I do think `WaitFor` is better than `Await` in this case.

File: sdk/src/wallet/operations/wait_for_tx_acceptance.rs [hunk 12]
```diff
@@ -0,0 +1,97 @@
...
+            .data()
+            .await
+            .transactions
+            .get(transaction_id)
+            .cloned()
+            .ok_or_else(|| Error::TransactionNotFound(*transaction_id))?;
+
+        if transaction.inclusion_state == InclusionState::Accepted
+            || transaction.inclusion_state == InclusionState::Confirmed
+            || transaction.inclusion_state == InclusionState::Finalized
```
Comment (DaughterOfMars) [inline sdk/src/wallet/operations/wait_for_tx_acceptance.rs]:
```suggestion
        if matches!(transaction.inclusion_state, InclusionState::Accepted | InclusionState::Confirmed | InclusionState::Finalized)
```

File: sdk/src/wallet/operations/wait_for_tx_acceptance.rs [hunk 13]
```diff
@@ -0,0 +1,97 @@
...
+        {
+            return Ok(transaction
+                .block_id
+                // Safe to unwrap, we always set the block id together with any of these inclusion states.
+                .expect("missing block id in TransactionWithMetadata"));
+        }
+
+        if transaction.inclusion_state == InclusionState::Conflicting
+            || transaction.inclusion_state == InclusionState::UnknownPruned
```
Comment (DaughterOfMars) [inline sdk/src/wallet/operations/wait_for_tx_acceptance.rs]:
```suggestion
        if matches!(transaction.inclusion_state, InclusionState::Conflicting | InclusionState::UnknownPruned)
```

**Review by DaughterOfMars — DISMISSED** [review]

File: sdk/src/wallet/operations/wait_for_tx_acceptance.rs [hunk 14]
```diff
@@ -0,0 +1,98 @@
...
+    types::{
+        api::core::TransactionState,
+        block::{payload::signed_transaction::TransactionId, BlockId},
+    },
+    wallet::{types::InclusionState, Error, Wallet},
+};
+
+// Time in milliseconds
+const DEFAULT_AWAIT_TX_ACCEPTANCE_INTERVAL: u64 = 500;
+const DEFAULT_AWAIT_TX_ACCEPTANCE_MAX_AMOUNT: u64 = 80;
```
Comment (thibault-martinez) [inline sdk/src/wallet/operations/wait_for_tx_acceptance.rs]: Do you want to adapt these?

File: sdk/src/wallet/operations/mod.rs [hunk 15]
```diff
@@ -18,9 +18,9 @@ pub(crate) mod output_consolidation;
 /// The module for participation
 #[cfg(feature = "participation")]
 pub(crate) mod participation;
-/// The module for reissuing blocks or transactions
-pub(crate) mod reissue;
 /// The module for synchronization of the wallet
 pub(crate) mod syncing;
 /// The module for transactions
 pub(crate) mod transaction;
+/// The module for awaiting on transaction acceptance
```
Comment (thibault-martinez) [inline sdk/src/wallet/operations/mod.rs]: Adapt?

Comment (Thoralf-M) [reply sdk/src/wallet/operations/mod.rs]: Done, not sure if that's good though

**Review by DaughterOfMars — DISMISSED** [review]

File: sdk/src/wallet/operations/wait_for_tx_acceptance.rs [hunk 16]
```diff
@@ -0,0 +1,98 @@
...
+                transaction_id, transaction.inclusion_state
+            ))
+            .into());
+        }
+
+        let block_id = transaction
+            .block_id
+            .ok_or_else(|| ClientError::TransactionAcceptance(transaction_id.to_string()))?;
+
+        let duration = std::time::Duration::from_millis(interval.unwrap_or(DEFAULT_WAIT_FOR_TX_ACCEPTANCE_INTERVAL));
```
Comment (thibault-martinez) [inline sdk/src/wallet/operations/wait_for_tx_acceptance.rs]: Nit but `Duration::from_millis` is const so you could have that as constant instead of the value

File: sdk/src/wallet/operations/wait_for_tx_acceptance.rs [hunk 17]
```diff
@@ -0,0 +1,98 @@
...
+        for _ in 0..max_attempts.unwrap_or(DEFAULT_WAIT_FOR_TX_ACCEPTANCE_MAX_AMOUNT) {
+            #[cfg(target_family = "wasm")]
+            gloo_timers::future::TimeoutFuture::new(duration.as_millis() as u32).await;
+
+            #[cfg(not(target_family = "wasm"))]
+            tokio::time::sleep(duration).await;
```
Comment (thibault-martinez) [inline sdk/src/wallet/operations/wait_for_tx_acceptance.rs]: Should we put the sleep after the checks? Just in case the first API call is enough

File: sdk/src/wallet/operations/wait_for_tx_acceptance.rs [hunk 18]
```diff
@@ -0,0 +1,98 @@
...
+
+            let block_metadata = self.client().get_block_metadata(&block_id).await?;
+            if let Some(transaction_state) = block_metadata.transaction_metadata.map(|m| m.transaction_state) {
+                match transaction_state {
+                    TransactionState::Accepted | TransactionState::Confirmed | TransactionState::Finalized => {
+                        return Ok(block_id);
+                    }
+                    TransactionState::Failed => {
+                        // Check if the transaction got reissued in another block and confirmed there
+                        let included_block = self.client().get_included_block(transaction_id).await.map_err(|e| {
```
Comment (thibault-martinez) [inline sdk/src/wallet/operations/wait_for_tx_acceptance.rs]: Call `get_included_block_metadata` to avoid having to compute the block ID ?

File: sdk/src/wallet/operations/wait_for_tx_acceptance.rs (hunk 16 above)
Comment (Thoralf-M) [reply sdk/src/wallet/operations/wait_for_tx_acceptance.rs]: But the interval is provided as param, so you think it should be `interval.map(std::time::Duration::from_millis).unwrap_or(DEFAULT_WAIT_FOR_TX_ACCEPTANCE_INTERVAL)`?

File: sdk/src/wallet/operations/wait_for_tx_acceptance.rs (hunk 18 above)
Comment (Thoralf-M) [reply sdk/src/wallet/operations/wait_for_tx_acceptance.rs]: Good call

File: sdk/src/wallet/operations/wait_for_tx_acceptance.rs (hunk 16 above)
Comment (thibault-martinez) [reply sdk/src/wallet/operations/wait_for_tx_acceptance.rs]: Somehow my brain didn't parse `interval`, just ignore me

File: sdk/src/wallet/operations/wait_for_tx_acceptance.rs (hunk 17 above)
Comment (Thoralf-M) [reply sdk/src/wallet/operations/wait_for_tx_acceptance.rs]: Probably isn't, but moved it, doesn't matter much

File: sdk/src/wallet/operations/wait_for_tx_acceptance.rs (hunk 16 above)
Comment (Thoralf-M) [reply sdk/src/wallet/operations/wait_for_tx_acceptance.rs]: Did it this way now

**Review by thibault-martinez — DISMISSED** [review]

File: sdk/src/wallet/operations/wait_for_tx_acceptance.rs [hunk 19]
```diff
@@ -10,8 +12,7 @@ use crate::{
     wallet::{types::InclusionState, Error, Wallet},
 };
 
-// Time in milliseconds
-const DEFAULT_WAIT_FOR_TX_ACCEPTANCE_INTERVAL: u64 = 500;
+const DEFAULT_WAIT_FOR_TX_ACCEPTANCE_INTERVAL: Duration = Duration::from_millis(500);
 const DEFAULT_WAIT_FOR_TX_ACCEPTANCE_MAX_AMOUNT: u64 = 80;
```
Comment (DaughterOfMars) [inline sdk/src/wallet/operations/wait_for_tx_acceptance.rs]: `DEFAULT_WAIT_FOR_TX_ACCEPTANCE_MAX_ATTEMPTS`?

File: sdk/src/wallet/operations/wait_for_tx_acceptance.rs [hunk 20]
```diff
@@ -62,14 +63,10 @@ where
...
-            #[cfg(target_family = "wasm")]
-            gloo_timers::future::TimeoutFuture::new(duration.as_millis() as u32).await;
-
-            #[cfg(not(target_family = "wasm"))]
-            tokio::time::sleep(duration).await;
-
+        let duration = interval
+            .map(std::time::Duration::from_millis)
+            .unwrap_or(DEFAULT_WAIT_FOR_TX_ACCEPTANCE_INTERVAL);
+        for _ in 0..max_attempts.unwrap_or(DEFAULT_WAIT_FOR_TX_ACCEPTANCE_MAX_AMOUNT) {
```
Comment (DaughterOfMars) [inline sdk/src/wallet/operations/wait_for_tx_acceptance.rs]: not 100% sure but I think this might do the option check every iteration for no reason

Comment (DaughterOfMars) [reply sdk/src/wallet/operations/wait_for_tx_acceptance.rs]: actually, no way it does that

**Review by thibault-martinez — APPROVED** [review]

**Review by DaughterOfMars — APPROVED** [review]
