### PR TITLE
Unlock unused inputs

### LINKED ISSUE #170: [Bug]: Input locked forever when transaction with ledger fails
### Issue description

```
After I wanted to withdraw my governance vote after the termination, this did not work at first (I used a ledger). 
I've been waiting forever for confirmation! 
At some point I closed the Shimmer wallet and then suddenly the transaction confirmation came on the ledger. 
I then rejected this because shimmer was already closed.
and now shimmer is telling me I can't withdraw the vote because they are being used in another transaction. 
```

This can probably also happen if a program is terminated while being in the transaction function, we could maybe check the locked inputs during syncing and unlock them if they aren't in a pending transaction, just needs to be done carefully so it can't happen for inputs that are selected for a transaction at the same time (not sure if the locks would currently prevent that)

### Version

-

### Expected behaviour

Input should get unlocked again if something in the transaction function fails

### Actual behaviour

Input locked forever

### Can the issue reliably be reproduced?

No

### Steps to reproduce the issue

_No response_

### Errors

_No response_

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### PR DESCRIPTION
**Pull request by Thoralf-M**
# Description of change

Unlock unused inputs during wallet building
Improve a few debug logs

## Links to any relevant issues

#170 

## Type of change

- Bug fix (a non-breaking change which fixes an issue)

## How the change has been tested

Manually locked inputs and checked if they get unlocked again

## Change checklist

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

File: sdk/src/wallet/wallet/builder.rs [hunk 1]
```diff
@@ -191,7 +194,11 @@ impl WalletBuilder {
         let event_emitter = Arc::new(Mutex::new(EventEmitter::new()));
 
         #[cfg(feature = "storage")]
-        let accounts = storage_manager.lock().await.get_accounts().await.unwrap_or_default();
+        let mut accounts = storage_manager.lock().await.get_accounts().await.unwrap_or_default();
+        #[cfg(feature = "storage")]
+        // It happened that inputs got locked, the transaction failed, but they weren't unlocked again, so we do this
```
Comment (thibault-martinez) [inline sdk/src/wallet/wallet/builder.rs:198]: Comment before attribute

File: sdk/src/wallet/wallet/builder.rs [hunk 2]
```diff
@@ -191,7 +194,11 @@ impl WalletBuilder {
         let event_emitter = Arc::new(Mutex::new(EventEmitter::new()));
 
         #[cfg(feature = "storage")]
-        let accounts = storage_manager.lock().await.get_accounts().await.unwrap_or_default();
+        let mut accounts = storage_manager.lock().await.get_accounts().await.unwrap_or_default();
+        // It happened that inputs got locked, the transaction failed, but they weren't unlocked again, so we do this
+        // here
+        #[cfg(feature = "storage")]
+        unlock_unused_inputs(&mut accounts)?;
```
Comment (thibault-martinez) [inline sdk/src/wallet/wallet/builder.rs:201]: Is it enough to do that only when building a wallet ?

Comment (Thoralf-M) [reply sdk/src/wallet/wallet/builder.rs:201]: I think so, normally this shouldn't even happen, that's why I also added more matches on the errors to unlock the inputs if something in the transaction process fails
Also tried to clean it up during syncing, but that doesn't work in a safe way with the way we create the transactions. To make that safe we would need to add a new lock or change it so the account gets locked the whole time

File: sdk/src/wallet/wallet/builder.rs [hunk 3]
```diff
@@ -251,3 +258,26 @@ impl WalletBuilder {
...
+    for account in accounts.iter_mut() {
+        let mut used_inputs = HashSet::new();
+        for transaction_id in account.pending_transactions() {
+            if let Some(tx) = account.transactions().get(transaction_id) {
+                for input in &tx.inputs {
+                    used_inputs.insert(input.metadata.output_id()?);
+                }
+            }
+        }
+        for input in account.locked_outputs().clone() {
```
Comment (thibault-martinez) [inline sdk/src/wallet/wallet/builder.rs]: Can you maybe use retain to avoid cloning ?

Comment (Thoralf-M) [reply sdk/src/wallet/wallet/builder.rs]: Done

**Review by thibault-martinez — DISMISSED** [review]

**Review by thibault-martinez — APPROVED** [review]

**Review by Alex6323 — APPROVED** [review]
