### PR TITLE
Single account wallet

### LINKED ISSUE #1250: Merge Wallet and Account types
- Remove Account type and move relevant fields to the Wallet.
- Wallet becomes based on a single Address.
- Comment out examples from Cargo so they are not compiled anymore.
- Make the tests compile, potentially comment them if they fail.

### PR DESCRIPTION
**Pull request by Alex6323**
# Description of change

* Removes separate account functionality from the wallet (now: 1 wallet == 1 account)
* Transitions to a single address per wallet/account
* Optional Secret Manager
* Optional BIP44 path
* Optional Wallet Alias

Bindings will be updated separately (and can be done in parallel). That's why they are temporarily excluded from the workspace.

## Links to any relevant issues

Closes #1250

### CODE REVIEW

File: sdk/src/wallet/core/operations/verify_integrity.rs [hunk 1]
```diff
@@ -10,7 +10,7 @@ impl<S: SecretManage> Wallet<S> {
     pub async fn verify_integrity(&self) -> crate::wallet::Result<()> {
```
Comment (Thoralf-M) [inline sdk/src/wallet/core/operations/verify_integrity.rs]: Just remove this function

File: sdk/src/wallet/core/operations/stronghold_backup/mod.rs [hunk 2]
```diff
@@ -255,7 +256,7 @@ impl Wallet<StrongholdSecretManager> {
             return Err(crate::wallet::Error::Backup("backup path doesn't exist"));
         }
 
-        let mut accounts = self.accounts.write().await;
+        let mut accounts = self.data.write().await;
```
Comment (Thoralf-M) [inline sdk/src/wallet/core/operations/stronghold_backup/mod.rs]: Don't do anything with "accounts", maybe check `WalletData.outputs.is_empty()` instead (same above)

File: sdk/src/wallet/core/operations/get_account.rs [hunk 3]
```diff
@@ -16,26 +16,30 @@ impl<S: SecretManage> Wallet<S> {
         identifier: I,
     ) -> crate::wallet::Result<Account<S>> {
         let account_id = identifier.into();
-        let accounts = self.accounts.read().await;
+
+        todo!("since there's only one account in the wallet, no need to have AccountIdentifier?");
```
Comment (Thoralf-M) [inline sdk/src/wallet/core/operations/get_account.rs]: No need to have the whole function anymore, we might want something for account outputs later, but even if so, it shouldn't be done in this PR

File: sdk/src/wallet/core/operations/account_recovery.rs [hunk 4]
```diff
@@ -116,63 +117,64 @@ where
         max_account_index_to_keep: &mut Option<u32>,
         sync_options: Option<SyncOptions>,
     ) -> crate::wallet::Result<()> {
```
Comment (Thoralf-M) [inline sdk/src/wallet/core/operations/account_recovery.rs]: Remove the whole function

File: sdk/src/wallet/core/operations/account_recovery.rs [hunk 5]
```diff
@@ -33,79 +33,80 @@ where
         address_gap_limit: u32,
         sync_options: Option<SyncOptions>,
     ) -> crate::wallet::Result<Vec<Account<S>>> {
```
Comment (Thoralf-M) [inline sdk/src/wallet/core/operations/account_recovery.rs]: Remove the whole function

File: sdk/src/wallet/core/mod.rs [hunk 6]
```diff
@@ -91,65 +90,69 @@ where
...
+        // let mut account_aliases = Vec::with_capacity(accounts.len());
+        // for handle in accounts.iter() {
+        //     account_aliases.push(handle.details().await.alias().clone());
+        // }
+        // Ok(account_aliases)
+        todo!("get_alias")
     }
 
     /// Removes the latest account (account with the largest account index).
     pub async fn remove_latest_account(&self) -> crate::wallet::Result<()> {
```
Comment (Thoralf-M) [inline sdk/src/wallet/core/mod.rs]: Remove the whole function

File: sdk/src/wallet/core/mod.rs [hunk 7]
```diff
@@ -91,65 +90,69 @@ where
 {
     /// Get all accounts
     pub async fn get_accounts(&self) -> crate::wallet::Result<Vec<Account<S>>> {
```
Comment (Thoralf-M) [inline sdk/src/wallet/core/mod.rs]: Remove the whole function

File: sdk/src/wallet/core/mod.rs [hunk 8]
```diff
@@ -91,65 +90,69 @@ where
...
-        Ok(self.accounts.read().await.clone())
+        // Ok(self.data.read().await.clone())
+        todo!("get_data")
     }
 
     /// Get all account aliases
     pub async fn get_account_aliases(&self) -> crate::wallet::Result<Vec<String>> {
```
Comment (Thoralf-M) [inline sdk/src/wallet/core/mod.rs]: Remove the whole function

File: sdk/src/wallet/core/operations/account_recovery.rs
Comment (Thoralf-M) [inline sdk/src/wallet/core/operations/account_recovery.rs:1]: Actually remove the whole file

File: sdk/src/wallet/core/operations/get_account.rs
Comment (Thoralf-M) [inline sdk/src/wallet/core/operations/get_account.rs:1]: Also delete the whole file

File: sdk/src/wallet/account/operations/address_generation.rs
Comment (Thoralf-M) [inline sdk/src/wallet/account/operations/address_generation.rs:1]: Would also delete the whole file

File: sdk/src/wallet/account/operations/syncing/addresses/mod.rs
Comment (Thoralf-M) [inline sdk/src/wallet/account/operations/syncing/addresses/mod.rs:1]: Also remove whole file

File: sdk/src/wallet/core/builder.rs [hunk 9]
```diff
@@ -253,74 +255,80 @@ where
...
+            alias: Some(wallet.data().await.alias.clone()),
             client_options: Some(wallet.client_options().await),
             storage_options: Some(wallet.storage_options.clone()),
             secret_manager: Some(wallet.secret_manager.clone()),
         }
     }
 }
 
+/// Generate the wallet address.
+pub(crate) async fn create_wallet_address<S: SecretManage>(
```
Comment (Thoralf-M) [inline sdk/src/wallet/core/builder.rs]: Address should be just generated with the secret manager and provided to the wallet builder

Comment (Alex6323) [reply sdk/src/wallet/core/builder.rs]: since the secret manager is provided to the builder as well, this could also be done internally, no?

Comment (Thoralf-M) [reply sdk/src/wallet/core/builder.rs]: Maybe it shouldn't be provided to it anymore, not sure
But in either case we want the possibility to have a wallet with an NFT or account address which we can't generate with a secret manager, so there needs to be a way for the user to provide the address

File: sdk/src/wallet/account/operations/transaction/prepare_transaction.rs [hunk 10]
```diff
@@ -78,21 +78,19 @@ where
                         None
                     }
                     RemainderValueStrategy::ChangeAddress => {
-                        todo!("How is this handled now?")
+                        // TODO: the change address will now always be the wallet address, right?
```
Comment (Thoralf-M) [inline sdk/src/wallet/account/operations/transaction/prepare_transaction.rs]: Yes, should just remove this variant

File: bindings/core/src/method/account.rs
Comment (DaughterOfMars) [inline bindings/core/src/method/account.rs:1]: rename file?

Comment (DaughterOfMars) [reply bindings/core/src/method/account.rs:1]: or merge these I guess

Comment (Alex6323) [reply bindings/core/src/method/account.rs:1]: yeah, I know ... I want to keep my sanity and do bare renames at the very last moment in order to keep the merge conflicts at a minimum.

File: sdk/src/wallet/account/update.rs [hunk 11]
```diff
@@ -108,101 +89,90 @@ where
...
         }
 
         #[cfg(feature = "storage")]
         {
-            log::debug!(
-                "[SYNC] storing account {} with new synced data",
-                account_details.alias()
-            );
-            self.save(Some(&account_details)).await?;
+            log::debug!("[SYNC] storing account {} with new synced data", wallet_data.alias);
```
Comment (Thoralf-M) [inline sdk/src/wallet/account/update.rs]:
```suggestion
            log::debug!("[SYNC] storing wallet {} with new synced data", wallet_data.alias);
```

File: sdk/src/wallet/storage/manager.rs [hunk 12]
```diff
@@ -46,70 +45,36 @@ impl StorageManager {
...
+    pub(crate) async fn save_wallet_data(&mut self, wallet_data: &WalletData) -> crate::wallet::Result<()> {
+        self.set(&format!("{WALLET_DATA_KEY}"), &WalletDataDto::from(wallet_data))
+            .await
     }
 
-    pub(crate) async fn remove_account(&mut self, account_index: u32) -> crate::wallet::Result<()> {
-        self.delete(&format!("{ACCOUNT_INDEXATION_KEY}{account_index}")).await?;
-        self.account_indexes.retain(|a| a != &account_index);
-        self.set(ACCOUNTS_INDEXATION_KEY, &self.account_indexes).await
+    // TODO: remove fn?
```
Comment (Thoralf-M) [inline sdk/src/wallet/storage/manager.rs]: Yes

File: sdk/src/wallet/storage/manager.rs [hunk 13]
```diff
@@ -165,17 +130,16 @@ mod tests {
...
-        assert_eq!(accounts[0].alias(), "Alice");
+        storage_manager.save_wallet_data(&account_details).await.unwrap();
+        let wallet = storage_manager.load_wallet_data().await.unwrap();
+        assert!(matches!(wallet, Some(data) if data.alias == "Alice"));
 
-        storage_manager.remove_account(0).await.unwrap();
-        assert!(storage_manager.get_accounts().await.unwrap().is_empty());
+        storage_manager.remove_wallet_data().await.unwrap();
+        assert!(storage_manager.load_wallet_data().await.unwrap().is_none());
     }
```
Comment (Thoralf-M) [inline sdk/src/wallet/storage/manager.rs]: Delete

File: sdk/examples/how_tos/advanced_transactions/claim_transaction.rs [hunk 14]
```diff
@@ -16,31 +16,32 @@ async fn main() -> Result<()> {
     // This example uses secrets in environment variables for simplicity which should not be done in production.
     dotenvy::dotenv().ok();
 
-    // Create the wallet
-    let wallet = Wallet::builder().finish().await?;
-
-    // Get the account we generated with `create_account`
-    let account = wallet.get_account("Alice").await?;
+    // Get the wallet we generated with `create_wallet`.
```
Comment (Thoralf-M) [inline sdk/examples/how_tos/advanced_transactions/claim_transaction.rs:19]: No create_wallet and get anymore :trollface:

File: sdk/examples/how_tos/advanced_transactions/send_micro_transaction.rs [hunk 15]
```diff
@@ -26,14 +26,15 @@ async fn main() -> Result<()> {
     // This example uses secrets in environment variables for simplicity which should not be done in production.
     dotenvy::dotenv().ok();
 
+    // Get the wallet we generated with `create_wallet`.
```
Comment (Thoralf-M) [inline sdk/examples/how_tos/advanced_transactions/send_micro_transaction.rs:29]: No create_wallet and get anymore :trollface:

File: sdk/examples/how_tos/advanced_transactions/advanced_transaction.rs [hunk 16]
```diff
@@ -24,11 +25,13 @@ async fn main() -> Result<()> {
     // This example uses secrets in environment variables for simplicity which should not be done in production.
     dotenvy::dotenv().ok();
 
-    // Create the wallet
-    let wallet = Wallet::builder().finish().await?;
+    // Get the wallet we generated with `create_wallet`.
```
Comment (Thoralf-M) [inline sdk/examples/how_tos/advanced_transactions/advanced_transaction.rs:28]: No create_wallet and get anymore :trollface:

File: sdk/src/wallet/account/operations/helpers/time.rs [hunk 17]
```diff
@@ -12,10 +12,7 @@ use crate::{
 
 // Check if an output can be unlocked by one of the account addresses at the current time
 pub(crate) fn can_output_be_unlocked_now(
-    // We use the addresses with unspent outputs, because other addresses of the account without unspent outputs can't
-    // be related to this output
-    // TODO disambiguate these two parameters when we are done with Account changes https://github.com/iotaledger/iota-sdk/issues/647
-    account_addresses: &[AddressWithUnspentOutputs],
+    wallet_address: &Address,
     account_and_nft_addresses: &[Address],
```
Comment (Thoralf-M) [inline sdk/src/wallet/account/operations/helpers/time.rs]: I think this should be removed then, since the wallet_address can already be this (comment above should also not mention `account`)

File: sdk/src/wallet/storage/manager.rs (hunk 12 above)
Comment (Alex6323) [reply sdk/src/wallet/storage/manager.rs]: Done

File: sdk/src/wallet/storage/manager.rs (hunk 13 above)
Comment (Alex6323) [reply sdk/src/wallet/storage/manager.rs]: Done

File: sdk/examples/how_tos/advanced_transactions/claim_transaction.rs (hunk 14 above)
Comment (Alex6323) [reply sdk/examples/how_tos/advanced_transactions/claim_transaction.rs:19]: why exactly?

File: sdk/examples/how_tos/advanced_transactions/send_micro_transaction.rs (hunk 15 above)
Comment (Alex6323) [reply sdk/examples/how_tos/advanced_transactions/send_micro_transaction.rs:29]: but there's still a `create_wallet` example or what do you mean?

File: sdk/examples/how_tos/advanced_transactions/advanced_transaction.rs (hunk 16 above)
Comment (Alex6323) [reply sdk/examples/how_tos/advanced_transactions/advanced_transaction.rs:28]: doesn't a wallet have to be created still?

File: sdk/examples/how_tos/advanced_transactions/claim_transaction.rs (hunk 14 above)
Comment (Thoralf-M) [reply sdk/examples/how_tos/advanced_transactions/claim_transaction.rs:19]: The function is not called like this

File: sdk/examples/how_tos/advanced_transactions/send_micro_transaction.rs (hunk 15 above)
Comment (Thoralf-M) [reply sdk/examples/how_tos/advanced_transactions/send_micro_transaction.rs:29]: Ah it references the example and not a fn, wasn't clear to me from reading this

File: sdk/examples/how_tos/advanced_transactions/advanced_transaction.rs (hunk 16 above)
Comment (Thoralf-M) [reply sdk/examples/how_tos/advanced_transactions/advanced_transaction.rs:28]: Well the wallet still gets build again, we don't get it from somewhere

File: bindings/core/src/method/wallet.rs [hunk 18]
```diff
@@ -34,32 +34,43 @@ pub enum WalletMethod {
...
+    // /// Return the account indexes.
+    // /// Expected response: [`AccountIndexes`](crate::Response::AccountIndexes)
+    // GetAccountIndexes,
+
+
+    // TODO: remove
+    // /// Read accounts.
+    // /// Expected response: [`Accounts`](crate::Response::Accounts)
+    // GetAccounts,
+
```
Comment (Thoralf-M) [inline bindings/core/src/method/wallet.rs:64]: Just remove all

File: sdk/src/wallet/core/operations/background_syncing.rs [hunk 19]
```diff
@@ -48,18 +48,18 @@ where
...
-                        match account.sync(options.clone()).await {
-                            Ok(_) => {}
-                            Err(err) => log::debug!("[background_syncing] error: {}", err),
-                        };
+                    log::debug!("[background_syncing]: syncing wallet");
+
+                    // Check if the process should stop before syncing each account so it stops faster
+                    if wallet.background_syncing_status.load(Ordering::Relaxed) == 2 {
+                        log::debug!("[background_syncing]: stopping");
+                        break 'outer;
```
Comment (Thoralf-M) [inline sdk/src/wallet/core/operations/background_syncing.rs]: This can be removed now
```suggestion
```

Comment (Alex6323) [reply sdk/src/wallet/core/operations/background_syncing.rs]: only those lines?

Comment (Alex6323) [reply sdk/src/wallet/core/operations/background_syncing.rs]: Done

File: sdk/src/wallet/core/builder.rs [hunk 20]
```diff
@@ -144,56 +156,95 @@ where
...
+        if let Some(wallet_data) = &wallet_data {
+            let new_coin_type = bip_path.coin_type;
+            let old_coin_type = wallet_data.bip_path.coin_type;
+            if bip_path != wallet_data.bip_path {
+                if new_coin_type != old_coin_type {
+                    return Err(crate::wallet::Error::CoinTypeMismatch {
+                        new_coin_type,
+                        old_coin_type,
+                    });
+                }
```
Comment (Thoralf-M) [inline sdk/src/wallet/core/builder.rs]: Should just compare the bip path

File: sdk/src/wallet/core/builder.rs [hunk 21]
```diff
@@ -203,56 +254,88 @@ where
...
+                    .as_ref()
+                    .unwrap()
+                    .read()
+                    .await
+                    .generate_ed25519_addresses(
+                        bip_path.coin_type,
+                        bip_path.account,
+                        0..1,
+                        GenerateAddressOptions {
+                            internal: false,
```
Comment (Thoralf-M) [inline sdk/src/wallet/core/builder.rs]:
```suggestion
                        bip_path.address_index..bip_path.address_index+1,
                        GenerateAddressOptions {
                            internal: bip_path.change != 0,
```

File: sdk/src/wallet/core/builder.rs (hunk 20 above)
Comment (Alex6323) [reply sdk/src/wallet/core/builder.rs]: Done

File: bindings/core/src/method/wallet_operation.rs [hunk 22]
```diff
@@ -18,28 +18,18 @@ use iota_sdk::{
...
 #[non_exhaustive]
-pub enum AccountMethod {
-    /// List addresses.
-    /// Expected response: [`Addresses`](crate::Response::Addresses)
-    Addresses,
-    /// Returns only addresses of the account with unspent outputs
-    /// Expected response:
-    /// [`AddressesWithUnspentOutputs`](crate::Response::AddressesWithUnspentOutputs)
-    AddressesWithUnspentOutputs,
+pub enum WalletOperationMethod {
```
Comment (DaughterOfMars) [inline bindings/core/src/method/wallet_operation.rs]: Why the separation still?

Comment (Alex6323) [reply bindings/core/src/method/wallet_operation.rs]: several reasons actually ... mostly because I wasn't absolutely sure whether this shouldn't be handled in a separate PR (since this one is already too big for my taste, so it might be a bit less to check as a reviewer), then I feel like there's still a difference between methods managing the wallet itself (`backup`, etc) and the methods that are interacting with an IOTA network. The `WalletMethod`s aren't exactly implied by the protocol, while the `WalletOperationMethod`s kinda are (working with outputs, addresses, participation, voting, ...). I am open to discussing merging them if that is what the team mostly prefers.

Comment (Alex6323) [reply bindings/core/src/method/wallet_operation.rs]: @Thoralf-M @kwek20 opinions?

Comment (Thoralf-M) [reply bindings/core/src/method/wallet_operation.rs]: Separation might make sense for a better overview, but don't have a strong opinion, would also be fine with merging
But don't think we should care that much about the bindings in this PR

File: sdk/src/types/block/error.rs [hunk 23]
```diff
@@ -211,7 +211,7 @@ impl fmt::Display for Error {
             }
             Self::InvalidAddress => write!(f, "invalid address provided"),
             Self::InvalidAddressKind(k) => write!(f, "invalid address kind: {k}"),
-            Self::InvalidAccountIndex(index) => write!(f, "invalid account index: {index}"),
+            Self::InvalidWalletIndex(index) => write!(f, "invalid account index: {index}"),
```
Comment (Thoralf-M) [inline sdk/src/types/block/error.rs]: Undo this change, account was correct here

File: sdk/src/types/block/unlock/account.rs [hunk 24]
```diff
@@ -5,7 +5,7 @@ use crate::types::block::{unlock::UnlockIndex, Error};
 
 /// Points to the unlock of a consumed account output.
 #[derive(Clone, Debug, Eq, PartialEq, Hash, packable::Packable)]
-#[packable(unpack_error = Error, with = Error::InvalidAccountIndex)]
+#[packable(unpack_error = Error, with = Error::InvalidWalletIndex)]
```
Comment (Thoralf-M) [inline sdk/src/types/block/unlock/account.rs]: Undo

File: sdk/src/wallet/core/builder.rs [hunk 25]
```diff
@@ -144,56 +156,99 @@ where
...
-        ))?;
+        // Panic: can be safely unwrapped now
+        let address = self.address.as_ref().unwrap().clone();
 
         #[cfg(feature = "storage")]
-        let mut accounts = storage_manager.get_accounts().await?;
+        let mut wallet_data = storage_manager.load_wallet_data().await?;
 
-        // Check against potential account coin type before saving the wallet data
+        // The coin type must not change.
```
Comment (Thoralf-M) [inline sdk/src/wallet/core/builder.rs]:
```suggestion
        // The bip path must not change.
```

File: sdk/src/wallet/core/mod.rs [hunk 26]
```diff
@@ -86,93 +99,322 @@ pub struct WalletInner<S: SecretManage = SecretManager> {
...
+        self.data().await.address.clone()
+    }
+
+    /// Get the wallet's configured Bech32 HRP.
+    pub async fn bech32_hrp(&self) -> Hrp {
+        self.data().await.address.hrp
+    }
+
+    /// Get the wallet's configured coin type.
+    pub async fn coin_type(&self) -> u32 {
```
Comment (Thoralf-M) [inline sdk/src/wallet/core/mod.rs]: Should rather return the full bip path

File: sdk/src/wallet/core/mod.rs [hunk 27]
```diff
@@ -86,93 +99,322 @@ pub struct WalletInner<S: SecretManage = SecretManager> {
     pub(crate) storage_manager: tokio::sync::RwLock<StorageManager>,
 }
 
+/// Wallet data.
+#[derive(Clone, Debug, Eq, PartialEq)]
+pub struct WalletData {
+    /// The wallet BIP44 path.
+    pub(crate) bip_path: Bip44,
```
Comment (Thoralf-M) [inline sdk/src/wallet/core/mod.rs]: Optional? In case of an account/nft address

File: sdk/src/wallet/core/mod.rs [hunk 28]
```diff
@@ -86,93 +99,322 @@ pub struct WalletInner<S: SecretManage = SecretManager> {
...
+                            if nft_ids.contains(&nft_id) {
+                                filtered_outputs.push(output.clone());
+                                continue;
+                            }
+                        }
+                    }
+                    _ => {}
+                }
+
+                // TODO check if we can still filter since milestone_timestamp_booked is gone
```
Comment (Thoralf-M) [inline sdk/src/wallet/core/mod.rs]:
```suggestion
                // TODO filter based on slot index

File: sdk/src/wallet/core/operations/stronghold_backup/mod.rs [hunk 29]
```diff
@@ -255,13 +233,16 @@ impl Wallet<StrongholdSecretManager> {
             return Err(crate::wallet::Error::Backup("backup path doesn't exist"));
         }
 
-        let mut accounts = self.accounts.write().await;
+        // Will be replaced by the restored wallet data
+        let mut wallet_data = self.data_mut().await;
+
+        // TODO: Is there a way to ensure that the user can't mess up?
```
Comment (Thoralf-M) [inline sdk/src/wallet/core/operations/stronghold_backup/mod.rs]: Maybe return an error if outputs aren't empty

File: sdk/src/wallet/core/operations/address_generation.rs [hunk 30]
```diff
@@ -18,12 +16,7 @@ impl Wallet {
...
-    ///     .generate_ed25519_addresses(
-    ///         0,
-    ///         false,
-    ///         0,
-    ///         None,
-    ///     )
+    ///     .generate_ed25519_address(None)
     ///     .await?;
     /// ```
     pub async fn generate_ed25519_address(
```
Comment (Thoralf-M) [inline sdk/src/wallet/core/operations/address_generation.rs:22]: I think we should remove this from the wallet, users can do it with the secret manager

File: sdk/src/types/block/error.rs (hunk 23 above)
Comment (Alex6323) [reply sdk/src/types/block/error.rs]: oopsie

File: sdk/src/types/block/unlock/account.rs (hunk 24 above)
Comment (Alex6323) [reply sdk/src/types/block/unlock/account.rs]: oopsie 2

File: sdk/src/wallet/operations/syncing/mod.rs [hunk 31]
```diff
@@ -145,58 +155,63 @@ where
...
+                let (addresses_with_unspent_outputs_inner, outputs_data_inner) =
+                    self.get_outputs_from_address_output_ids(unspent_output_ids).await?;
+
                 addresses_with_unspent_outputs = addresses_with_unspent_outputs_inner;
                 outputs_data.extend(outputs_data_inner.clone());
                 outputs_data_inner
             } else {
-                let bech32_hrp = self.client().get_bech32_hrp().await?;
+                // TODO: why did we call this inside of the loop? Once should be enough, no?
+                // let bech32_hrp = self.client().get_bech32_hrp().await?;
```
Comment (Thoralf-M) [inline sdk/src/wallet/operations/syncing/mod.rs]: Yes
```suggestion
```

File: sdk/src/wallet/operations/transaction/high_level/send_native_tokens.rs [hunk 32]
```diff
@@ -133,11 +131,9 @@ where
         let rent_structure = self.client().get_rent_structure().await?;
         let token_supply = self.client().get_token_supply().await?;
 
-        let account_addresses = self.addresses().await;
-        let default_return_address = account_addresses
-            .into_iter()
-            .next()
-            .ok_or(Error::FailedToGetRemainder)?;
+        let wallet_address = self.address().await;
+        // TODO: not needed anymore?
```
Comment (Thoralf-M) [inline sdk/src/wallet/operations/transaction/high_level/send_native_tokens.rs]: Why not? Or what exactly is not needed anymore?

File: sdk/tests/types/unlock/account.rs [hunk 33]
```diff
@@ -23,7 +23,7 @@ fn new_valid_max_index() {
 fn new_invalid_more_than_max_index() {
     assert!(matches!(
         AccountUnlock::new(128),
-        Err(Error::InvalidAccountIndex(InvalidBoundedU16(128)))
+        Err(Error::InvalidWalletIndex(InvalidBoundedU16(128)))
```
Comment (Thoralf-M) [inline sdk/tests/types/unlock/account.rs]: Undo

File: sdk/examples/wallet/storage.rs [hunk 34]
```diff
@@ -32,48 +30,30 @@ async fn main() -> Result<()> {
...
+    println!("ADDRESS:\n{bech32_address}");
 
-    sync_print_balance(&account).await?;
+    sync_print_balance(&wallet).await?;
 
-    #[cfg(debug_assertions)]
-    wallet.verify_integrity().await?;
+    // TODO: remove?
+    // #[cfg(debug_assertions)]
+    // wallet.verify_integrity().await?;
```
Comment (Thoralf-M) [inline sdk/examples/wallet/storage.rs]: Yes
```suggestion
```

File: sdk/examples/wallet/spammer.rs [hunk 35]
```diff
@@ -39,23 +44,36 @@ async fn main() -> Result<()> {
     // Restore wallet from a mnemonic phrase.
     let client_options = ClientOptions::new().with_node(&std::env::var("NODE_URL").unwrap())?;
     let secret_manager = MnemonicSecretManager::try_from_mnemonic(std::env::var("MNEMONIC").unwrap())?;
+
+    // TODO: in this case we can just let the builder generate the wallet address ... so remove?
```
Comment (Thoralf-M) [inline sdk/examples/wallet/spammer.rs]: Would keep it for now, not sure if we want to keep the address generation in the builder like it is

File: sdk/src/wallet/mod.rs [hunk 36]
```diff
@@ -27,19 +32,93 @@ pub mod storage;
...
+    tx_id: TransactionId,
+    tx_payload: TransactionPayload,
+    inputs: Vec<OutputWithMetadataResponse>,
+) -> crate::wallet::Result<Transaction> {
+    Ok(Transaction {
+        payload: tx_payload.clone(),
+        block_id: inputs.first().map(|i| *i.metadata.block_id()),
+        inclusion_state: InclusionState::Confirmed,
+        timestamp: 0,
+        // TODO check if we keep a timestamp in Transaction since milestone_timestamp_spent is gone
```
Comment (Thoralf-M) [inline sdk/src/wallet/mod.rs]:
```suggestion
        // TODO use slot index since milestone_timestamp_spent is gone
```

File: cli/src/wallet_operation_cli/completer.rs
Comment (thibault-martinez) [inline cli/src/wallet_operation_cli/completer.rs:1]: Keep the `Command` name instead of operations please, it's a Command Line Interface after all.

**Review by thibault-martinez — CHANGES_REQUESTED** [review]

File: cli/src/wallet_operation_cli/completer.rs
Comment (Alex6323) [reply cli/src/wallet_operation_cli/completer.rs:1]: Done

File: bindings/core/src/method/wallet_operation.rs (hunk 22 above)
Comment (Alex6323) [reply bindings/core/src/method/wallet_operation.rs]: kept the separation and named the structs `Cli` (essentially the wallet/storage file management) and `WalletCli` (the actual network protocol interaction) at the "signed in" wallet prompt.

File: sdk/src/types/block/error.rs (hunk 23 above)
Comment (Alex6323) [reply sdk/src/types/block/error.rs]: undone

File: sdk/src/types/block/unlock/account.rs (hunk 24 above)
Comment (Alex6323) [reply sdk/src/types/block/unlock/account.rs]: undone

File: sdk/src/wallet/core/builder.rs (hunk 25 above)
Comment (Alex6323) [reply sdk/src/wallet/core/builder.rs]: Done

File: sdk/src/wallet/core/mod.rs (hunk 26 above)
Comment (Alex6323) [reply sdk/src/wallet/core/mod.rs]: Done

File: sdk/src/wallet/core/mod.rs [hunk 37]
```diff
@@ -230,3 +472,253 @@ impl<S: SecretManage> Drop for Wallet<S> {
         log::debug!("drop Wallet");
     }
 }
+
+/// Dto for an Account.
```
Comment (DaughterOfMars) [inline sdk/src/wallet/core/mod.rs]: account

File: bindings/core/src/method/wallet_operation.rs (hunk 22 above)
Comment (kwek20) [reply bindings/core/src/method/wallet_operation.rs]: I prefer the separation! so 👍

File: bindings/core/tests/combined.rs [hunk 38]
```diff
@@ -68,113 +49,114 @@ async fn create_account() -> Result<()> {
...
-                assert!(account_details.contains_key(&index));
-            }
-        }
-        response => panic!("unexpected response {response:?}"),
-    }
-
-    std::fs::remove_dir_all(storage_path).ok();
-    Ok(())
-}
+// TODO: temporarily disabled (needs to become `verify_wallet`)
```
Comment (Thoralf-M) [inline bindings/core/tests/combined.rs]: Should be fine to just remove, this was there to make sure we don't mess the account indexes up, but this can't happen anymore

File: cli/src/helper.rs [hunk 39]
```diff
@@ -152,10 +127,10 @@ pub async fn generate_mnemonic(
         println_log_info!("Mnemonic has been written to '{file_path}'.");
     }
 
-    println_log_info!("IMPORTANT:");
-    println_log_info!("Store this mnemonic in a secure location!");
-    println_log_info!(
-        "It is the only way to recover your account if you ever forget your password and/or lose the stronghold file."
+    println!("IMPORTANT:");
```
Comment (Thoralf-M) [inline cli/src/helper.rs:130]: Why not println_log_info anymore?

File: sdk/tests/wallet/address_generation.rs [hunk 40]
```diff
@@ -56,6 +57,8 @@ async fn wallet_address_generation_mnemonic() -> Result<()> {
 #[cfg(feature = "stronghold")]
 #[tokio::test]
 async fn wallet_address_generation_stronghold() -> Result<()> {
+    use iota_sdk::crypto::keys::bip44::Bip44;
```
Comment (Thoralf-M) [inline sdk/tests/wallet/address_generation.rs]: Already imported in L6?

File: sdk/tests/wallet/address_generation.rs [hunk 41]
```diff
@@ -95,6 +98,8 @@ async fn wallet_address_generation_stronghold() -> Result<()> {
 #[cfg(all(feature = "ledger_nano", feature = "events"))]
 #[ignore = "requires ledger nano instance"]
 async fn wallet_address_generation_ledger() -> Result<()> {
+    use iota_sdk::crypto::keys::bip44::Bip44;
```
Comment (Thoralf-M) [inline sdk/tests/wallet/address_generation.rs]: Already imported in L6?

File: cli/src/helper.rs (hunk 39 above)
Comment (Alex6323) [reply cli/src/helper.rs:130]: what's the purpose of this safety message in the log?

Comment (Thoralf-M) [reply cli/src/helper.rs:130]: I thought we just print everything (apart from the mnemonic) this way just so one can see what happened, but just checked and we mix both ways, so fine if we don't do it here

File: sdk/src/wallet/operations/transaction/high_level/send_native_tokens.rs (hunk 32 above)
Comment (Alex6323) [reply sdk/src/wallet/operations/transaction/high_level/send_native_tokens.rs]: just meant the variable binding, but I can also keep it. Removing the comment...

Comment (Thoralf-M) [reply sdk/src/wallet/operations/transaction/high_level/send_native_tokens.rs]: Ah yeah you can also remove the variable if you want, but at least remove the comment :D

File: sdk/src/wallet/core/mod.rs (hunk 37 above)
Comment (Alex6323) [reply sdk/src/wallet/core/mod.rs]: changed

File: bindings/core/tests/combined.rs (hunk 38 above)
Comment (Alex6323) [reply bindings/core/tests/combined.rs]: removed

File: sdk/tests/wallet/address_generation.rs (hunk 40 above)
Comment (Alex6323) [reply sdk/tests/wallet/address_generation.rs]: removed

File: sdk/tests/wallet/address_generation.rs (hunk 41 above)
Comment (Alex6323) [reply sdk/tests/wallet/address_generation.rs]: removed

File: sdk/src/wallet/operations/transaction/high_level/send_native_tokens.rs (hunk 32 above)
Comment (Alex6323) [reply sdk/src/wallet/operations/transaction/high_level/send_native_tokens.rs]: Done

File: sdk/examples/how_tos/account/create.rs [hunk 42]
```diff
@@ -20,13 +20,13 @@ async fn main() -> Result<()> {
     dotenvy::dotenv().ok();
 
     let wallet = Wallet::builder()
+        .with_alias("Alice")
```
Comment (thibault-martinez) [inline sdk/examples/how_tos/account/create.rs]: remove

Comment (Alex6323) [reply sdk/examples/how_tos/account/create.rs]: one more Alice to kill :smiling_imp:

File: sdk/tests/wallet/error.rs [hunk 43]
```diff
@@ -6,12 +6,6 @@ use pretty_assertions::assert_eq;
 
 #[test]
 fn stringified_error() {
-    let error = Error::AccountNotFound("0".into());
-    assert_eq!(
-        &serde_json::to_string(&error).unwrap(),
-        "{\"type\":\"accountNotFound\",\"error\":\"account 0 not found\"}"
-    );
-
```
Comment (thibault-martinez) [inline sdk/tests/wallet/error.rs:14]: Don't simply remove them, these were testing specific serialisations. Please replace by other errors with similar patterns. One tuple error, one struct error and one unit error.

Comment (Alex6323) [reply sdk/tests/wallet/error.rs:14]: not sure I follow tbh ... it's not possible anymore that an account (or a wallet) cannot be found (which is why I removed the error variant).  So what should I replace it with?

Comment (thibault-martinez) [reply sdk/tests/wallet/error.rs:14]: This has nothing to do with the actual variant, we're just testing error serialization here. Just pick a random other variant that has the same structure.

Comment (thibault-martinez) [reply sdk/tests/wallet/error.rs:14]: We just need to test one tuple, one struct and one unit

File: sdk/examples/how_tos/accounts_and_addresses/consolidate_outputs.rs [hunk 44]
```diff
@@ -27,23 +27,22 @@ async fn main() -> Result<()> {
...
         .finish()
         .await?;
-    let account = wallet.get_account("Alice").await?;
 
     // Set the stronghold password
     wallet
         .set_stronghold_password(std::env::var("STRONGHOLD_PASSWORD").unwrap())
         .await?;
 
     // Sync account to make sure account is updated with outputs from previous examples
```
Comment (thibault-martinez) [inline sdk/examples/how_tos/accounts_and_addresses/consolidate_outputs.rs]: update

File: sdk/examples/how_tos/accounts_and_addresses/list_outputs.rs [hunk 45]
```diff
@@ -19,20 +19,19 @@ async fn main() -> Result<()> {
         .with_storage_path(&std::env::var("WALLET_DB_PATH").unwrap())
         .finish()
         .await?;
-    let account = wallet.get_account("Alice").await?;
 
     // Sync account
```
Comment (thibault-martinez) [inline sdk/examples/how_tos/accounts_and_addresses/list_outputs.rs]: update

File: sdk/examples/how_tos/accounts_and_addresses/list_transactions.rs [hunk 46]
```diff
@@ -22,10 +22,9 @@ async fn main() -> Result<()> {
         .with_storage_path(&std::env::var("WALLET_DB_PATH").unwrap())
         .finish()
         .await?;
-    let account = wallet.get_account("Alice").await?;
 
     // Sync account
```
Comment (thibault-martinez) [inline sdk/examples/how_tos/accounts_and_addresses/list_transactions.rs]: Update and look in the whole repo for occurrences of this

File: sdk/examples/how_tos/advanced_transactions/claim_transaction.rs [hunk 47]
```diff
@@ -16,31 +16,31 @@ async fn main() -> Result<()> {
...
+    let wallet = Wallet::builder()
+        .with_storage_path(&std::env::var("WALLET_DB_PATH").unwrap())
+        .finish()
+        .await?;
 
     // May want to ensure the account is synced before sending a transaction.
```
Comment (thibault-martinez) [inline sdk/examples/how_tos/advanced_transactions/claim_transaction.rs]: update

File: sdk/examples/how_tos/advanced_transactions/send_micro_transaction.rs [hunk 48]
```diff
@@ -26,14 +26,14 @@ async fn main() -> Result<()> {
...
     let wallet = Wallet::builder()
         .with_storage_path(&std::env::var("WALLET_DB_PATH").unwrap())
         .finish()
         .await?;
-    let account = wallet.get_account("Alice").await?;
 
     // May want to ensure the account is synced before sending a transaction.
```
Comment (thibault-martinez) [inline sdk/examples/how_tos/advanced_transactions/send_micro_transaction.rs]: Update and look for occurrences

File: sdk/examples/how_tos/native_tokens/burn.rs [hunk 49]
```diff
@@ -32,15 +32,14 @@ async fn main() -> Result<()> {
     // This example uses secrets in environment variables for simplicity which should not be done in production.
     dotenvy::dotenv().ok();
 
+    let alias = "Alice";
```
Comment (thibault-martinez) [inline sdk/examples/how_tos/native_tokens/burn.rs]: remove?

File: sdk/examples/how_tos/native_tokens/destroy_foundry.rs [hunk 50]
```diff
@@ -19,15 +19,14 @@ async fn main() -> Result<()> {
     // This example uses secrets in environment variables for simplicity which should not be done in production.
     dotenvy::dotenv().ok();
 
+    let alias = "Alice";
```
Comment (thibault-martinez) [inline sdk/examples/how_tos/native_tokens/destroy_foundry.rs]: remove ?

File: sdk/examples/how_tos/native_tokens/create.rs [hunk 51]
```diff
@@ -87,7 +87,7 @@ async fn main() -> Result<()> {
     println!("Created token: {}", transaction.token_id);
 
     // Ensure the account is synced after creating the native token.
-    account.sync(None).await?;
+    wallet.sync(None).await?;
     println!("Account synced");
```
Comment (thibault-martinez) [inline sdk/examples/how_tos/native_tokens/create.rs]: Update and find occurrences

File: bindings/core/tests/serialize_error.rs [hunk 52]
```diff
@@ -12,9 +12,9 @@ fn custom_error_serialization() {
         serde_json::to_string(&error).unwrap(),
         "{\"type\":\"client\",\"error\":\"no healthy node available\"}"
     );
-    let error = Error::Wallet(WalletError::AccountNotFound("Alice".to_string()));
+    let error = Error::Wallet(WalletError::MissingBipPath);
```
Comment (thibault-martinez) [inline bindings/core/tests/serialize_error.rs]: Try to replace with a similar error instead

File: bindings/core/src/method/wallet_command.rs [hunk 53]
```diff
@@ -18,28 +18,18 @@ use iota_sdk::{
...
 #[non_exhaustive]
-pub enum AccountMethod {
-    /// List addresses.
-    /// Expected response: [`Addresses`](crate::Response::Addresses)
-    Addresses,
-    /// Returns only addresses of the account with unspent outputs
-    /// Expected response:
-    /// [`AddressesWithUnspentOutputs`](crate::Response::AddressesWithUnspentOutputs)
-    AddressesWithUnspentOutputs,
+pub enum WalletCommandMethod {
```
Comment (thibault-martinez) [inline bindings/core/src/method/wallet_command.rs:29]: I don't really like this split/name, will put in my issue to not have to address it here.

File: sdk/src/wallet/core/operations/stronghold_backup/mod.rs [hunk 54]
```diff
@@ -36,7 +34,7 @@ impl Wallet {
             // Backup with existing stronghold
             SecretManager::Stronghold(stronghold) => {
                 stronghold.set_password(stronghold_password).await?;
-                self.store_data_to_stronghold(stronghold).await?;
+                self.store_wallet_data_to_stronghold(stronghold).await?;
```
Comment (thibault-martinez) [inline sdk/src/wallet/core/operations/stronghold_backup/mod.rs]: Revert, we're in a Wallet impl block no need to put wallet in the name.

File: sdk/src/wallet/operations/participation/event.rs [hunk 55]
```diff
@@ -60,12 +61,11 @@ where
                 data: event_data,
                 nodes: vec![options.node.clone()],
             };
-            let account_index = self.details().await.index;
-            self.wallet
+            self.inner
```
Comment (thibault-martinez) [inline sdk/src/wallet/operations/participation/event.rs]: You sometimes use `inner.storage_manager` and sometimes just `.storage_manager`, harmonise pls

File: bindings/core/src/method/wallet_command.rs (hunk 53 above)
Comment (Alex6323) [reply bindings/core/src/method/wallet_command.rs:29]: you mean ... just like Chloe you want to merge everything into `WalletMethod`?

Comment (thibault-martinez) [reply bindings/core/src/method/wallet_command.rs:29]: I think that would be my preference yes, there is no such dichotomy in the SDK anymore so I don't know why there would be one in the bindings. At the very least we rename the enum, `WalletCommandMethod` is way too weird. But just keep it like that for now, we can change later.

File: sdk/examples/how_tos/native_tokens/create.rs (hunk 51 above)
Comment (Alex6323) [reply sdk/examples/how_tos/native_tokens/create.rs]: Fixed

File: bindings/core/tests/serialize_error.rs (hunk 52 above)
Comment (Alex6323) [reply bindings/core/tests/serialize_error.rs]: those are completely different errors (the former wasn't necessary anymore because there are no accounts anymore, and the new one comes with the fact that providing a BIP path is now optional, but can be necessary for certain operations.

Comment (thibault-martinez) [reply bindings/core/tests/serialize_error.rs]: I have said it in the other comment, we do NOT care about the actual variant, this test is about custom serialisation

File: sdk/src/wallet/core/operations/stronghold_backup/mod.rs (hunk 54 above)
Comment (Alex6323) [reply sdk/src/wallet/core/operations/stronghold_backup/mod.rs]: Done

File: sdk/tests/wallet/error.rs (hunk 43 above)
Comment (Alex6323) [reply sdk/tests/wallet/error.rs:14]: lol, I see

File: sdk/src/wallet/core/operations/address_generation.rs (hunk 30 above)
Comment (Alex6323) [reply sdk/src/wallet/core/operations/address_generation.rs:22]: that's a significant change though, that has a lot of downstream effects. I see that it's related to turning the wallet into a single account one, but not that strongly that it couldn't be a separate PR, wdyt?

File: bindings/core/src/method/wallet_command.rs (hunk 53 above)
Comment (Alex6323) [reply bindings/core/src/method/wallet_command.rs:29]: sounds good to me

Comment (Alex6323) [reply bindings/core/src/method/wallet_command.rs:29]: Done :trollface:

File: sdk/src/wallet/core/operations/address_generation.rs (hunk 30 above)
Comment (Thoralf-M) [reply sdk/src/wallet/core/operations/address_generation.rs:22]: Fine, opened an issue https://github.com/iotaledger/iota-sdk/issues/1536

File: bindings/core/tests/serialize_error.rs (hunk 52 above)
Comment (Alex6323) [reply bindings/core/tests/serialize_error.rs]: gotcha

File: sdk/examples/how_tos/native_tokens/burn.rs (hunk 49 above)
Comment (Alex6323) [reply sdk/examples/how_tos/native_tokens/burn.rs]: either I missed it, or it was reintroduced accidentally during a merge :shrug:

File: sdk/examples/how_tos/native_tokens/destroy_foundry.rs (hunk 50 above)
Comment (Alex6323) [reply sdk/examples/how_tos/native_tokens/destroy_foundry.rs]: Done

File: sdk/examples/how_tos/native_tokens/burn.rs (hunk 49 above)
Comment (Alex6323) [reply sdk/examples/how_tos/native_tokens/burn.rs]: Done

File: sdk/examples/how_tos/advanced_transactions/send_micro_transaction.rs (hunk 48 above)
Comment (Alex6323) [reply sdk/examples/how_tos/advanced_transactions/send_micro_transaction.rs]: Done

File: sdk/examples/how_tos/advanced_transactions/claim_transaction.rs (hunk 47 above)
Comment (Alex6323) [reply sdk/examples/how_tos/advanced_transactions/claim_transaction.rs]: Done

File: sdk/examples/how_tos/accounts_and_addresses/list_transactions.rs (hunk 46 above)
Comment (Alex6323) [reply sdk/examples/how_tos/accounts_and_addresses/list_transactions.rs]: hopefully found all of them

File: sdk/examples/how_tos/accounts_and_addresses/list_outputs.rs (hunk 45 above)
Comment (Alex6323) [reply sdk/examples/how_tos/accounts_and_addresses/list_outputs.rs]: Done

File: sdk/examples/how_tos/accounts_and_addresses/consolidate_outputs.rs (hunk 44 above)
Comment (Alex6323) [reply sdk/examples/how_tos/accounts_and_addresses/consolidate_outputs.rs]: Fixed

File: sdk/tests/wallet/error.rs (hunk 43 above)
Comment (Alex6323) [reply sdk/tests/wallet/error.rs:14]: Added a test for each kind.

File: sdk/examples/how_tos/account/create.rs (hunk 42 above)
Comment (Alex6323) [reply sdk/examples/how_tos/account/create.rs]: so weird ... but finally gone.

File: sdk/Cargo.toml [hunk 56]
```diff
@@ -221,30 +221,15 @@ path = "examples/how_tos/accounts_and_addresses/create_mnemonic.rs"
...
 required-features = ["rocksdb", "stronghold"]
 
-[[example]]
-name = "list_addresses"
-path = "examples/how_tos/accounts_and_addresses/list_addresses.rs"
-required-features = ["rocksdb", "stronghold"]
-
-[[example]]
-name = "create_address"
-path = "examples/how_tos/accounts_and_addresses/create_address.rs"
```
Comment (thibault-martinez) [inline sdk/Cargo.toml:245]: Also remove the files of the disabled examples ?

File: sdk/examples/how_tos/accounts_and_addresses/list_transactions.rs
Comment (thibault-martinez) [inline sdk/examples/how_tos/accounts_and_addresses/list_transactions.rs:1]: `of an account.` in the examples header, also look for more pls

File: sdk/examples/how_tos/native_tokens/burn.rs
Comment (thibault-martinez) [inline sdk/examples/how_tos/native_tokens/burn.rs:1]: some more account reference in this

File: sdk/examples/how_tos/native_tokens/destroy_foundry.rs
Comment (thibault-martinez) [inline sdk/examples/how_tos/native_tokens/destroy_foundry.rs:1]: account references

File: sdk/examples/how_tos/native_tokens/melt.rs
Comment (thibault-martinez) [inline sdk/examples/how_tos/native_tokens/melt.rs:1]: account references

File: sdk/examples/how_tos/native_tokens/mint.rs
Comment (thibault-martinez) [inline sdk/examples/how_tos/native_tokens/mint.rs:1]: account references

File: sdk/examples/how_tos/simple_transaction/request_funds.rs
Comment (thibault-martinez) [inline sdk/examples/how_tos/simple_transaction/request_funds.rs:1]: account reference

File: sdk/examples/how_tos/accounts_and_addresses/check_balance.rs
Comment (thibault-martinez) [inline sdk/examples/how_tos/accounts_and_addresses/check_balance.rs:1]: account reference

File: sdk/examples/how_tos/native_tokens/create.rs
Comment (thibault-martinez) [inline sdk/examples/how_tos/native_tokens/create.rs:1]: account

File: sdk/examples/how_tos/accounts_and_addresses/consolidate_outputs.rs
Comment (thibault-martinez) [inline sdk/examples/how_tos/accounts_and_addresses/consolidate_outputs.rs:1]: account

File: sdk/src/wallet/operations/syncing/options.rs [hunk 57]
```diff
@@ -40,9 +40,9 @@ pub struct SyncOptions {
...
     #[serde(default = "default_sync_pending_transactions")]
     pub sync_pending_transactions: bool,
-    /// Specifies what outputs should be synced for the ed25519 addresses from the account.
+    /// Specifies what outputs should be synced for the ed25519 addresses from the wallet.
     #[serde(default)]
-    pub account: AccountSyncOptions,
+    pub wallet: WalletSyncOptions,
     /// Specifies what outputs should be synced for the address of an account output.
     #[serde(default)]
     // TODO Rename when we are done with Account changes https://github.com/iotaledger/iota-sdk/issues/647.
```
Comment (thibault-martinez) [inline sdk/src/wallet/operations/syncing/options.rs]: Idk if you want to, but since you renamed `AccountSyncOptions`, we're able to address this TODO

File: sdk/tests/wallet/migrate_stronghold_snapshot_v2_to_v3.rs [hunk 58]
```diff
@@ -88,7 +89,8 @@ async fn stronghold_snapshot_v2_v3_migration() {
         .with_secret_manager(stronghold_secret_manager)
         .with_client_options(ClientOptions::new().with_node(NODE_LOCAL).unwrap())
         // Build with a different coin type, to check if it gets replaced by the one from the backup
-        .with_coin_type(IOTA_COIN_TYPE)
+        .with_bip_path(Bip44::new(IOTA_COIN_TYPE))
+        .with_alias("0")
```
Comment (thibault-martinez) [inline sdk/tests/wallet/migrate_stronghold_snapshot_v2_to_v3.rs]: Is there no default one?

File: sdk/tests/wallet/error.rs (hunk 43 above)
Comment (thibault-martinez) [reply sdk/tests/wallet/error.rs:14]: I don't see them

File: sdk/src/wallet/operations/syncing/options.rs (hunk 57 above)
Comment (Alex6323) [reply sdk/src/wallet/operations/syncing/options.rs]: Done

File: sdk/tests/wallet/migrate_stronghold_snapshot_v2_to_v3.rs (hunk 58 above)
Comment (Alex6323) [reply sdk/tests/wallet/migrate_stronghold_snapshot_v2_to_v3.rs]: removed

File: bindings/core/src/method/wallet.rs [hunk 59]
```diff
@@ -129,17 +84,14 @@ pub enum WalletMethod {
         #[derivative(Debug(format_with = "OmittedDebug::omitted_fmt"))]
         password: String,
         /// If ignore_if_coin_type_mismatch.is_some(), client options will not be restored.
-        /// If ignore_if_coin_type_mismatch == Some(true), client options coin type and accounts will not be restored
+        /// If ignore_if_coin_type_mismatch == Some(true), client options coin type and wallet will not be restored
         /// if the cointype doesn't match.
         ignore_if_coin_type_mismatch: Option<bool>,
-        /// If ignore_if_bech32_hrp_mismatch == Some("rms"), but addresses have something different like "smr", no
-        /// accounts will be restored.
+        /// If ignore_if_bech32_hrp_mismatch == Some("rms"), but addresses have something different like "smr", the
```
Comment (DaughterOfMars) [inline bindings/core/src/method/wallet.rs]: weird comment

File: bindings/core/src/method_handler/wallet.rs [hunk 60]
```diff
@@ -92,26 +40,6 @@ pub(crate) async fn call_wallet_method_internal(wallet: &Wallet, method: WalletM
...
-                account_dtos.push(AccountDetailsDto::from(&*account));
-            }
-            Response::Accounts(account_dtos)
-        }
-        WalletMethod::RemoveLatestAccount => {
-            wallet.remove_latest_account().await?;
-            Response::Ok
-        }
         #[cfg(feature = "stronghold")]
         WalletMethod::RestoreBackup {
```
Comment (DaughterOfMars) [inline bindings/core/src/method_handler/wallet.rs:41]: So, I feel that we need to better define the difference between `WalletMethod` and `WalletCommandMethod`. To my eyes, they are basically the same right now. Based on the names, things like this `RestoreBackup` should be in `WalletCommandMethod` and things like `WalletCommandMethod::Transactions` should be here instead. This isn't necessarily something we need to change in this PR, but I think we should rework this (or just combine these methods because realistically we do not need both).

File: bindings/core/src/response.rs [hunk 61]
```diff
@@ -55,7 +56,7 @@ use crate::{error::Error, OmittedDebug};
 #[non_exhaustive]
 pub enum Response {
     /// Response for:
-    /// - [`GenerateEd25519Addresses`](crate::method::SecretManagerMethod::GenerateEd25519Addresses)
+    /// - [`GenerateEd25519Address`](crate::method::SecretManagerMethod::GenerateEd25519Addresses)
```
Comment (DaughterOfMars) [inline bindings/core/src/response.rs]: Mismatch here is weird

File: bindings/core/src/method/wallet.rs (hunk 59 above)
Comment (Alex6323) [reply bindings/core/src/method/wallet.rs]: it isn't mine ... I just replaced a word.

File: bindings/core/tests/serialize_error.rs [hunk 62]
```diff
@@ -1,20 +1,35 @@
...
         serde_json::to_string(&error).unwrap(),
         "{\"type\":\"client\",\"error\":\"no healthy node available\"}"
     );
-    let error = Error::Wallet(WalletError::AccountNotFound("Alice".to_string()));
+    // testing a tuple-like error
+    let error = Error::Wallet(WalletError::InvalidMnemonic("nilly willy".to_string()));
     assert_eq!(
         serde_json::to_string(&error).unwrap(),
-        "{\"type\":\"wallet\",\"error\":\"account Alice not found\"}"
+        "{\"type\":\"wallet\",\"error\":\"invalid mnemonic: nilly willy\"}"
```
Comment (DaughterOfMars) [inline bindings/core/tests/serialize_error.rs:25]: use json macro

File: bindings/core/src/method_handler/wallet.rs (hunk 60 above)
Comment (thibault-martinez) [reply bindings/core/src/method_handler/wallet.rs:41]: I agree, I have added an entry in https://github.com/iotaledger/iota-sdk/issues/1521 to deal with it later.

Comment (Alex6323) [reply bindings/core/src/method_handler/wallet.rs:41]: while you were away we discussed this and agree ... but not in this PR. Can you adapt https://github.com/iotaledger/iota-sdk/issues/1521 if necessary?

File: bindings/core/src/response.rs (hunk 61 above)
Comment (Alex6323) [reply bindings/core/src/response.rs]: did you select the right line? this is not a mismatch reponse

File: bindings/core/tests/serialize_error.rs (hunk 62 above)
Comment (Alex6323) [reply bindings/core/tests/serialize_error.rs:25]: not the purpose of this PR to change this ... and it was like this before ... so should be changed in a small separate PR I think.

File: sdk/src/wallet/operations/syncing/addresses/output_ids/mod.rs [hunk 63]
```diff
@@ -49,7 +49,7 @@ where
         // If interested in alias, basic, NFT and foundry outputs, get them all at once
```
Comment (thibault-martinez) [inline sdk/src/wallet/operations/syncing/addresses/output_ids/mod.rs]: account

File: sdk/examples/how_tos/accounts_and_addresses/list_transactions.rs
Comment (Alex6323) [reply sdk/examples/how_tos/accounts_and_addresses/list_transactions.rs:1]: Done (I wished the term "account" would completely vanish from the codebase lol)

File: sdk/src/wallet/core/builder.rs [hunk 64]
```diff
@@ -1,38 +1,38 @@
...
+    types::block::address::{Address, Bech32Address},
+    wallet::{
+        core::{Bip44, WalletData, WalletInner},
+        operations::syncing::SyncOptions,
+        ClientOptions, Wallet,
+    },
 };
 
-/// Builder for the wallet.
+/// Builder for the wallet inner.
```
Comment (DaughterOfMars) [inline sdk/src/wallet/core/builder.rs]: not sure about this

File: sdk/src/wallet/core/builder.rs [hunk 65]
```diff
@@ -63,15 +65,27 @@ where
...
+    }
+
+    /// Set the wallet address.
+    pub fn with_address(mut self, address: impl Into<Option<Bech32Address>>) -> Self {
+        self.address = address.into();
+        self
+    }
+
+    /// Set the alias of the wallet.
+    pub fn with_alias<'a>(mut self, alias: impl Into<Option<&'a str>>) -> Self {
```
Comment (DaughterOfMars) [inline sdk/src/wallet/core/builder.rs]: I realize this is an awkward signature but I wonder if we can do better

File: sdk/src/wallet/core/mod.rs [hunk 66]
```diff
@@ -230,3 +473,254 @@ impl<S: SecretManage> Drop for Wallet<S> {
         log::debug!("drop Wallet");
     }
 }
+
+/// Dto for the wallet data.
+#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
+#[serde(rename_all = "camelCase")]
+pub struct WalletDataDto {
+    /// The BIP44 path of the wallet.
```
Comment (DaughterOfMars) [inline sdk/src/wallet/core/mod.rs]: We can probably remove the doc comments for the Dto

File: sdk/src/wallet/core/operations/stronghold_backup/mod.rs [hunk 67]
```diff
@@ -81,12 +79,7 @@ impl Wallet {
             return Err(crate::wallet::Error::Backup("backup path doesn't exist"));
         }
 
-        // We don't want to overwrite possible existing accounts
-        if !self.accounts.read().await.is_empty() {
-            return Err(crate::wallet::Error::Backup(
-                "can't restore backup when there are already accounts",
-            ));
-        }
+        let mut wallet_data = self.data.write().await;
```
Comment (DaughterOfMars) [inline sdk/src/wallet/core/operations/stronghold_backup/mod.rs:82]: We shouldn't hold these locks across await points

File: sdk/examples/how_tos/account/create.rs [hunk 68]
```diff
@@ -23,10 +23,9 @@ async fn main() -> Result<()> {
         .with_storage_path(&std::env::var("WALLET_DB_PATH").unwrap())
         .finish()
         .await?;
-    let account = wallet.get_account("Alice").await?;
 
-    // May want to ensure the account is synced before sending a transaction.
-    let balance = account.sync(None).await?;
+    // May want to ensure the wallet is synced before sending a transaction.
+    let balance = wallet.sync(None).await?;
     println!("Accounts BEFORE:\n{:#?}", balance.accounts());
```
Comment (DaughterOfMars) [inline sdk/examples/how_tos/account/create.rs:29]: accounts

File: sdk/Cargo.toml (hunk 56 above)
Comment (Alex6323) [reply sdk/Cargo.toml:245]: probably re-inserted during merge. thanks

File: sdk/examples/how_tos/account/destroy.rs [hunk 69]
```diff
@@ -22,11 +22,9 @@ async fn main() -> Result<()> {
...
-    let alias = "Alice";
-    let account = wallet.get_account(alias).await?;
 
-    // May want to ensure the account is synced before sending a transaction.
-    let balance = account.sync(None).await?;
+    // May want to ensure the wallet is synced before sending a transaction.
+    let balance = wallet.sync(None).await?;
 
     // Get the first account
     if let Some(account_id) = balance.accounts().first() {
```
Comment (DaughterOfMars) [inline sdk/examples/how_tos/account/destroy.rs:30]: account

File: sdk/Cargo.toml (hunk 56 above)
Comment (Alex6323) [reply sdk/Cargo.toml:245]: Done

File: sdk/examples/how_tos/native_tokens/burn.rs
Comment (Alex6323) [reply sdk/examples/how_tos/native_tokens/burn.rs:1]: Done

File: sdk/examples/how_tos/native_tokens/destroy_foundry.rs
Comment (Alex6323) [reply sdk/examples/how_tos/native_tokens/destroy_foundry.rs:1]: Done

File: sdk/examples/how_tos/account/create.rs (hunk 68 above)
Comment (thibault-martinez) [reply sdk/examples/how_tos/account/create.rs:29]: This is a valid one :)

File: sdk/examples/how_tos/native_tokens/melt.rs
Comment (Alex6323) [reply sdk/examples/how_tos/native_tokens/melt.rs:1]: Done

File: sdk/examples/how_tos/account/destroy.rs (hunk 69 above)
Comment (thibault-martinez) [reply sdk/examples/how_tos/account/destroy.rs:30]: Valid one

File: sdk/examples/how_tos/native_tokens/mint.rs
Comment (Alex6323) [reply sdk/examples/how_tos/native_tokens/mint.rs:1]: Done

File: sdk/examples/how_tos/simple_transaction/request_funds.rs
Comment (Alex6323) [reply sdk/examples/how_tos/simple_transaction/request_funds.rs:1]: Done

File: sdk/examples/how_tos/accounts_and_addresses/check_balance.rs
Comment (Alex6323) [reply sdk/examples/how_tos/accounts_and_addresses/check_balance.rs:1]: Done

File: sdk/examples/how_tos/native_tokens/create.rs
Comment (Alex6323) [reply sdk/examples/how_tos/native_tokens/create.rs:1]: Done

File: sdk/examples/how_tos/accounts_and_addresses/consolidate_outputs.rs
Comment (Alex6323) [reply sdk/examples/how_tos/accounts_and_addresses/consolidate_outputs.rs:1]: Done

File: sdk/examples/how_tos/account/create.rs (hunk 68 above)
Comment (Alex6323) [reply sdk/examples/how_tos/account/create.rs:29]: in the print we mean account outputs, not wallet accounts

File: sdk/examples/how_tos/account/destroy.rs (hunk 69 above)
Comment (Alex6323) [reply sdk/examples/how_tos/account/destroy.rs:30]: sorry, no

File: sdk/src/wallet/core/builder.rs [hunk 70]
```diff
@@ -144,56 +153,94 @@ where
...
+                    alias
+                });
+
+            self.alias = Some(alias);
         }
-        let coin_type = self.coin_type.ok_or(crate::wallet::Error::MissingParameter(
-            "coin_type (IOTA: 4218, Shimmer: 4219)",
-        ))?;
+        // Panic: can be safely unwrapped now
+        let alias = self.alias.as_ref().unwrap().clone();
```
Comment (DaughterOfMars) [inline sdk/src/wallet/core/builder.rs]: Should the alias just be an option in the wallet?

File: sdk/src/wallet/core/builder.rs [hunk 71]
```diff
@@ -144,56 +153,94 @@ where
...
+        // May create a default Ed25519 wallet address if there's a secret manager.
+        if self.address.is_none() {
+            if self.secret_manager.is_some() {
+                let address = self.create_default_wallet_address().await?;
+                self.address = Some(address);
+            } else {
+                return Err(crate::wallet::Error::MissingParameter("address"));
+            }
+        }
+        // Panic: can be safely unwrapped now
```
Comment (DaughterOfMars) [inline sdk/src/wallet/core/builder.rs:209]: Not if there's no secret manager

File: sdk/src/wallet/core/builder.rs [hunk 72]
```diff
@@ -203,56 +250,88 @@ where
         // It happened that inputs got locked, the transaction failed, but they weren't unlocked again, so we do this
```
Comment (DaughterOfMars) [inline sdk/src/wallet/core/builder.rs:235]: comment could be better

File: sdk/src/wallet/core/builder.rs (hunk 70 above)
Comment (Alex6323) [reply sdk/src/wallet/core/builder.rs]: I think that's reasonable. Changing it ...

**Review by thibault-martinez — COMMENTED** [review]
There is an account reference in the 3 .env.examples files

**Comment by Alex6323** [comment]
> There is an account reference in the 3 .env.examples files

okay, thanks ... fixing them

File: sdk/src/wallet/operations/output_claiming.rs [hunk 73]
```diff
@@ -46,19 +47,19 @@ where
     /// additional inputs
     pub async fn claimable_outputs(&self, outputs_to_claim: OutputsToClaim) -> crate::wallet::Result<Vec<OutputId>> {
         log::debug!("[OUTPUT_CLAIMING] claimable_outputs");
-        let account_details = self.details().await;
+        let wallet_data = self.data().await;
```
Comment (DaughterOfMars) [inline sdk/src/wallet/operations/output_claiming.rs:50]: Is this a lock?

File: sdk/examples/wallet/getting_started.rs
Comment (thibault-martinez) [inline sdk/examples/wallet/getting_started.rs:1]: account reference

File: sdk/examples/wallet/logger.rs [hunk 74]
```diff
@@ -41,20 +39,15 @@ async fn main() -> Result<()> {
...
-    let account = wallet.get_or_create_account("Alice").await?;
-
-    println!("Generating {NUM_ADDRESSES_TO_GENERATE} addresses...");
-    let _ = account
-        .generate_ed25519_addresses(NUM_ADDRESSES_TO_GENERATE, None)
-        .await?;
+    println!("Generating address...");
+    let _ = wallet.generate_ed25519_address(0, 0, None).await?;
 
     println!("Syncing account");
```
Comment (thibault-martinez) [inline sdk/examples/wallet/logger.rs]: hello

File: sdk/src/wallet/core/builder.rs (hunk 72 above)
Comment (Alex6323) [reply sdk/src/wallet/core/builder.rs:235]: sure (I didn't add it tho)

File: sdk/examples/how_tos/account/destroy.rs [hunk 75]
```diff
@@ -4,7 +4,7 @@
 //! In this example we will try to destroy the first account output there is in the account.
```
Comment (thibault-martinez) [inline sdk/examples/how_tos/account/destroy.rs]: hello

File: sdk/src/wallet/operations/syncing/addresses/output_ids/mod.rs [hunk 76]
```diff
@@ -20,41 +20,40 @@ use crate::{
...
     crate::wallet::Error: From<S::Error>,
+    crate::client::Error: From<S::Error>,
 {
     /// Returns output ids for outputs that are directly (Ed25519 address in AddressUnlockCondition) or indirectly
     /// (account/nft address in AddressUnlockCondition and the account/nft output is controlled with the Ed25519
     /// address) connected to
     pub(crate) async fn get_output_ids_for_address(
         &self,
-        address: &Address,
+        address: Bech32Address,
```
Comment (DaughterOfMars) [inline sdk/src/wallet/operations/syncing/addresses/output_ids/mod.rs]: Probably accept a ref here?

File: sdk/src/wallet/operations/output_claiming.rs (hunk 73 above)
Comment (Alex6323) [reply sdk/src/wallet/operations/output_claiming.rs:50]: yes, honestly I would never hand out the lock guard, but probably should be done in a separate PR.

File: sdk/examples/how_tos/account/destroy.rs (hunk 75 above)
Comment (Alex6323) [reply sdk/examples/how_tos/account/destroy.rs]: I promise you I'll never use the word account again in my lifetime.

File: sdk/src/wallet/operations/syncing/mod.rs [hunk 77]
```diff
@@ -145,65 +155,67 @@ where
...
+        let bech32_hrp = self.client().get_bech32_hrp().await?;
 
         loop {
             let new_outputs_data = if new_account_and_nft_addresses.is_empty() {
-                // Get outputs for addresses and add them also the the addresses_with_unspent_outputs
-                let (addresses_with_output_ids, spent_or_not_synced_output_ids_inner) = self
-                    .get_output_ids_for_addresses(options, addresses_to_sync.clone())
+                // Get outputs for the  addresses and add them also the the addresses_with_unspent_outputs
+                let (unspent_output_ids, spent_or_not_synced_output_ids_inner) = self
+                    .get_unspent_and_spent_output_ids_for_addresses(addresses_to_sync.clone(), options)
```
Comment (DaughterOfMars) [inline sdk/src/wallet/operations/syncing/mod.rs]: feels like this could be just `get_output_ids_for_addresses` but I dunno

File: sdk/examples/wallet/logger.rs (hunk 74 above)
Comment (Alex6323) [reply sdk/examples/wallet/logger.rs]: Fixed

File: sdk/src/wallet/storage/constants.rs [hunk 78]
```diff
@@ -15,18 +15,15 @@ pub const fn default_storage_path() -> &'static str {
...
-pub(crate) const ACCOUNTS_INDEXATION_KEY: &str = "iota-wallet-accounts";
-pub(crate) const ACCOUNT_INDEXATION_KEY: &str = "iota-wallet-account-";
-
-pub(crate) const ACCOUNT_SYNC_OPTIONS: &str = "sync-options";
-
 pub(crate) const DATABASE_SCHEMA_VERSION: u8 = 1;
 pub(crate) const DATABASE_SCHEMA_VERSION_KEY: &str = "database-schema-version";
 
+pub(crate) const WALLET_DATA_KEY: &str = "wallet-data";
+pub(crate) const WALLET_BUILDER_KEY: &str = "wallet-builder";
```
Comment (DaughterOfMars) [inline sdk/src/wallet/storage/constants.rs:22]: little weird, maybe we should call this something else?

File: sdk/src/wallet/storage/constants.rs [hunk 79]
```diff
@@ -15,18 +15,15 @@ pub const fn default_storage_path() -> &'static str {
...
+pub(crate) const WALLET_SYNC_OPTIONS: &str = "sync-options";
```
Comment (DaughterOfMars) [inline sdk/src/wallet/storage/constants.rs]:
```suggestion
pub(crate) const WALLET_SYNC_OPTIONS: &str = "wallet-sync-options";
```

File: sdk/src/wallet/storage/constants.rs [hunk 80]
```diff
@@ -15,18 +15,15 @@ pub const fn default_storage_path() -> &'static str {
...
+
+pub(crate) const SECRET_MANAGER_KEY: &str = "secret_manager";
```
Comment (DaughterOfMars) [inline sdk/src/wallet/storage/constants.rs]:
```suggestion
pub(crate) const SECRET_MANAGER_KEY: &str = "secret-manager";
```

File: sdk/src/wallet/operations/syncing/addresses/output_ids/mod.rs (hunk 63 above)
Comment (Alex6323) [reply sdk/src/wallet/operations/syncing/addresses/output_ids/mod.rs]: burned it with fire

File: sdk/src/wallet/operations/transaction/prepare_transaction.rs [hunk 81]
```diff
@@ -71,30 +71,15 @@ where
             }
         }
 
+        // TODO: more readable than `map_or`?
+        #[allow(clippy::option_if_let_else)]
         let remainder_address = match &options {
```
Comment (DaughterOfMars) [inline sdk/src/wallet/operations/transaction/prepare_transaction.rs]: I think the clippy lint is right here

File: sdk/src/wallet/operations/transaction/prepare_output.rs [hunk 82]
```diff
@@ -285,33 +287,23 @@ where
     ) -> crate::wallet::Result<Address> {
         let transaction_options = transaction_options.into();
 
+        // TODO: more readable than `map_or`?
+        #[allow(clippy::option_if_let_else)]
```
Comment (DaughterOfMars) [inline sdk/src/wallet/operations/transaction/prepare_output.rs]: could split into
```
let mut remainder_address = None;
if let Some(options) = &transaction_options {
  ...
}
```

Comment (DaughterOfMars) [reply sdk/src/wallet/operations/transaction/prepare_output.rs]: actually since we re-assign below it should just be one if-let-else

File: sdk/src/wallet/operations/transaction/prepare_transaction.rs (hunk 81 above)
Comment (Alex6323) [reply sdk/src/wallet/operations/transaction/prepare_transaction.rs]: okay. Changing it then ...

File: sdk/src/wallet/update.rs [hunk 83]
```diff
@@ -0,0 +1,211 @@
...
+    pub async fn set_alias(&self, alias: &str) -> crate::wallet::Result<()> {
+        let mut wallet_data = self.data_mut().await;
+        wallet_data.alias = alias.to_string();
+        #[cfg(feature = "storage")]
+        self.save(Some(&wallet_data)).await?;
+        Ok(())
+    }
+
+    /// Update wallet with newly synced data and emit events for outputs.
+    pub(crate) async fn update(
```
Comment (DaughterOfMars) [inline sdk/src/wallet/update.rs]: better name?

File: sdk/src/wallet/update.rs [hunk 84]
```diff
@@ -0,0 +1,211 @@
...
+            log::debug!(
+                "[SYNC] storing wallet {} with new synced transactions",
+                wallet_data.alias
+            );
+            self.save(Some(&wallet_data)).await?;
+        }
+        Ok(())
+    }
+
+    /// Update the wallet address with a possible new Bech32 HRP and clear the inaccessible_incoming_transactions.
```
Comment (DaughterOfMars) [inline sdk/src/wallet/update.rs]:
```suggestion
    /// Update the wallet address with a possible new Bech32 HRP and clear the inaccessible incoming transactions.
```

File: bindings/core/tests/serialize_error.rs (hunk 62 above)
Comment (DaughterOfMars) [reply bindings/core/tests/serialize_error.rs:25]: alright, I guess

File: bindings/core/src/response.rs (hunk 61 above)
Comment (DaughterOfMars) [reply bindings/core/src/response.rs]: the mismatch is that the response is multiple addresses for a single address call

File: sdk/src/wallet/update.rs (hunk 83 above)
Comment (Alex6323) [reply sdk/src/wallet/update.rs]: yeah, it's a bit generic now. I think it was called `update_accounts` before. Suggestions?

File: sdk/src/wallet/update.rs (hunk 84 above)
Comment (Alex6323) [reply sdk/src/wallet/update.rs]: fine with me. But I guess @thibault-martinez might be opinionated here?

File: bindings/core/src/method_handler/wallet.rs (hunk 60 above)
Comment (kwek20) [reply bindings/core/src/method_handler/wallet.rs:41]: Yea had the same comment, suggesting manager and wallet maybe

File: sdk/examples/how_tos/nfts/burn_nft.rs [hunk 85]
```diff
@@ -54,11 +52,11 @@ async fn main() -> Result<()> {
 
         println!("Burned NFT '{}'", nft_id);
 
-        let balance = account.sync(None).await?;
+        let balance = wallet.sync(None).await?;
         let nfts_after = balance.nfts();
         println!("Balance after burning:\n{nfts_after:#?}",);
     } else {
-        println!("No NFT available in account '{alias}'");
+        println!("No NFT available in the wallet");
```
Comment (kwek20) [inline sdk/examples/how_tos/nfts/burn_nft.rs:59]: we can still use alias right? i think we should make a new issue discussing what we do with alias now

Comment (thibault-martinez) [reply sdk/examples/how_tos/nfts/burn_nft.rs:59]: We keep an alias in the wallet but it just doesn't really make sense to use it like that in the examples tbh

File: sdk/src/wallet/operations/syncing/mod.rs (hunk 77 above)
Comment (Alex6323) [reply sdk/src/wallet/operations/syncing/mod.rs]: edit of the edit: changing it

File: bindings/core/src/method/wallet.rs [hunk 86]
```diff
@@ -31,35 +24,12 @@ use crate::OmittedDebug;
...
     /// Returns [`Response`](crate::Response)
     #[serde(rename_all = "camelCase")]
-    CallAccountMethod {
-        /// The account identifier.
-        account_id: AccountIdentifier,
-        /// The account method to call.
-        method: AccountMethod,
+    CallMethod {
+        /// The wallet command method to call.
+        method: super::WalletCommandMethod,
```
Comment (thibault-martinez) [inline bindings/core/src/method/wallet.rs]: import it like the others pls

File: bindings/core/src/method_handler/wallet_operation.rs [hunk 87]
```diff
@@ -0,0 +1,283 @@
...
+    types::{
+        block::output::{dto::OutputDto, Output},
+        TryFromDto,
+    },
+    wallet::{types::TransactionWithMetadataDto, OutputDataDto, PreparedCreateNativeTokenTransactionDto, Wallet},
+};
+
+use crate::{method::WalletCommandMethod, Response, Result};
+
+pub(crate) async fn call_wallet_operation_method_internal(
```
Comment (thibault-martinez) [inline bindings/core/src/method_handler/wallet_operation.rs]: This is really confusing, operation or command? Pick one

File: sdk/src/wallet/operations/syncing/mod.rs (hunk 77 above)
Comment (Alex6323) [reply sdk/src/wallet/operations/syncing/mod.rs]: Done

File: sdk/src/wallet/core/mod.rs [hunk 88]
```diff
@@ -213,15 +456,15 @@ impl<S: SecretManage> WalletInner<S> {
     }
 
     #[cfg(feature = "events")]
```
Comment (kwek20) [inline sdk/src/wallet/core/mod.rs:458]: Im thinking maybe we want to emit with alias? or add to the alias questions

File: sdk/examples/wallet/spammer.rs [hunk 89]
```diff
@@ -86,15 +100,15 @@ async fn main() -> Result<()> {
         let mut tasks = tokio::task::JoinSet::<std::result::Result<(), (usize, iota_sdk::wallet::Error)>>::new();
 
         for n in 0..num_simultaneous_txs {
-            let account_clone = account.clone();
-            let recv_address = recv_address.clone();
+            let recv_address_clone = recv_address.clone();
+            let account_clone = wallet.clone();
```
Comment (thibault-martinez) [inline sdk/examples/wallet/spammer.rs]: remove the suffixes

File: sdk/src/wallet/storage/constants.rs (hunk 78 above)
Comment (Alex6323) [reply sdk/src/wallet/storage/constants.rs:22]: happy to hear suggestions @thibault-martinez @kwek20 @Thoralf-M ?

File: sdk/src/wallet/core/mod.rs (hunk 88 above)
Comment (thibault-martinez) [reply sdk/src/wallet/core/mod.rs:458]: Open an issue, but that doesn't strike me as a very useful feature. It was needed for users to know which account the event was from but now there is only one thing that could emit it.

File: bindings/core/src/method_handler/wallet_operation.rs (hunk 87 above)
Comment (thibault-martinez) [reply bindings/core/src/method_handler/wallet_operation.rs]: (I'd go with operation temporarily until/if we merge the two enums)

File: sdk/src/wallet/operations/participation/event.rs (hunk 55 above)
Comment (thibault-martinez) [reply sdk/src/wallet/operations/participation/event.rs]: This hasn't been addressed

File: sdk/src/wallet/core/mod.rs (hunk 88 above)
Comment (Alex6323) [reply sdk/src/wallet/core/mod.rs:458]: is this rather #issue material?

File: bindings/core/src/method/wallet.rs (hunk 86 above)
Comment (Alex6323) [reply bindings/core/src/method/wallet.rs]: Done

File: sdk/src/wallet/core/mod.rs (hunk 88 above)
Comment (kwek20) [reply sdk/src/wallet/core/mod.rs:458]: yea but are we not making this with the idea that users create themselves multiple wallets? odds are, the same method isused to receive events for all wallets.

File: bindings/core/src/method_handler/wallet_operation.rs (hunk 87 above)
Comment (Alex6323) [reply bindings/core/src/method_handler/wallet_operation.rs]: Renamed (decided to rename to `call_wallet_command_method_internal`), otherwise the enum would have to be renamed to make it consistent. Will be changed probably anyway when we merge both enums)

File: sdk/examples/wallet/spammer.rs (hunk 89 above)
Comment (Alex6323) [reply sdk/examples/wallet/spammer.rs]: Done

File: sdk/src/wallet/core/mod.rs (hunk 88 above)
Comment (thibault-martinez) [reply sdk/src/wallet/core/mod.rs:458]: What happens above the Wallet layer is not really our responsibility anymore, I wouldn't plan for such use cases no

Comment (thibault-martinez) [reply sdk/src/wallet/core/mod.rs:458]: That is just my opinion, as I said feel free to open an issue to discuss it!

File: sdk/examples/how_tos/nfts/burn_nft.rs (hunk 85 above)
Comment (Alex6323) [reply sdk/examples/how_tos/nfts/burn_nft.rs:59]: the alias is a convenience thing now if you like separating your wallets like we did before with the accounts: `main`, `savings`, `kid a`, `kid_b`, ... In the examples it's enough to show that you can give your wallet an alias in the "getting_started" one.

File: sdk/src/wallet/core/operations/stronghold_backup/mod.rs [hunk 90]
```diff
@@ -145,40 +136,24 @@ impl Wallet {
             fs::copy(backup_path, new_snapshot_path)?;
         }
 
-        // drop secret manager, otherwise we get a deadlock in set_client_options() (there inside of save_wallet_data())
```
Comment (kwek20) [inline sdk/src/wallet/core/operations/stronghold_backup/mod.rs:148]: found a whoopsie

Comment (Alex6323) [reply sdk/src/wallet/core/operations/stronghold_backup/mod.rs:148]: thanks

File: sdk/src/wallet/core/builder.rs (hunk 65 above)
Comment (Alex6323) [reply sdk/src/wallet/core/builder.rs]: we can just use `String` here, the & was mostly for example convenience.

File: sdk/src/wallet/core/builder.rs (hunk 72 above)
Comment (Alex6323) [reply sdk/src/wallet/core/builder.rs:235]: okay ... Gh not showing this at the correct line, but inside VSCode it shows up where it makes sense. Finding something better...

File: sdk/src/wallet/operations/syncing/addresses/output_ids/mod.rs (hunk 76 above)
Comment (Alex6323) [reply sdk/src/wallet/operations/syncing/addresses/output_ids/mod.rs]: Done

File: sdk/src/wallet/operations/participation/event.rs (hunk 55 above)
Comment (Alex6323) [reply sdk/src/wallet/operations/participation/event.rs]: on it ...

File: sdk/tests/wallet/error.rs (hunk 43 above)
Comment (Alex6323) [reply sdk/tests/wallet/error.rs:14]: oh, I changed the test in the bindings, not this one, should be fixed now

File: sdk/src/wallet/operations/participation/event.rs (hunk 55 above)
Comment (Alex6323) [reply sdk/src/wallet/operations/participation/event.rs]: Done

File: sdk/src/wallet/update.rs (hunk 84 above)
Comment (Alex6323) [reply sdk/src/wallet/update.rs]: changing...

File: sdk/src/wallet/operations/participation/event.rs (hunk 55 above)
Comment (thibault-martinez) [reply sdk/src/wallet/operations/participation/event.rs]: There is still one `inner`

File: bindings/core/src/method_handler/wallet_operation.rs (hunk 87 above)
Comment (thibault-martinez) [reply bindings/core/src/method_handler/wallet_operation.rs]: File hasn't been renamed

File: sdk/src/wallet/operations/transaction/prepare_output.rs (hunk 82 above)
Comment (Alex6323) [reply sdk/src/wallet/operations/transaction/prepare_output.rs]: Done

File: sdk/src/wallet/operations/transaction/prepare_transaction.rs (hunk 81 above)
Comment (Alex6323) [reply sdk/src/wallet/operations/transaction/prepare_transaction.rs]: Done

File: sdk/src/wallet/core/mod.rs (hunk 88 above)
Comment (Thoralf-M) [reply sdk/src/wallet/core/mod.rs:458]: https://github.com/iotaledger/iota-sdk/issues/1544

File: sdk/examples/how_tos/nfts/burn_nft.rs (hunk 85 above)
Comment (thibault-martinez) [reply sdk/examples/how_tos/nfts/burn_nft.rs:59]: https://github.com/iotaledger/iota-sdk/issues/1544

File: sdk/src/wallet/storage/constants.rs (hunk 78 above)
Comment (DaughterOfMars) [reply sdk/src/wallet/storage/constants.rs:22]: maybe just wallet?

Comment (DaughterOfMars) [reply sdk/src/wallet/storage/constants.rs:22]: or `wallet-config`

File: sdk/src/wallet/operations/transaction/prepare_transaction.rs [hunk 91]
```diff
@@ -71,20 +71,13 @@ where
...
-                    RemainderValueStrategy::ReuseAddress => {
-                        // select_inputs will select an address from the inputs if it's none
-                        None
-                    }
-                    RemainderValueStrategy::CustomAddress(address) => Some(address.clone()),
-                }
-            }
-            None => None,
-        };
+        let remainder_address = options.as_ref().map_or_else(
```
Comment (DaughterOfMars) [inline sdk/src/wallet/operations/transaction/prepare_transaction.rs]: Just a regular map should do

Comment (DaughterOfMars) [reply sdk/src/wallet/operations/transaction/prepare_transaction.rs]: or maybe and_then

File: bindings/core/src/method/wallet.rs (hunk 59 above)
Comment (DaughterOfMars) [reply bindings/core/src/method/wallet.rs]: yeah, I know, but regardless it is weird and it's not difficult to fix these things while you touch the code around them

File: sdk/src/wallet/update.rs (hunk 83 above)
Comment (DaughterOfMars) [reply sdk/src/wallet/update.rs]: maybe `update_after_sync`?

File: sdk/src/wallet/core/builder.rs (hunk 72 above)
Comment (thibault-martinez) [reply sdk/src/wallet/core/builder.rs:235]: Let's keep it for now, there will 100% be a refactoring of this file soon, we'll clean up the comments then

File: sdk/src/wallet/core/mod.rs (hunk 66 above)
Comment (thibault-martinez) [reply sdk/src/wallet/core/mod.rs]: I think this has been addressed

File: sdk/src/wallet/storage/constants.rs (hunk 78 above)
Comment (thibault-martinez) [reply sdk/src/wallet/storage/constants.rs:22]: Honestly I'd keep these questions for later, we have no clue what the database with look like in the future. Adding it to https://github.com/iotaledger/iota-sdk/issues/1521

File: sdk/src/wallet/operations/transaction/prepare_transaction.rs (hunk 91 above)
Comment (thibault-martinez) [reply sdk/src/wallet/operations/transaction/prepare_transaction.rs]: Using and_then now

File: sdk/src/wallet/core/builder.rs (hunk 64 above)
Comment (thibault-martinez) [reply sdk/src/wallet/core/builder.rs]: Removed the inner

File: sdk/src/wallet/core/operations/background_syncing.rs [hunk 92]
```diff
@@ -49,18 +49,13 @@ where
...
-                            Ok(_) => {}
-                            Err(err) => log::debug!("[background_syncing] error: {}", err),
-                        };
-                    }
+                    log::debug!("[background_syncing]: syncing wallet");
+
+                    match wallet.sync(options.clone()).await {
+                        Ok(_) => {}
+                        Err(err) => log::debug!("[background_syncing] error: {}", err),
+                    };
```
Comment (Thoralf-M) [inline sdk/src/wallet/core/operations/background_syncing.rs]:
```suggestion
                    if let Err(err) = wallet.sync(options.clone()).await {
                        log::debug!("[background_syncing] error: {}", err)
                    }
```

File: bindings/core/src/response.rs (hunk 61 above)
Comment (thibault-martinez) [reply bindings/core/src/response.rs]: Fixed

File: sdk/src/wallet/update.rs (hunk 83 above)
Comment (thibault-martinez) [reply sdk/src/wallet/update.rs]: Changed

File: sdk/src/wallet/storage/constants.rs (hunk 78 above)
Comment (DaughterOfMars) [reply sdk/src/wallet/storage/constants.rs:22]: alrighty

**Review by DaughterOfMars — DISMISSED** [review]

**Review by Thoralf-M — APPROVED** [review]

**Review by thibault-martinez — APPROVED** [review]
