### PR TITLE
fix: default number of workers for  `Miner` to `num_cpu::get()`

### LINKED ISSUE #516: Use num_cpu::get() as default PoW worker count
## Description

Use num_cpu::get() as default PoW worker count

## Motivation

Faster PoW

## Requirements

1. Currently by default `DEFAULT_NUM_WORKERS: usize = 1;` is used which is slow

## Are you planning to do it yourself in a pull request?

No.

### PR DESCRIPTION
**Pull request by qrayven**
# Description of change

Default number of workers for nonce `Miner` changed from `1` to `num_cpu::get()`

## Links to any relevant issues

closes #516 

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Enhancement (a non-breaking change which adds functionality)

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by thibault-martinez — APPROVED** [review]

**Review by thibault-martinez — CHANGES_REQUESTED** [review]
Clippy

**Review by thibault-martinez — APPROVED** [review]

File: sdk/src/pow/miner.rs [hunk 1]
```diff
@@ -82,7 +80,7 @@ impl MinerBuilder {
     /// Builds the [`Miner`].
     pub fn finish(self) -> Miner {
         Miner {
-            num_workers: self.num_workers.unwrap_or(DEFAULT_NUM_WORKERS),
```
Comment (kwek20) [inline sdk/src/pow/miner.rs:85]: pretty sure this isnt implemented for wasm, could you test it for wasm32-unknown-unknown and otherwise fall back to 1 on wasm?

Comment (qrayven) [reply sdk/src/pow/miner.rs:85]: I was surprised either. `num_cpus` support the `wasm` targets. When wam is used, the `1`  is returned.

**Review by DaughterOfMars — APPROVED** [review]

**Review by Thoralf-M — APPROVED** [review]
