### PR TITLE
Fix `BigInt` serialization in Wasm.

### LINKED ISSUE #924: [Bug]: TypeError: Do not know how to serialize a BigInt
### Issue description

Building an output with a native token throws an error: `TypeError: Do not know how to serialize a BigInt`

### Version

Wasm bindings built from `6a856129bfd57a71a3567f05d7811b2b9cc30a43`.

### Expected behaviour

The example succeeds.

### Actual behaviour

The example fails.

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

Run this example to reproduce:

```typescript
const client = new Client({
        primaryNode: API_ENDPOINT,
        localPow: true,
    });

    const address = Utils.parseBech32Address("tst1qzkly6hllhscsaqy2le6f4dfymanx6nze2anf2qhlsy4m2zc5rrs5sy83ms")
    const tokenId: string = Utils.computeTokenId("0xf000000000000000000000000000000000000000000000000000000000000000", 1, TokenSchemeType.Simple);

    client.buildBasicOutput({
      unlockConditions: [new AddressUnlockCondition(address)],
      nativeTokens: [
        
          {
              id: tokenId,
              amount: BigInt(500_000),
          },
      
      ]
    })
```

### Errors

```
~/git/iota-sdk/bindings/wasm/out/lib/client/client-method-handler.ts:31
            JSON.stringify(method),
                 ^
TypeError: Do not know how to serialize a BigInt
    at JSON.stringify (<anonymous>)
    at ClientMethodHandler.callMethod (~/git/iota-sdk/bindings/wasm/out/lib/client/client-method-handler.ts:31:18)
    at Client.buildBasicOutput (~/git/iota-sdk/bindings/wasm/out/lib/client/client.ts:933:51)
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### PR DESCRIPTION
**Pull request by abdulmth**
# Description of change

Fixes serialization error in Wasm since `bindings.ts` was modified in node.js but not in Wasm.

Also maybe worth noting that we patch a built-in object to allow the serialization, although it's for `BigInt` "[not explicitly discouraged](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt#use_within_json)"  it might conflict with user patching `BigInt` too (I'm not sure how common is that, probably pretty rare), the solution could be to convert `bigint` values manually to a hex string for the native token amounts everywhere it's used. 

### Note
The issue can be resolved on the current `1.0.1` release by the user manually running: 

```
(BigInt.prototype as any).toJSON = function() {
    return '0x' + this.toString(16);
};
```

## Links to any relevant issues

fixes #924

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Bug fix (a non-breaking change which fixes an issue)

### CODE REVIEW

**Review by Thoralf-M — DISMISSED** [review]

File: bindings/wasm/lib/bindings.ts [hunk 1]
```diff
@@ -20,6 +20,15 @@ const callUtilsMethod = (method: __UtilsMethods__): any => {
     }
 };
 
+// Allow bigint to be serialized as hex string.
+//
+// Note:
+// Serializing `bigint` to a different format, e.g. to decimal number string
+// must be done manually.
```
Comment (thibault-martinez) [inline bindings/wasm/lib/bindings.ts]: Are there not currently places where this would then have to be changed?

Comment (thibault-martinez) [reply bindings/wasm/lib/bindings.ts]: Or maybe another question, this isn't inherited from the nodejs bindings ?

Comment (abdulmth) [reply bindings/wasm/lib/bindings.ts]: Yes, only `bindings.ts` is different between Wasm and Node.js. In other places it's inherited from Node.js

Comment (thibault-martinez) [reply bindings/wasm/lib/bindings.ts]: So if this was somewhere else than in `bindings.ts`, we wouldn't have to duplicate it ? Shouldn't we just move it then?

Comment (abdulmth) [reply bindings/wasm/lib/bindings.ts]: I moved it to `index.ts`, probably `bindings.ts` fits better, but in `index.ts` we don't need to duplicate.

File: bindings/nodejs/lib/bindings.ts [hunk 2]
```diff
@@ -100,15 +100,6 @@ const callWalletMethodAsync = (
...
 
-// Allow bigint to be serialized as hex string.
-//
-// Note:
-// Serializing `bigint` to a different format, e.g. to decimal number string
-// must be done manually.
-(BigInt.prototype as any).toJSON = function () {
-    return bigIntToHex(this);
-};
-
```
Comment (thibault-martinez) [inline bindings/nodejs/lib/bindings.ts:111]: Is it breaking change to move it? Was it directly accessible through bindings.ts?

Comment (abdulmth) [reply bindings/nodejs/lib/bindings.ts:111]: No it's not breaking, it just adds the function `toJSON` to `BigInt`, no matter where it's called from.

File: bindings/wasm/CHANGELOG.md [hunk 3]
```diff
@@ -19,6 +19,14 @@ and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0
 
 ### Security -->
 
+## 1.0.2 - 2023-MM-DD
+
+Same changes as https://github.com/iotaledger/iota-sdk/blob/develop/bindings/nodejs/CHANGELOG.md.
+
+### Fixed
+
+- Runtime serializtion error of `BigInt` when working with native token amounts;
```
Comment (thibault-martinez) [inline bindings/wasm/CHANGELOG.md:28]: Not exactly sure what's best, but technically this hasn't been done in this crate anymore

Comment (abdulmth) [reply bindings/wasm/CHANGELOG.md:28]: But it was broken in Wasm and now it's fixed 🤷🏻

Comment (thibault-martinez) [reply bindings/wasm/CHANGELOG.md:28]: Yeah but I mean, not because of a change in the wasm bindings, let me think about it

Comment (abdulmth) [reply bindings/wasm/CHANGELOG.md:28]: Technically it is, it was copied from somewhere else, but it's a part of the Wasm bindings.

**Review by Thoralf-M — APPROVED** [review]

File: bindings/wasm/CHANGELOG.md (hunk 3 above)
Comment (thibault-martinez) [reply bindings/wasm/CHANGELOG.md:28]: Alright 👍🏻

**Review by thibault-martinez — APPROVED** [review]
