### PR TITLE
fix(storage): fix record decryption

### LINKED ISSUE #354: [Bug]: Wallet Db record encryption/decryption
### Issue description

This is a test that I added:

```rust=
    #[cfg(feature = "rand")]
    #[tokio::test]
    async fn get_set_encrypted() {
        #[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
        struct Record {
            a: String,
            b: u32,
            c: i64,
        }

        let encryption_key = crate::types::block::rand::bytes::rand_bytes_array::<32>();

        let mut storage = Storage {
            inner: Box::<Memory>::default(),
            encryption_key: Some(encryption_key),
        };

        let rec = Record { a: "test".to_string(), b: 42, c: -420 };
        storage.set("key", rec.clone()).await.unwrap();

        assert_eq!(Some(rec), storage.get::<Record>("key").await.unwrap());
    }
```

It should pass. However, it fails with:

```sh
running 1 test
thread 'wallet::storage::tests::get_set_encrypted' panicked at 'called `Result::unwrap()` on an `Err` value: Crypto(CipherError { alg: "XCHACHA20-POLY1305" })', sdk/src/wallet/storage/mod.rs:266:66
stack backtrace:
   0: rust_begin_unwind
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/result.rs:1750:5
   3: core::result::Result<T,E>::unwrap
   4: iota_sdk::wallet::storage::tests::get_set_encrypted::{{closure}}
   5: <core::pin::Pin<P> as core::future::future::Future>::poll
   6: <core::pin::Pin<P> as core::future::future::Future>::poll
   7: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}::{{closure}}
   8: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}
   9: tokio::runtime::scheduler::current_thread::Context::enter
  10: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}
  11: tokio::runtime::scheduler::current_thread::CoreGuard::enter::{{closure}}
  12: tokio::macros::scoped_tls::ScopedKey<T>::set
  13: tokio::runtime::scheduler::current_thread::CoreGuard::enter
  14: tokio::runtime::scheduler::current_thread::CoreGuard::block_on
  15: tokio::runtime::scheduler::current_thread::CurrentThread::block_on
  16: tokio::runtime::runtime::Runtime::block_on
  17: iota_sdk::wallet::storage::tests::get_set_encrypted
  18: iota_sdk::wallet::storage::tests::get_set_encrypted::{{closure}}
  19: core::ops::function::FnOnce::call_once
  20: core::ops::function::FnOnce::call_once
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
test wallet::storage::tests::get_set_encrypted ... FAILED

failures:

failures:
    wallet::storage::tests::get_set_encrypted

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 29 filtered out; finished in 0.01s
```

Printing the error yields:
```sh
error in algorithm XCHACHA20-POLY1305
```
### Version

1.0.0-rc2

### Expected behaviour

This test should pass.

### Actual behaviour

The previously inserted record should be successfully decrypted and idential to the record that was inserted. The decryption part fails though.

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. set an encryption key
2. create a record and insert it
3. try to get the record

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### PR DESCRIPTION
**Pull request by Alex6323**
# Description of change

Fixes decrypting previously encrypted records from storage.

## Links to any relevant issues

Closes #354 

## Type of change

- Bug fix (a non-breaking change which fixes an issue)

## How the change has been tested

Unit test.

### CODE REVIEW

File: sdk/src/wallet/storage/mod.rs [hunk 1]
```diff
@@ -159,14 +156,13 @@ mod tests {
 
         storage.batch_set(records).await.unwrap();
 
-        assert!(storage.get::<Record>("0").await.unwrap().is_some());
-        assert!(storage.get::<Record>("9").await.unwrap().is_some());
+        for index in 0..10 {
```
Comment (DaughterOfMars) [inline sdk/src/wallet/storage/mod.rs]: assert_eq?

Comment (Alex6323) [reply sdk/src/wallet/storage/mod.rs]: Done

File: sdk/src/wallet/storage/mod.rs [hunk 2]
```diff
@@ -63,17 +63,21 @@ impl Storage {
     }
 
     #[allow(dead_code)]
-    async fn batch_set(&mut self, records: HashMap<String, String>) -> crate::wallet::Result<()> {
+    async fn batch_set<T: Serialize + Send>(&mut self, records: HashMap<String, T>) -> crate::wallet::Result<()> {
```
Comment (DaughterOfMars) [inline sdk/src/wallet/storage/mod.rs]: Only problem with this is that is forces all the records to be the same type.

Comment (Alex6323) [reply sdk/src/wallet/storage/mod.rs]: yeah, that's right ... I assumed that would be the case for a batch, but you're right ... that doesn't have to be the case.

Comment (DaughterOfMars) [reply sdk/src/wallet/storage/mod.rs]: It breaks the function, because the point of it is to set many fields of different types. That said, I think we shoulf just remove it anyway.

Comment (Alex6323) [reply sdk/src/wallet/storage/mod.rs]: Yeah, I see. Changed it back. Removing it should be a separate issue/pr I think.

**Review by thibault-martinez — APPROVED** [review]

**Review by qrayven — APPROVED** [review]

**Review by Thoralf-M — APPROVED** [review]
