### PR TITLE
Fix prepare_output() with ReturnStrategy::Gift

### LINKED ISSUE #1027: [Bug]: Prepare Output amount for returnStrategy: Gift
### Issue description

Amount not calculated correctly when using `prepareOutput` with `returnStrategy: Gift`

https://github.com/iotaledger/firefly/pull/7174#issuecomment-1680809500

### Version

"@iota/sdk": "1.0.4"

### Expected behaviour

correctly calculate amount

### Actual behaviour

amount not correct

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

_No response_

### Errors

_No response_

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### PR DESCRIPTION
**Pull request by Thoralf-M**
# Description of change

Fix `Account::prepare_output()` when `ReturnStrategy::Gift` is used with an existing NFT output

## Links to any relevant issues

Fixes https://github.com/iotaledger/iota-sdk/issues/1027

## Type of change

- Bug fix (a non-breaking change which fixes an issue)

## How the change has been tested

Added test

## Change checklist

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

File: sdk/src/wallet/account/operations/transaction/prepare_output.rs [hunk 1]
```diff
@@ -110,6 +110,13 @@ where
         let min_storage_deposit_basic_output =
             MinimumStorageDepositBasicOutput::new(rent_structure, token_supply).finish()?;
 
+        let min_required_storage_deposit = if nft_id.is_some() {
+            let min_storage_deposit_nft_output = Output::Nft(first_output.as_nft().clone()).rent_cost(&rent_structure);
+            min_storage_deposit_basic_output.max(min_storage_deposit_nft_output)
```
Comment (thibault-martinez) [inline sdk/src/wallet/account/operations/transaction/prepare_output.rs]: Not asking to remove the max, but isn't Nft assured to be > Basic?

Comment (Thoralf-M) [reply sdk/src/wallet/account/operations/transaction/prepare_output.rs]: In this case true, only if the basic output has features or more unlock conditions it could be different, but currently this isn't checked at this place, will check tomorrow if this also needs to be considered at this place or not

Comment (Thoralf-M) [reply sdk/src/wallet/account/operations/transaction/prepare_output.rs]: Updated it

**Review by thibault-martinez — DISMISSED** [review]

**Review by DaughterOfMars — DISMISSED** [review]

**Review by thibault-martinez — APPROVED** [review]

**Review by qrayven — APPROVED** [review]
