### PR TITLE
ISA: error on InvalidChainStateTransition, fix example

### LINKED ISSUE #285: [Bug]: Error Client(TransactionSemantic(InvalidChainStateTransition))
### Issue description

ISA is returning inputs that are only later detected as InvalidChainStateTransition

### Version

develop

### Expected behaviour

ISA should error already

### Actual behaviour

Inputs are returned which will create an InvalidChainStateTransition

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

Update state metadata and try to transition and output with such features https://explorer.shimmer.network/testnet/output/0x6babddc820b4b9b75fb6ac38f4975dca7c8f163c368324ce698c92aed9cacc8c0000

### Errors

```
2023-04-19 09:44:28 (UTC) iota_sdk::wallet::account::operations::transaction::input_selection DEBUG [TRANSACTION] select_inputs
2023-04-19 09:44:28 (UTC) iota_sdk::client::api::block_builder::input_selection::core::requirement DEBUG Adding Alias(AliasId(0x8b11ad08f637bc426d11fbcfacd492c93b06fbdcce292b525a4a9f0bbbe9f391), Governance) from output
2023-04-19 09:44:28 (UTC) iota_sdk::client::api::block_builder::input_selection::core::requirement DEBUG Adding Sender(Ed25519Address(0xbcb601a35721bce20a4eb456631fa4dda25ef134ffa6dbb0888cca6b303784e5)) from output
2023-04-19 09:44:28 (UTC) iota_sdk::client::api::block_builder::input_selection::core::requirement DEBUG Fulfilling requirement Sender(Ed25519Address(0xbcb601a35721bce20a4eb456631fa4dda25ef134ffa6dbb0888cca6b303784e5))
2023-04-19 09:44:28 (UTC) iota_sdk::client::api::block_builder::input_selection::core::requirement::sender DEBUG Treating Ed25519Address(0xbcb601a35721bce20a4eb456631fa4dda25ef134ffa6dbb0888cca6b303784e5) sender requirement as an ed25519 requirement
2023-04-19 09:44:28 (UTC) iota_sdk::client::api::block_builder::input_selection::core::requirement::ed25519 DEBUG Ed25519Address(0xbcb601a35721bce20a4eb456631fa4dda25ef134ffa6dbb0888cca6b303784e5) sender requirement fulfilled by OutputId(0xe9d5373a9ccacc6232d7621d6eaf73d8afcf2855c7b21c39a5e41db2a3c445000200) (alias transition None)
2023-04-19 09:44:28 (UTC) iota_sdk::client::api::block_builder::input_selection::core DEBUG Selecting input OutputId(0xe9d5373a9ccacc6232d7621d6eaf73d8afcf2855c7b21c39a5e41db2a3c445000200)
2023-04-19 09:44:28 (UTC) iota_sdk::client::api::block_builder::input_selection::core::requirement DEBUG Fulfilling requirement Alias(AliasId(0x8b11ad08f637bc426d11fbcfacd492c93b06fbdcce292b525a4a9f0bbbe9f391), Governance)
2023-04-19 09:44:28 (UTC) iota_sdk::client::api::block_builder::input_selection::core::requirement::alias DEBUG AliasId(0x8b11ad08f637bc426d11fbcfacd492c93b06fbdcce292b525a4a9f0bbbe9f391)/Governance requirement fulfilled by OutputId(0x6babddc820b4b9b75fb6ac38f4975dca7c8f163c368324ce698c92aed9cacc8c0000)
2023-04-19 09:44:28 (UTC) iota_sdk::client::api::block_builder::input_selection::core DEBUG Selecting input OutputId(0x6babddc820b4b9b75fb6ac38f4975dca7c8f163c368324ce698c92aed9cacc8c0000)
2023-04-19 09:44:28 (UTC) iota_sdk::client::api::block_builder::input_selection::core::transition DEBUG No transition of OutputId(0x6babddc820b4b9b75fb6ac38f4975dca7c8f163c368324ce698c92aed9cacc8c0000)/AliasId(0x8b11ad08f637bc426d11fbcfacd492c93b06fbdcce292b525a4a9f0bbbe9f391) as output already exists
2023-04-19 09:44:28 (UTC) iota_sdk::client::api::block_builder::input_selection::core DEBUG Adding Ed25519(Ed25519Address(0xbcb601a35721bce20a4eb456631fa4dda25ef134ffa6dbb0888cca6b303784e5)) from input OutputId(0x6babddc820b4b9b75fb6ac38f4975dca7c8f163c368324ce698c92aed9cacc8c0000)
2023-04-19 09:44:28 (UTC) iota_sdk::client::api::block_builder::input_selection::core::requirement DEBUG Fulfilling requirement Ed25519(Ed25519Address(0xbcb601a35721bce20a4eb456631fa4dda25ef134ffa6dbb0888cca6b303784e5))
2023-04-19 09:44:28 (UTC) iota_sdk::client::api::block_builder::input_selection::core::requirement::ed25519 DEBUG Ed25519Address(0xbcb601a35721bce20a4eb456631fa4dda25ef134ffa6dbb0888cca6b303784e5) sender requirement already fulfilled by OutputId(0xe9d5373a9ccacc6232d7621d6eaf73d8afcf2855c7b21c39a5e41db2a3c445000200)
2023-04-19 09:44:28 (UTC) iota_sdk::client::api::block_builder::input_selection::core::requirement DEBUG Fulfilling requirement NativeTokens
2023-04-19 09:44:28 (UTC) iota_sdk::client::api::block_builder::input_selection::core::requirement::native_tokens DEBUG Native tokens requirement already fulfilled
2023-04-19 09:44:28 (UTC) iota_sdk::client::api::block_builder::input_selection::core::requirement DEBUG Fulfilling requirement Amount
2023-04-19 09:44:28 (UTC) iota_sdk::client::api::block_builder::input_selection::core::requirement::amount DEBUG Amount requirement already fulfilled
2023-04-19 09:44:28 (UTC) iota_sdk::client::api::block_builder::input_selection::core::remainder DEBUG Created storage deposit return output of 234000 for Ed25519Address(0xbcb601a35721bce20a4eb456631fa4dda25ef134ffa6dbb0888cca6b303784e5)
2023-04-19 09:44:28 (UTC) iota_sdk::client::api::block_builder::input_selection::core::remainder DEBUG Created remainder output of 940200 for Ed25519Address(0xbcb601a35721bce20a4eb456631fa4dda25ef134ffa6dbb0888cca6b303784e5)
2023-04-19 09:44:28 (UTC) iota_sdk::wallet::account::operations::transaction::input_selection DEBUG [TRANSACTION] locking: 0xe9d5373a9ccacc6232d7621d6eaf73d8afcf2855c7b21c39a5e41db2a3c445000200
2023-04-19 09:44:28 (UTC) iota_sdk::wallet::account::operations::transaction::input_selection DEBUG [TRANSACTION] locking: 0x6babddc820b4b9b75fb6ac38f4975dca7c8f163c368324ce698c92aed9cacc8c0000
2023-04-19 09:44:28 (UTC) iota_sdk::wallet::account::operations::transaction::build_transaction DEBUG [TRANSACTION] build_transaction
2023-04-19 09:44:28 (UTC) iota_sdk::wallet::account::operations::transaction::build_transaction DEBUG [TRANSACTION] finished build_transaction in 14.95µs
2023-04-19 09:44:28 (UTC) iota_sdk::wallet::account::operations::transaction::prepare_transaction DEBUG [TRANSACTION] finished prepare_transaction in 398.99µs
2023-04-19 09:44:28 (UTC) iota_sdk::wallet::account::operations::transaction DEBUG [TRANSACTION] sign_and_submit_transaction
2023-04-19 09:44:28 (UTC) iota_sdk::wallet::account::operations::transaction::sign_transaction DEBUG [TRANSACTION] sign_transaction_essence
2023-04-19 09:44:28 (UTC) iota_sdk::wallet::account::operations::transaction::sign_transaction DEBUG [TRANSACTION] prepared_transaction_data PreparedTransactionData { essence: Regular(RegularTransactionEssence { network_id: 1856588631910923207, inputs: [UtxoInput(0xe9d5373a9ccacc6232d7621d6eaf73d8afcf2855c7b21c39a5e41db2a3c445000200), UtxoInput(0x6babddc820b4b9b75fb6ac38f4975dca7c8f163c368324ce698c92aed9cacc8c0000)], inputs_commitment: InputsCommitment(0xec480ec194e047534865ab08d1e43a4b9bb8da09960d035b189a1af2c3179e31), outputs: [AliasOutput { amount: 59900, native_tokens: NativeTokens([]), alias_id: AliasId(0x8b11ad08f637bc426d11fbcfacd492c93b06fbdcce292b525a4a9f0bbbe9f391), state_index: 1, state_metadata: [117, 112, 100, 97, 116, 101, 100, 32, 115, 116, 97, 116, 101, 32, 109, 101, 116, 97, 100, 97, 116, 97], foundry_counter: 1, unlock_conditions: UnlockConditions([StateControllerAddressUnlockCondition(Ed25519Address(0xbcb601a35721bce20a4eb456631fa4dda25ef134ffa6dbb0888cca6b303784e5)), GovernorAddressUnlockCondition(Ed25519Address(0xbcb601a35721bce20a4eb456631fa4dda25ef134ffa6dbb0888cca6b303784e5))]), features: Features([SenderFeature(Ed25519Address(0xbcb601a35721bce20a4eb456631fa4dda25ef134ffa6dbb0888cca6b303784e5)), MetadataFeature(0x010203)]), immutable_features: Features([IssuerFeature(Ed25519Address(0xbcb601a35721bce20a4eb456631fa4dda25ef134ffa6dbb0888cca6b303784e5))]) }, BasicOutput { amount: 940200, native_tokens: NativeTokens([]), unlock_conditions: UnlockConditions([AddressUnlockCondition(Ed25519Address(0xbcb601a35721bce20a4eb456631fa4dda25ef134ffa6dbb0888cca6b303784e5))]), features: Features([]) }, BasicOutput { amount: 234000, native_tokens: NativeTokens([]), unlock_conditions: UnlockConditions([AddressUnlockCondition(Ed25519Address(0xbcb601a35721bce20a4eb456631fa4dda25ef134ffa6dbb0888cca6b303784e5))]), features: Features([]) }], payload: OptionalPayload(None) }), inputs_data: [InputSigningData { output: BasicOutput { amount: 234100, native_tokens: NativeTokens([]), unlock_conditions: UnlockConditions([AddressUnlockCondition(Ed25519Address(0xbcb601a35721bce20a4eb456631fa4dda25ef134ffa6dbb0888cca6b303784e5)), StorageDepositReturnUnlockCondition { return_address: Ed25519Address(0xbcb601a35721bce20a4eb456631fa4dda25ef134ffa6dbb0888cca6b303784e5), amount: 234000 }]), features: Features([]) }, output_metadata: OutputMetadata { block_id: BlockId(0x8643ab6c734786e973a594520ad71777d3952cebbc8e94340de58c5b22ab18b4), output_id: OutputId(0xe9d5373a9ccacc6232d7621d6eaf73d8afcf2855c7b21c39a5e41db2a3c445000200), is_spent: false, milestone_index_spent: None, milestone_timestamp_spent: None, transaction_id_spent: None, milestone_index_booked: 295432, milestone_timestamp_booked: 1659611206, ledger_index: 4723224 }, chain: Some(Chain([Segment { hardened: true, bs: [128, 0, 0, 44] }, Segment { hardened: true, bs: [128, 0, 16, 123] }, Segment { hardened: true, bs: [128, 0, 0, 0] }, Segment { hardened: true, bs: [128, 0, 0, 0] }, Segment { hardened: true, bs: [128, 0, 0, 0] }])) }, InputSigningData { output: AliasOutput { amount: 1000000, native_tokens: NativeTokens([]), alias_id: AliasId(0x8b11ad08f637bc426d11fbcfacd492c93b06fbdcce292b525a4a9f0bbbe9f391), state_index: 1, state_metadata: [], foundry_counter: 1, unlock_conditions: UnlockConditions([StateControllerAddressUnlockCondition(Ed25519Address(0xbcb601a35721bce20a4eb456631fa4dda25ef134ffa6dbb0888cca6b303784e5)), GovernorAddressUnlockCondition(Ed25519Address(0xbcb601a35721bce20a4eb456631fa4dda25ef134ffa6dbb0888cca6b303784e5))]), features: Features([SenderFeature(Ed25519Address(0xbcb601a35721bce20a4eb456631fa4dda25ef134ffa6dbb0888cca6b303784e5)), MetadataFeature(0x010203)]), immutable_features: Features([IssuerFeature(Ed25519Address(0xbcb601a35721bce20a4eb456631fa4dda25ef134ffa6dbb0888cca6b303784e5))]) }, output_metadata: OutputMetadata { block_id: BlockId(0x56accb5f85c1b6037b7c9d5576992f6fece8caa6f7ab5ee46980725a9e3a59bd), output_id: OutputId(0x6babddc820b4b9b75fb6ac38f4975dca7c8f163c368324ce698c92aed9cacc8c0000), is_spent: false, milestone_index_spent: None, milestone_timestamp_spent: None, transaction_id_spent: None, milestone_index_booked: 249156, milestone_timestamp_booked: 1659379826, ledger_index: 4723224 }, chain: Some(Chain([Segment { hardened: true, bs: [128, 0, 0, 44] }, Segment { hardened: true, bs: [128, 0, 16, 123] }, Segment { hardened: true, bs: [128, 0, 0, 0] }, Segment { hardened: true, bs: [128, 0, 0, 0] }, Segment { hardened: true, bs: [128, 0, 0, 0] }])) }], remainder: Some(RemainderData { output: BasicOutput { amount: 940200, native_tokens: NativeTokens([]), unlock_conditions: UnlockConditions([AddressUnlockCondition(Ed25519Address(0xbcb601a35721bce20a4eb456631fa4dda25ef134ffa6dbb0888cca6b303784e5))]), features: Features([]) }, chain: Some(Chain([Segment { hardened: true, bs: [128, 0, 0, 44] }, Segment { hardened: true, bs: [128, 0, 16, 123] }, Segment { hardened: true, bs: [128, 0, 0, 0] }, Segment { hardened: true, bs: [128, 0, 0, 0] }, Segment { hardened: true, bs: [128, 0, 0, 0] }])), address: Ed25519Address(0xbcb601a35721bce20a4eb456631fa4dda25ef134ffa6dbb0888cca6b303784e5) }) }
2023-04-19 09:44:28 (UTC) iota_sdk::wallet::account::operations::transaction::sign_transaction DEBUG [TRANSACTION] signed transaction: TransactionPayload { essence: Regular(RegularTransactionEssence { network_id: 1856588631910923207, inputs: [UtxoInput(0xe9d5373a9ccacc6232d7621d6eaf73d8afcf2855c7b21c39a5e41db2a3c445000200), UtxoInput(0x6babddc820b4b9b75fb6ac38f4975dca7c8f163c368324ce698c92aed9cacc8c0000)], inputs_commitment: InputsCommitment(0xec480ec194e047534865ab08d1e43a4b9bb8da09960d035b189a1af2c3179e31), outputs: [AliasOutput { amount: 59900, native_tokens: NativeTokens([]), alias_id: AliasId(0x8b11ad08f637bc426d11fbcfacd492c93b06fbdcce292b525a4a9f0bbbe9f391), state_index: 1, state_metadata: [117, 112, 100, 97, 116, 101, 100, 32, 115, 116, 97, 116, 101, 32, 109, 101, 116, 97, 100, 97, 116, 97], foundry_counter: 1, unlock_conditions: UnlockConditions([StateControllerAddressUnlockCondition(Ed25519Address(0xbcb601a35721bce20a4eb456631fa4dda25ef134ffa6dbb0888cca6b303784e5)), GovernorAddressUnlockCondition(Ed25519Address(0xbcb601a35721bce20a4eb456631fa4dda25ef134ffa6dbb0888cca6b303784e5))]), features: Features([SenderFeature(Ed25519Address(0xbcb601a35721bce20a4eb456631fa4dda25ef134ffa6dbb0888cca6b303784e5)), MetadataFeature(0x010203)]), immutable_features: Features([IssuerFeature(Ed25519Address(0xbcb601a35721bce20a4eb456631fa4dda25ef134ffa6dbb0888cca6b303784e5))]) }, BasicOutput { amount: 940200, native_tokens: NativeTokens([]), unlock_conditions: UnlockConditions([AddressUnlockCondition(Ed25519Address(0xbcb601a35721bce20a4eb456631fa4dda25ef134ffa6dbb0888cca6b303784e5))]), features: Features([]) }, BasicOutput { amount: 234000, native_tokens: NativeTokens([]), unlock_conditions: UnlockConditions([AddressUnlockCondition(Ed25519Address(0xbcb601a35721bce20a4eb456631fa4dda25ef134ffa6dbb0888cca6b303784e5))]), features: Features([]) }], payload: OptionalPayload(None) }), unlocks: Unlocks([SignatureUnlock(Ed25519Signature { public_key: 0x8c483a5239706d0e033b8d29e07682e86b5ba93de5396d3493b679cb7087f277, signature: 0x7830427955c96b168dc7eef80f4eb56794c491daff780395e3d78940eff8a8094aaf0b0f7f56a06fb62d0e7b779b7f9ff9e3a1d7eabea4c39b084c791190ec00 }), ReferenceUnlock(BoundedU16(0))]) }
2023-04-19 09:44:28 (UTC) iota_sdk::wallet::account::operations::transaction DEBUG [TRANSACTION] submit_and_store_transaction 0x0be475835b5b3a20c66e7bf72b0ac3bce2ba23a86ec55f61b063ce41ed34380f
2023-04-19 09:44:28 (UTC) iota_sdk::wallet::account::operations::transaction DEBUG [TRANSACTION] conflict: InvalidChainStateTransition for TransactionPayload { essence: Regular(RegularTransactionEssence { network_id: 1856588631910923207, inputs: [UtxoInput(0xe9d5373a9ccacc6232d7621d6eaf73d8afcf2855c7b21c39a5e41db2a3c445000200), UtxoInput(0x6babddc820b4b9b75fb6ac38f4975dca7c8f163c368324ce698c92aed9cacc8c0000)], inputs_commitment: InputsCommitment(0xec480ec194e047534865ab08d1e43a4b9bb8da09960d035b189a1af2c3179e31), outputs: [AliasOutput { amount: 59900, native_tokens: NativeTokens([]), alias_id: AliasId(0x8b11ad08f637bc426d11fbcfacd492c93b06fbdcce292b525a4a9f0bbbe9f391), state_index: 1, state_metadata: [117, 112, 100, 97, 116, 101, 100, 32, 115, 116, 97, 116, 101, 32, 109, 101, 116, 97, 100, 97, 116, 97], foundry_counter: 1, unlock_conditions: UnlockConditions([StateControllerAddressUnlockCondition(Ed25519Address(0xbcb601a35721bce20a4eb456631fa4dda25ef134ffa6dbb0888cca6b303784e5)), GovernorAddressUnlockCondition(Ed25519Address(0xbcb601a35721bce20a4eb456631fa4dda25ef134ffa6dbb0888cca6b303784e5))]), features: Features([SenderFeature(Ed25519Address(0xbcb601a35721bce20a4eb456631fa4dda25ef134ffa6dbb0888cca6b303784e5)), MetadataFeature(0x010203)]), immutable_features: Features([IssuerFeature(Ed25519Address(0xbcb601a35721bce20a4eb456631fa4dda25ef134ffa6dbb0888cca6b303784e5))]) }, BasicOutput { amount: 940200, native_tokens: NativeTokens([]), unlock_conditions: UnlockConditions([AddressUnlockCondition(Ed25519Address(0xbcb601a35721bce20a4eb456631fa4dda25ef134ffa6dbb0888cca6b303784e5))]), features: Features([]) }, BasicOutput { amount: 234000, native_tokens: NativeTokens([]), unlock_conditions: UnlockConditions([AddressUnlockCondition(Ed25519Address(0xbcb601a35721bce20a4eb456631fa4dda25ef134ffa6dbb0888cca6b303784e5))]), features: Features([]) }], payload: OptionalPayload(None) }), unlocks: Unlocks([SignatureUnlock(Ed25519Signature { public_key: 0x8c483a5239706d0e033b8d29e07682e86b5ba93de5396d3493b679cb7087f277, signature: 0x7830427955c96b168dc7eef80f4eb56794c491daff780395e3d78940eff8a8094aaf0b0f7f56a06fb62d0e7b779b7f9ff9e3a1d7eabea4c39b084c791190ec00 }), ReferenceUnlock(BoundedU16(0))]) }
2023-04-19 09:44:28 (UTC) iota_sdk::wallet::account::operations::transaction DEBUG [TRANSACTION] Unlocked output 0xe9d5373a9ccacc6232d7621d6eaf73d8afcf2855c7b21c39a5e41db2a3c445000200 because of transaction error
2023-04-19 09:44:28 (UTC) iota_sdk::wallet::account::operations::transaction DEBUG [TRANSACTION] Unlocked output 0x6babddc820b4b9b75fb6ac38f4975dca7c8f163c368324ce698c92aed9cacc8c0000 because of transaction error
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### PR DESCRIPTION
**Pull request by Thoralf-M**
# Description of change

ISA: error on InvalidChainStateTransition
Validate utxo chain transitions
Fix example and add tests

## Links to any relevant issues

Fixes #285 

## Type of change

- Bug fix (a non-breaking change which fixes an issue)

## How the change has been tested

Running the example and tests

## Change checklist

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by thibault-martinez — COMMENTED** [review]
Changelog worthy?

File: sdk/src/client/api/block_builder/input_selection/core/transition.rs [hunk 1]
```diff
@@ -35,12 +35,22 @@ impl InputSelection {
...
+        if let Some(alias_output) = self
             .outputs
             .iter()
-            .any(|output| is_alias_with_id_non_null(output, &alias_id))
+            .find(|output| is_alias_with_id_non_null(output, &alias_id))
         {
             log::debug!("No transition of {output_id:?}/{alias_id:?} as output already exists");
+
+            if (alias_output.as_alias().state_metadata() != input.state_metadata())
+                && (alias_output.as_alias().state_index() == input.state_index())
```
Comment (thibault-martinez) [inline sdk/src/client/api/block_builder/input_selection/core/transition.rs]: It's not only `state_metadata` though, right? It's also amount, native_tokens and foundry_counter. And we should also check state transition.

Comment (thibault-martinez) [reply sdk/src/client/api/block_builder/input_selection/core/transition.rs]: Which makes me think we could use `StateTransitionVerifier::transition` if we manage to extract the context-related parts

Comment (Thoralf-M) [reply sdk/src/client/api/block_builder/input_selection/core/transition.rs]: Yeah also thought about that, but I'm not sure if we can check this at this place or if we need to do that at the end after we selected all inputs, because some foundry outputs might not be selected already and then it would fail :thinking:

Comment (thibault-martinez) [reply sdk/src/client/api/block_builder/input_selection/core/transition.rs]: Yeah but it's very arbitrary to check `state_metadata` only :/

Comment (Thoralf-M) [reply sdk/src/client/api/block_builder/input_selection/core/transition.rs]: I think I found a way that's okay now and checks all things

File: sdk/src/types/block/output/mod.rs [hunk 2]
```diff
@@ -323,9 +323,12 @@ impl Output {
...
             // Transitions.
-            (Some(Self::Alias(current_state)), Some(Self::Alias(next_state))) => {
-                AliasOutput::transition(current_state, next_state, context)
-            }
+            (Some(Self::Alias(current_state)), Some(Self::Alias(next_state))) => AliasOutput::transition(
+                current_state,
+                next_state,
+                &context.input_chains,
+                context.essence.outputs(),
+            ),
```
Comment (thibault-martinez) [inline sdk/src/types/block/output/mod.rs]: You don't really need to change that? I'd revert

File: sdk/src/types/block/output/foundry.rs [hunk 3]
```diff
@@ -210,6 +210,10 @@ impl FoundryOutputBuilder {
 
         verify_allowed_features(&immutable_features, FoundryOutput::ALLOWED_IMMUTABLE_FEATURES)?;
 
+        if self.serial_number == 0 {
```
Comment (thibault-martinez) [inline sdk/src/types/block/output/foundry.rs]: Check it first to avoid the previous operations that are more expensive

File: sdk/CHANGELOG.md [hunk 4]
```diff
@@ -28,6 +28,10 @@ and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0
 - `StrongholdAdapter::inner` method;
 - `OutputMetadata::set_spent` method;
 - `ignore_if_bech32_mismatch` parameter to `Wallet::restore_backup()`;
+- Validation for transitions in the input selection;
+- Automatically increase foundry counter of alias outputs;
+- `types::block::Error::InvalidZeroSerialNumber` variant;
+- Validate that foundry outputs can't have serial number `0`;
```
Comment (thibault-martinez) [inline sdk/CHANGELOG.md]: Some of this sounds like a fix 🤔

File: sdk/src/client/api/block_builder/input_selection/core/transition.rs [hunk 5]
```diff
@@ -44,11 +44,24 @@ impl InputSelection {
             return Ok(None);
         }
 
+        let mut highest_foundry_serial_number = 0;
+        for output in self.outputs.iter() {
+            if let Output::Foundry(foundry) = output {
+                if let ChainId::Foundry(foundry_id) = foundry.chain_id() {
```
Comment (thibault-martinez) [inline sdk/src/client/api/block_builder/input_selection/core/transition.rs]: You don't need to go through the chain_id? just call `id()`

Comment (Thoralf-M) [reply sdk/src/client/api/block_builder/input_selection/core/transition.rs]: Thanks, I searched for the wrong name and didn't found it

File: sdk/src/types/block/output/mod.rs (hunk 2 above)
Comment (Thoralf-M) [reply sdk/src/types/block/output/mod.rs]: Was needed because of the same name and the imported trait, changed the name and reverted

File: sdk/src/client/api/block_builder/input_selection/core/transition.rs (hunk 5 above)
Comment (thibault-martinez) [reply sdk/src/client/api/block_builder/input_selection/core/transition.rs]: Maybe we should rename it... I initially didn't do it because I wanted to show that it's computing it and not returning it. But yeah, not sure if we really care

File: sdk/tests/client/input_selection/nft_outputs.rs [hunk 6]
```diff
@@ -585,7 +592,7 @@ fn missing_ed25519_issuer_transition() {
     )
     .select();
 
-    assert!(selected.is_ok());
+    assert!(selected.is_err());
```
Comment (thibault-martinez) [inline sdk/tests/client/input_selection/nft_outputs.rs]: I'm confused, how were these tests passing?
Anyway, for all newly `is_err` tests, can you test the actually expected error please?

Comment (Thoralf-M) [reply sdk/tests/client/input_selection/nft_outputs.rs]: Also not sure, but it failed for another reason `validate_transitions error MutatedImmutableField` :trollface:

Comment (thibault-martinez) [reply sdk/tests/client/input_selection/nft_outputs.rs]: But can you make it so they actually test what they should please?

Comment (Thoralf-M) [reply sdk/tests/client/input_selection/nft_outputs.rs]: Sure on it, failed because issuer is ignored if the alias is not newly created which is checked by the null id, but we built it with another alias id

File: sdk/src/client/api/block_builder/input_selection/core/transition.rs [hunk 7]
```diff
@@ -44,11 +44,22 @@ impl InputSelection {
             return Ok(None);
         }
 
+        let mut highest_foundry_serial_number = 0;
+        for output in self.outputs.iter() {
+            if let Output::Foundry(foundry) = output {
+                if *foundry.id().alias_address().alias_id() == alias_id {
```
Comment (thibault-martinez) [inline sdk/src/client/api/block_builder/input_selection/core/transition.rs]: You don't need to go through the ID to get the alias_address

File: sdk/src/client/api/block_builder/input_selection/core/transition.rs [hunk 8]
```diff
@@ -44,11 +44,22 @@ impl InputSelection {
...
+                    highest_foundry_serial_number =
+                        u32::max(highest_foundry_serial_number, foundry.id().serial_number());
```
Comment (thibault-martinez) [inline sdk/src/client/api/block_builder/input_selection/core/transition.rs]: Same with the serial_number

File: sdk/tests/client/input_selection/burn.rs [hunk 9]
```diff
@@ -735,21 +735,21 @@ fn burn_foundries_present() {
...
-            1,
+            2,
             SimpleTokenScheme::new(U256::from(0), U256::from(0), U256::from(10)).unwrap(),
             None,
         ),
         Alias(
             1_000_000,
             alias_id_1,
-            0,
+            2,
```
Comment (thibault-martinez) [inline sdk/tests/client/input_selection/burn.rs:752]: Is this checked? I changed it back to 0 locally and it passed

File: sdk/tests/client/input_selection/nft_outputs.rs [hunk 10]
```diff
@@ -585,7 +591,10 @@ fn missing_ed25519_issuer_transition() {
     )
     .select();
 
-    assert!(selected.is_ok());
+    assert!(matches!(
+        selected,
+        Err(Error::UnfulfillableRequirement(Requirement::Issuer(issuer))) if issuer == Address::try_from_bech32(BECH32_ADDRESS_ED25519_1).unwrap()
+    ));
```
Comment (thibault-martinez) [inline sdk/tests/client/input_selection/nft_outputs.rs]: Now that I think about it, the test was correct. It actually tests on purpose that a missing issuer has no effect on transitions. There is `missing_ed25519_issuer_created` before that does exactly what you are doing now.

File: sdk/src/client/api/block_builder/input_selection/core/mod.rs [hunk 11]
```diff
@@ -403,10 +403,97 @@ impl InputSelection {
...
+                        .find(|i| {
+                            if let Output::Nft(nft_input) = &i.output {
+                                *nft_output.nft_id() == nft_input.nft_id_non_null(i.output_id())
+                            } else {
+                                false
+                            }
+                        })
+                        .expect("ISA is broken because there is no nft input");
+
+                    if nft_input.output.as_nft().immutable_features() != nft_output.immutable_features() {
```
Comment (thibault-martinez) [inline sdk/src/client/api/block_builder/input_selection/core/mod.rs]: I know it's annoying for so few checks but I would do the same and call the actual transition checker, to be future proof.

File: sdk/src/client/api/block_builder/input_selection/core/mod.rs [hunk 12]
```diff
@@ -403,10 +403,97 @@ impl InputSelection {
...
+                    input_chains_foundries.insert(foundry.chain_id(), &input.output);
+                }
+                Output::Nft(_) => {
+                    input_nfts.push(input);
+                }
+                _ => {}
+            }
+        }
+
+        // Validate alias output transition
```
Comment (thibault-martinez) [inline sdk/src/client/api/block_builder/input_selection/core/mod.rs]: Not only alias...

File: sdk/src/client/api/block_builder/input_selection/core/mod.rs [hunk 13]
```diff
@@ -403,10 +403,97 @@ impl InputSelection {
...
+                                false
+                            }
+                        })
+                        .expect("ISA is broken because there is no nft input");
+
+                    if nft_input.output.as_nft().immutable_features() != nft_output.immutable_features() {
+                        return Err(Error::UnfulfillableRequirement(Requirement::Nft(*nft_output.nft_id())));
+                    }
+                }
+                _ => {}
```
Comment (thibault-martinez) [inline sdk/src/client/api/block_builder/input_selection/core/mod.rs:535]: What about foundry transitions?

File: sdk/src/client/api/block_builder/input_selection/core/mod.rs (hunk 12 above)
Comment (Thoralf-M) [inline sdk/src/client/api/block_builder/input_selection/core/mod.rs:434]:
```suggestion
        // Validate alias and nft output transition
```

File: sdk/tests/client/input_selection/burn.rs (hunk 9 above)
Comment (Thoralf-M) [reply sdk/tests/client/input_selection/burn.rs:752]: It doesn't matter what we have there (currently since we don't validate creation), can also undo

Comment (thibault-martinez) [reply sdk/tests/client/input_selection/burn.rs:752]: Why doesn't it matter?

Comment (Thoralf-M) [reply sdk/tests/client/input_selection/burn.rs:752]: Because we don't provide it in the outputs

Comment (thibault-martinez) [reply sdk/tests/client/input_selection/burn.rs:752]: Ok, still keep 2, it makes sense. Was just wondering why it didn't fail.

File: sdk/tests/client/input_selection/nft_outputs.rs (hunk 10 above)
Comment (Thoralf-M) [reply sdk/tests/client/input_selection/nft_outputs.rs]: It wasn't correct, but the input should then also have the issuer already, is that what you mean?

File: sdk/src/client/api/block_builder/input_selection/core/mod.rs (hunk 13 above)
Comment (Thoralf-M) [reply sdk/src/client/api/block_builder/input_selection/core/mod.rs:535]: Thought about doing it in a separate PR, but it's actually not that much, will also do it

Comment (Thoralf-M) [reply sdk/src/client/api/block_builder/input_selection/core/mod.rs:535]: Done

**Review by thibault-martinez — CHANGES_REQUESTED** [review]
Clippy

File: sdk/CHANGELOG.md [hunk 14]
```diff
@@ -29,6 +29,9 @@ and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0
 - `OutputMetadata::set_spent` method;
 - `ignore_if_bech32_mismatch` parameter to `Wallet::restore_backup()`;
 - `OutputWithMetadata::{into_output, into_metadata}` methods;
+- Validation for transitions in the input selection;
```
Comment (thibault-martinez) [inline sdk/CHANGELOG.md]: You have some duplicates between Added and Fixed

File: sdk/src/client/api/block_builder/input_selection/core/mod.rs (hunk 12 above)
Comment (thibault-martinez) [inline sdk/src/client/api/block_builder/input_selection/core/mod.rs]: Did you fail a merge/rebase? I swear this was fixed at some point

Comment (Thoralf-M) [reply sdk/src/client/api/block_builder/input_selection/core/mod.rs]: Yes, thanks

File: sdk/tests/client/input_selection/nft_outputs.rs [hunk 15]
```diff
@@ -707,7 +713,10 @@ fn missing_alias_issuer_transition() {
     )
     .select();
 
-    assert!(selected.is_ok());
+    assert!(matches!(
+        selected,
+        Err(Error::UnfulfillableRequirement(Requirement::Issuer(issuer))) if issuer == Address::try_from_bech32(BECH32_ADDRESS_ALIAS_1).unwrap()
+    ));
```
Comment (thibault-martinez) [inline sdk/tests/client/input_selection/nft_outputs.rs]: This should stay is_ok

File: sdk/tests/client/input_selection/nft_outputs.rs [hunk 16]
```diff
@@ -829,7 +837,10 @@ fn missing_nft_issuer_transition() {
     )
     .select();
 
-    assert!(selected.is_ok());
+    assert!(matches!(
+        selected,
+        Err(Error::UnfulfillableRequirement(Requirement::Issuer(issuer))) if issuer == Address::try_from_bech32(BECH32_ADDRESS_NFT_1).unwrap()
+    ));
```
Comment (thibault-martinez) [inline sdk/tests/client/input_selection/nft_outputs.rs]: same

File: sdk/tests/client/input_selection/alias_outputs.rs [hunk 17]
```diff
@@ -785,7 +793,10 @@ fn missing_alias_issuer_transition() {
     )
     .select();
 
-    assert!(selected.is_ok());
+    assert!(matches!(
+        selected,
+        Err(Error::UnfulfillableRequirement(Requirement::Issuer(issuer))) if issuer == Address::try_from_bech32(BECH32_ADDRESS_ALIAS_1).unwrap()
+    ));
```
Comment (thibault-martinez) [inline sdk/tests/client/input_selection/alias_outputs.rs]: Same as the others, this should stay is_ok

File: sdk/tests/client/input_selection/alias_outputs.rs [hunk 18]
```diff
@@ -907,7 +917,10 @@ fn missing_nft_issuer_transition() {
     )
     .select();
 
-    assert!(selected.is_ok());
+    assert!(matches!(
+        selected,
+        Err(Error::UnfulfillableRequirement(Requirement::Issuer(issuer))) if issuer == Address::try_from_bech32(BECH32_ADDRESS_NFT_1).unwrap()
+    ));
```
Comment (thibault-martinez) [inline sdk/tests/client/input_selection/alias_outputs.rs]: same

File: sdk/tests/client/input_selection/foundry_outputs.rs [hunk 19]
```diff
@@ -72,14 +80,28 @@ fn existing_input_alias_for_foundry_alias() {
...
+                Address::try_from_bech32(BECH32_ADDRESS_ED25519_0).unwrap(),
+            ))
+            .add_unlock_condition(GovernorAddressUnlockCondition::new(
+                Address::try_from_bech32(BECH32_ADDRESS_ED25519_0).unwrap(),
+            ))
+            .with_state_index(1)
+            .with_foundry_counter(1)
+            .finish_output(protocol_parameters.token_supply())
+            .unwrap(),
+    );
```
Comment (thibault-martinez) [inline sdk/tests/client/input_selection/foundry_outputs.rs]: What's that for? Should work fine without? Isn't it even better without so it's supposed to pick the right values?

File: sdk/tests/client/input_selection/foundry_outputs.rs [hunk 20]
```diff
@@ -107,7 +129,7 @@ fn minted_native_tokens_in_new_remainder() {
     let alias_id_2 = AliasId::from_str(ALIAS_ID_2).unwrap();
 
     let inputs = build_inputs(vec![
-        Basic(1_000_000, BECH32_ADDRESS_ED25519_0, None, None, None, None, None, None),
+        Basic(2_000_000, BECH32_ADDRESS_ED25519_0, None, None, None, None, None, None),
```
Comment (thibault-martinez) [inline sdk/tests/client/input_selection/foundry_outputs.rs]: Why?

File: sdk/tests/client/input_selection/foundry_outputs.rs (hunk 19 above)
Comment (thibault-martinez) [reply sdk/tests/client/input_selection/foundry_outputs.rs]: Oh is that because of the foundry counter that we can't set with the enum?

Comment (Thoralf-M) [reply sdk/tests/client/input_selection/foundry_outputs.rs]: I added that  before I automatically updated the state index, undid the change now :+1:

File: sdk/tests/client/input_selection/foundry_outputs.rs (hunk 20 above)
Comment (Thoralf-M) [reply sdk/tests/client/input_selection/foundry_outputs.rs]: Probably updated because it was necessary somewhere else, changed back

File: sdk/tests/client/input_selection/alias_outputs.rs [hunk 21]
```diff
@@ -2291,3 +2306,100 @@ fn sender_in_governor_but_not_owned() {
...
+
+    let outputs = vec![updated_alias_output];
+
+    let selected = InputSelection::new(
+        inputs.clone(),
+        outputs.clone(),
+        addresses(vec![BECH32_ADDRESS_ED25519_0]),
+        protocol_parameters,
+    )
+    .required_inputs(HashSet::from_iter([*inputs[0].output_id()]))
```
Comment (thibault-martinez) [inline sdk/tests/client/input_selection/alias_outputs.rs]: Just checking, is this necessary? You have the alias as output so requirement will make the input mandatory anyway?

File: sdk/tests/client/input_selection/alias_outputs.rs [hunk 22]
```diff
@@ -2291,3 +2306,100 @@ fn sender_in_governor_but_not_owned() {
...
+
+    let outputs = vec![updated_alias_output];
+
+    let selected = InputSelection::new(
+        inputs.clone(),
+        outputs,
+        addresses(vec![BECH32_ADDRESS_ED25519_0]),
+        protocol_parameters,
+    )
+    .required_inputs(HashSet::from_iter([*inputs[0].output_id()]))
```
Comment (thibault-martinez) [inline sdk/tests/client/input_selection/alias_outputs.rs]: Same?

File: sdk/tests/client/input_selection/alias_outputs.rs [hunk 23]
```diff
@@ -2291,3 +2306,100 @@ fn sender_in_governor_but_not_owned() {
...
+    .select();
+
+    assert!(matches!(
+        selected,
+        Err(Error::UnfulfillableRequirement(Requirement::Alias(
+            alias_id,
+            _alias_transition,
```
Comment (thibault-martinez) [inline sdk/tests/client/input_selection/alias_outputs.rs:2400]: Should we actually test that it's expecting a state transition?

File: sdk/tests/client/input_selection/alias_outputs.rs (hunk 21 above)
Comment (Thoralf-M) [reply sdk/tests/client/input_selection/alias_outputs.rs]: True not needed

File: sdk/tests/client/input_selection/alias_outputs.rs (hunk 23 above)
Comment (Thoralf-M) [reply sdk/tests/client/input_selection/alias_outputs.rs:2400]: Not sure about that, could also be that it's doing an invalid state metadata mutation

File: sdk/tests/client/input_selection/foundry_outputs.rs [hunk 24]
```diff
@@ -688,73 +711,54 @@ fn simple_foundry_transition_basic_not_needed_with_remainder() {
...
-                );
-            } else {
-                panic!("unexpected output type")
-            }
-        }
-    });
+    assert!(matches!(
+        selected,
+        Err(Error::UnfulfillableRequirement(Requirement::Foundry(id))) if id == foundry_id
+    ));
```
Comment (thibault-martinez) [inline sdk/tests/client/input_selection/foundry_outputs.rs:761]: Is it not possible to mint and burn at the same time?

Comment (Thoralf-M) [reply sdk/tests/client/input_selection/foundry_outputs.rs:761]: Not with the same token id `The presence and validation of the foundry outputs of the native tokens determines whether the tokens are burned (removed from the ledger) or melted in the foundry.` https://github.com/iotaledger/tips/blob/main/tips/TIP-0018/tip-0018.md#additional-semantic-transaction-validation-rules

**Review by thibault-martinez — DISMISSED** [review]

File: sdk/src/client/api/block_builder/input_selection/core/mod.rs [hunk 25]
```diff
@@ -403,10 +406,147 @@ impl InputSelection {
...
+            }
+        }
+
+        let input_native_tokens = hashbrown::HashMap::from_iter(
+            input_native_tokens_builder
+                .finish_vec()?
+                .into_iter()
+                .map(|n| (*n.token_id(), n.amount())),
+        );
```
Comment (thibault-martinez) [inline sdk/src/client/api/block_builder/input_selection/core/mod.rs]: I wonder if we can change APIs a bit so we don't have to do that

Comment (Thoralf-M) [reply sdk/src/client/api/block_builder/input_selection/core/mod.rs]: NativeTokensBuilder internally uses `BTreeMap` and for validation we have `hashbrown::HashMap`, what was the reason to use the hashbrown one?

Comment (Thoralf-M) [reply sdk/src/client/api/block_builder/input_selection/core/mod.rs]: Ah it was there to make it no_std, changed something

File: sdk/src/types/block/semantic.rs [hunk 26]
```diff
@@ -120,13 +121,13 @@ pub struct ValidationContext<'a> {
...
     ///
-    pub input_native_tokens: HashMap<TokenId, U256>,
+    pub input_native_tokens: BTreeMap<TokenId, U256>,
     ///
     pub input_chains: HashMap<ChainId, &'a Output>,
     ///
     pub output_amount: u64,
     ///
-    pub output_native_tokens: HashMap<TokenId, U256>,
+    pub output_native_tokens: BTreeMap<TokenId, U256>,
```
Comment (thibault-martinez) [inline sdk/src/types/block/semantic.rs:130]: This is all public so it needs a changelog entry.

Comment (thibault-martinez) [reply sdk/src/types/block/semantic.rs:130]: Maybe we don't even need `ValidationContext` to be public at all...

**Review by thibault-martinez — APPROVED** [review]

**Review by thibault-martinez — CHANGES_REQUESTED** [review]
Conflicts

**Review by thibault-martinez — DISMISSED** [review]

File: sdk/src/client/api/block_builder/input_selection/core/mod.rs [hunk 27]
```diff
@@ -403,10 +406,134 @@ impl InputSelection {
...
         })
     }
+
+    fn validate_transitions(&self) -> Result<(), Error> {
+        let mut input_native_tokens_builder = NativeTokensBuilder::new();
+        let mut output_native_tokens_builder = NativeTokensBuilder::new();
+        let mut input_aliases = Vec::new();
+        let mut input_chains_foundries = hashbrown::HashMap::new();
+        let mut input_foundries = Vec::new();
+        let mut input_nfts = Vec::new();
```
Comment (Alex6323) [inline sdk/src/client/api/block_builder/input_selection/core/mod.rs:425]: consider using `with_capacity` so it doesn't have to reallocate?

Comment (thibault-martinez) [reply sdk/src/client/api/block_builder/input_selection/core/mod.rs:425]: We don't know the number in advance

File: sdk/src/client/api/block_builder/input_selection/core/transition.rs [hunk 28]
```diff
@@ -44,11 +44,21 @@ impl InputSelection {
...
+                }
+            }
+        }
+
         // Remove potential sender feature because it will not be needed anymore as it only needs to be verified once.
         let features = input.features().iter().cloned().filter(|feature| !feature.is_sender());
 
         let mut builder = AliasOutputBuilder::from(input)
             .with_alias_id(alias_id)
+            .with_foundry_counter(u32::max(highest_foundry_serial_number, input.foundry_counter()))
```
Comment (Alex6323) [inline sdk/src/client/api/block_builder/input_selection/core/transition.rs:61]:
```suggestion
            .with_foundry_counter(highest_foundry_serial_number.max(input.foundry_counter()))
```

Comment (thibault-martinez) [reply sdk/src/client/api/block_builder/input_selection/core/transition.rs:61]: I personally find this version to be less intuitive 🤷🏻

File: sdk/src/types/block/error.rs [hunk 29]
```diff
@@ -92,6 +92,7 @@ pub enum Error {
     InvalidUnlockNft(u16),
     InvalidUnlockConditionCount(<UnlockConditionCount as TryFrom<usize>>::Error),
     InvalidUnlockConditionKind(u8),
+    InvalidZeroSerialNumber,
```
Comment (Alex6323) [inline sdk/src/types/block/error.rs]: `InvalidFoundryZeroSerialNumber` maybe (considering we also have `InconsistentFoundrySerialNumber`)?

File: sdk/src/types/block/error.rs [hunk 30]
```diff
@@ -256,6 +257,7 @@ impl fmt::Display for Error {
             }
             Self::InvalidUnlockConditionCount(count) => write!(f, "invalid unlock condition count: {count}"),
             Self::InvalidUnlockConditionKind(k) => write!(f, "invalid unlock condition kind: {k}"),
+            Self::InvalidZeroSerialNumber => write!(f, "invalid zero serial number"),
```
Comment (Alex6323) [inline sdk/src/types/block/error.rs]:
```suggestion
            Self::InvalidZeroSerialNumber => write!(f, "invalid foundry zero serial number"),
```

File: sdk/src/types/block/output/native_token.rs [hunk 31]
```diff
@@ -71,7 +71,7 @@ fn verify_amount<const VERIFY: bool>(amount: &U256, _: &()) -> Result<(), Error>
 /// A builder for [`NativeTokens`].
 #[derive(Clone, Default, Debug, Deref, DerefMut, From)]
 #[must_use]
-pub struct NativeTokensBuilder(BTreeMap<TokenId, U256>);
+pub struct NativeTokensBuilder(pub(crate) BTreeMap<TokenId, U256>);
```
Comment (Alex6323) [inline sdk/src/types/block/output/native_token.rs]: why do we need the `pub(crate)`. For creation you can just use `.into()` and for iteration `.deref()`, and changing should probably only done through the builder?

File: sdk/src/client/api/block_builder/input_selection/core/transition.rs (hunk 28 above)
Comment (Alex6323) [reply sdk/src/client/api/block_builder/input_selection/core/transition.rs:61]: I kinda agree. It won't require a change though should the type ever change. Your choice @Thoralf-M :smile:

File: sdk/src/client/api/block_builder/input_selection/core/mod.rs (hunk 27 above)
Comment (Alex6323) [reply sdk/src/client/api/block_builder/input_selection/core/mod.rs:425]: But I think we know the upper limit, right? We may allocate too much then, but it could be potentially a bit faster since no re-allocations and copying has to take place.

File: sdk/src/types/block/output/native_token.rs (hunk 31 above)
Comment (Thoralf-M) [reply sdk/src/types/block/output/native_token.rs:74]: Deref is not implemented?

Comment (Thoralf-M) [reply sdk/src/types/block/output/native_token.rs]: Have overlooked the Deref :+1:

File: sdk/src/client/api/block_builder/input_selection/core/transition.rs (hunk 28 above)
Comment (Thoralf-M) [reply sdk/src/client/api/block_builder/input_selection/core/transition.rs:61]: The `u32::max()` looks clearer to me here, so I would leave it

File: sdk/src/client/api/block_builder/input_selection/core/mod.rs (hunk 27 above)
Comment (Thoralf-M) [reply sdk/src/client/api/block_builder/input_selection/core/mod.rs:425]: Upper limit is 128, but can often also stay completely empty

**Review by thibault-martinez — APPROVED** [review]

**Review by Alex6323 — APPROVED** [review]
