### PR TITLE
fix(wallet): arithmetic overflow in native token balance computation

### LINKED ISSUE #264: [Bug]: Calling `balance` in an account produces an arithmetic overflow
### Issue description

In certain situations an `arithmetic overflow` panic is triggered.

### Version

rc-2

### Expected behaviour

This panic should not occur.

### Actual behaviour

It does tho.

### Can the issue reliably be reproduced?

No

### Steps to reproduce the issue
It doesn't work always but this is how it was triggered a few times:

1. mint a new token using the `mint_native_token` example
2. use the `send_native_token` example to send it somewhere (I changed the address to another address that only I own)
3. after the command has finished, immediatedly log into the wallet and call `balance`.

### Errors

```
Stronghold password: [hidden]
Account "Alice": balance
thread 'main' panicked at 'arithmetic operation overflow', /home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/primitive-types-0.12.1/src/lib.rs:38:1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fish: Job 1, './wallet' terminated by signal SIGABRT (Abort)
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### PR DESCRIPTION
**Pull request by Alex6323**
# Description of change

Skips potentially locked outputs for the native token balance computation.

## Links to any relevant issues

Fixes #264 

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Bug fix (a non-breaking change which fixes an issue)

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Thoralf-M — DISMISSED** [review]

File: sdk/src/wallet/account/operations/balance.rs [hunk 1]
```diff
@@ -225,6 +225,9 @@ impl Account {
         let mut locked_native_tokens = NativeTokensBuilder::new();
 
         for locked_output in &account_details.locked_outputs {
+            if account_balance.potentially_locked_outputs.contains_key(locked_output) {
```
Comment (Thoralf-M) [inline sdk/src/wallet/account/operations/balance.rs:229]:
```suggestion
            // Skip potentially_locked_outputs, as their amounts aren't added to the balance
            if account_balance.potentially_locked_outputs.contains_key(locked_output) {
```

**Review by Thoralf-M — APPROVED** [review]

**Review by DaughterOfMars — APPROVED** [review]

**Review by thibault-martinez — APPROVED** [review]
