### PR TITLE
Map errors to wallet error variant

### LINKED ISSUE #480: Consistent error is thrown when account cannot cover storage deposit
## Description

When Firefly tries to claim transactions that cannot be claimed due to no outputs available for covering the storage deposit, different type of errors are thrown per output. As an example.

If I have two incoming NFT Outputs that need claiming, but I only have one output with SMR, then I get the following error if I try to claim the transaction:

`{type: 'insufficientFunds', error: 'insufficient funds 0/70500 available'}`

If I have two incoming Basic Outputs with SD requirements in the same scenario, the following error is thrown:

`{type: 'block', error: 'insufficient output amount for storage deposit: 1 (should be at least 42600)'}`

If I want to attach extra storage deposit that I don't have due to pending transaction, the following error is thrown:

`{type: 'client', error: 'insufficient amount: found 125000, required 133000'}`

## Motivation

Consistent Error Handling, if  a transaction cannot be confirmed for the same reason

## Requirements

Write a list of what you want this feature to do.

1. Consistently throw one error: our preferred one is `{type: 'insufficientFunds', error: 'insufficient funds 0/70500 available'}`
2. Check whether there are other places where a similar error should be thrown that we missed

## Are you planning to do it yourself in a pull request?

No.

### PR DESCRIPTION
**Pull request by Thoralf-M**
# Description of change

Map errors to wallet error variant 

## Links to any relevant issues

Fixes https://github.com/iotaledger/iota-sdk/issues/480

## Type of change

- Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How the change has been tested

Added test

## Change checklist

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

File: sdk/src/wallet/account/operations/output_claiming.rs [hunk 1]
```diff
@@ -162,7 +162,24 @@ impl Account {
...
         log::debug!("[OUTPUT_CLAIMING] claim_outputs");
         let basic_outputs = self.get_basic_outputs_for_additional_inputs().await?;
-        self.claim_outputs_internal(output_ids_to_claim, basic_outputs).await
+        self.claim_outputs_internal(output_ids_to_claim, basic_outputs)
+            .await
+            .map_err(|error| {
+                // Map InsufficientStorageDepositAmount error here because it's the result of InsufficientFunds in this
+                // case and then easier to handle
+                match error {
+                    crate::wallet::Error::Block(block_error) => match *block_error {
```
Comment (DaughterOfMars) [inline sdk/src/wallet/account/operations/output_claiming.rs:171]: Maybe it would be better to have a manual `From` impl for the error types? Unless this should only ever happen here of course

Comment (Thoralf-M) [reply sdk/src/wallet/account/operations/output_claiming.rs:171]: Initially I did in on the error type, but I think it's better to have it only here. In other places we want to keep the information that it's about the storage deposit since there it's not about the available funds, but in the claiming this is the case

**Review by DaughterOfMars — APPROVED** [review]

**Review by thibault-martinez — APPROVED** [review]
