### PR TITLE
Fixed cli restore in existing wallet folder

### LINKED ISSUE #1068: [Bug]: (CLI) `restore` command asks for the cached stronghold instead of specified
### Issue description

I was trying to restore a wallet from a stronghold file and every time it asked my password and I wrote it told me the password was wrong...
Turns out, there was already a wallet in the same folder I was executing wallet restore ... so, I wasn't really writing the password for the stronghold I was trying to restore but for the wallet that was already in the folder. I found this behavior a bit confusing, so maybe it could be changed and instead prioritize the stronghold file that is being passed to the restore command and make it overwrite the wallet that is already in the folder, or, simply show a warning with something like "There seems to be a wallet in this folder already. First remove it to restore a new wallet."

### Version

https://github.com/iotaledger/iota-sdk/tree/ec1f64c98b71a13afe87c048d85f157d639909dd/cli

### Expected behaviour

Prioritize the stronghold file that is being passed to the restore command and make it overwrite the wallet that is already in the folder, or, simply show a warning with something like "There seems to be a wallet in this folder already. First remove it to restore a new wallet."

### Actual behaviour

It's prioritizing the cached stronghold

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. `mkdir tmp && cd tmp`
2. Create/restore a wallet (`Wallet A`)
3. Restore another wallet (`Wallet B`)

### Errors

_No response_

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### PR DESCRIPTION
**Pull request by kwek20**
# Description of change

Checks before restoring a stronghold file if there is an existing stronghold.
The check for restoring when accounts exist was already in place, with error: "can't restore backup when there are already accounts"
Also adds a check for `snapshot_path` being a file, not folder (it crashes oddly if you send a folder path)

## Links to any relevant issues

Closes https://github.com/iotaledger/iota-sdk/issues/1068

## Type of change

- Bug fix (a non-breaking change which fixes an issue)

## How the change has been tested

Ran the following scenarios:
- Import an export in empty folder
- Import an export in a folder with wallet, but no account
- Import an export in a folder with wallet with accounts
- Import from the same folder as export (this errors saying already has an account, or succeeds if there wasnt any)

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

File: cli/src/command/wallet.rs [hunk 1]
```diff
@@ -238,14 +238,22 @@ pub async fn node_info_command(storage_path: &Path) -> Result<Wallet, Error> {
...
-        StrongholdSecretManager::builder()
-            .password(password.clone())
-            .build(snapshot_path)?,
-    );
-    let wallet = Wallet::builder()
-        .with_secret_manager(secret_manager)
+    let mut builder = Wallet::builder();
+    if check_file_exists(snapshot_path).await.is_ok() {
+        println_log_info!(
+            "Detected a stronghold file at {}, requiring unlock..",
```
Comment (DaughterOfMars) [inline cli/src/command/wallet.rs]: The messages here are a little weird. Maybe go with
```
Detected a stronghold file at {}. Enter password to unlock:
```

and not sure about "Detected Stronghold password" below

Comment (kwek20) [reply cli/src/command/wallet.rs]: The"Detected Stronghold password" is for the prompt to unlock the current stronghold (named detected)
Afterwards, you get a prompt as well to unlock the stronghold you import ("imported stronghold)
The detected and imported name is important to not cause confusions when both prompts trigger

File: sdk/src/client/stronghold/error.rs [hunk 2]
```diff
@@ -51,6 +51,9 @@ pub enum Error {
     /// Path already exists
     #[error("path already exists: {0}")]
     PathAlreadyExists(std::path::PathBuf),
+    /// Path is not a file
+    #[error("path is not a file: {0}")]
+    PathIsNotFile(std::path::PathBuf),
```
Comment (thibault-martinez) [inline sdk/src/client/stronghold/error.rs]: Can't do that, breaking change

Comment (kwek20) [reply sdk/src/client/stronghold/error.rs]: i argue its not. the code wouldt allow it anyway, because the filesystem would lock and crash. This just gives a better error message. And there is absolutely NO way someone has a match case for all errors :)

Comment (thibault-martinez) [reply sdk/src/client/stronghold/error.rs]: We had such a case 2 weeks ago and we put TODOs to change later in 2.0 and found another way. This is breaking change whether people use it that way or not.

File: cli/src/command/wallet.rs (hunk 1 above)
Comment (DaughterOfMars) [reply cli/src/command/wallet.rs]: Sure, but the phrase is confusing. It reads like a statement rather than a prompt

File: sdk/src/client/stronghold/error.rs (hunk 2 above)
Comment (kwek20) [reply sdk/src/client/stronghold/error.rs]: So what error should i throw? IO?
Edit: Wont work, ill comment and add TODO + issue

File: cli/src/command/wallet.rs (hunk 1 above)
Comment (kwek20) [reply cli/src/command/wallet.rs]: Updated

File: sdk/src/client/stronghold/mod.rs [hunk 3]
```diff
@@ -182,6 +182,12 @@ impl StrongholdAdapterBuilder {
     /// [`password()`]: Self::password()
     /// [`timeout()`]: Self::timeout()
     pub fn build<P: AsRef<Path>>(self, snapshot_path: P) -> Result<StrongholdAdapter, Error> {
+        if snapshot_path.as_ref().is_dir() {
+            // TODO: Add Error in 2.0 as its breaking. Will crash further down now.
```
Comment (DaughterOfMars) [inline sdk/src/client/stronghold/mod.rs]: just panic?

Comment (kwek20) [reply sdk/src/client/stronghold/mod.rs]: fair

**Review by Thoralf-M — DISMISSED** [review]

**Review by DaughterOfMars — DISMISSED** [review]

**Review by thibault-martinez — CHANGES_REQUESTED** [review]
Changelog

File: cli/src/command/wallet.rs [hunk 4]
```diff
@@ -238,14 +238,22 @@ pub async fn node_info_command(storage_path: &Path) -> Result<Wallet, Error> {
...
-            .build(snapshot_path)?,
-    );
-    let wallet = Wallet::builder()
-        .with_secret_manager(secret_manager)
+    let mut builder = Wallet::builder();
+    if check_file_exists(snapshot_path).await.is_ok() {
+        println_log_info!(
+            "Detected a stronghold file at {}. Enter password to unlock:",
+            snapshot_path.to_str().unwrap()
+        );
```
Comment (Alex6323) [inline cli/src/command/wallet.rs]: Is that "Enter password to unlock:" necessary? Also a bit weird to have that in the log, no?

File: sdk/src/client/stronghold/mod.rs [hunk 5]
```diff
@@ -484,6 +490,14 @@ impl StrongholdAdapter {
     ///
     /// [`unload_stronghold_snapshot()`]: Self::unload_stronghold_snapshot()
     pub async fn write_stronghold_snapshot(&self, snapshot_path: Option<&Path>) -> Result<(), Error> {
+        if let Some(p) = snapshot_path {
+            if p.is_dir() {
```
Comment (Alex6323) [inline sdk/src/client/stronghold/mod.rs:498]: `if matches!(snapshot_path, Some(p) if p.is_dir()) { ... }` (if you like)

Comment (kwek20) [reply sdk/src/client/stronghold/mod.rs:498]: i like!

File: cli/src/command/wallet.rs (hunk 4 above)
Comment (kwek20) [reply cli/src/command/wallet.rs]: yea its kind of needed, otherwise theres the chance you have to unlock 2 strongholds, and its not clear which one is which.

Comment (kwek20) [reply cli/src/command/wallet.rs]: I do agree its weird in the logs :/

**Review by DaughterOfMars — DISMISSED** [review]

**Review by Thoralf-M — DISMISSED** [review]

File: cli/src/command/wallet.rs (hunk 4 above)
Comment (thibault-martinez) [reply cli/src/command/wallet.rs]: Then don't log it ?

Comment (kwek20) [reply cli/src/command/wallet.rs]: you know.. i forgot that was an option :D

**Review by Thoralf-M — DISMISSED** [review]

**Review by abdulmth — DISMISSED** [review]

File: sdk/src/client/stronghold/mod.rs [hunk 6]
```diff
@@ -182,6 +182,12 @@ impl StrongholdAdapterBuilder {
     /// [`password()`]: Self::password()
     /// [`timeout()`]: Self::timeout()
     pub fn build<P: AsRef<Path>>(self, snapshot_path: P) -> Result<StrongholdAdapter, Error> {
+        if snapshot_path.as_ref().is_dir() {
+            // TODO: Add Error in 2.0 as its breaking.
+            // Issue #1197
+            panic!("Path is not a file: {:?}", snapshot_path.as_ref().to_path_buf());
```
Comment (thibault-martinez) [inline sdk/src/client/stronghold/mod.rs]: Let's return an IO error instead

Comment (kwek20) [reply sdk/src/client/stronghold/mod.rs]: i dont have an std::io error. in https://github.com/iotaledger/iota-sdk/pull/1187/commits/482fe51b9063e5672527bc8aa8d255625b637fd6 i introduced an error type but that was breaking

Comment (thibault-martinez) [reply sdk/src/client/stronghold/mod.rs]: Not sure what you mean, just return `std::io::Error`? I just tested it it's fine.

Comment (kwek20) [reply sdk/src/client/stronghold/mod.rs]: how? :D

`return Err(Error::Io(std::io::Error(format!("Path is not a file: {:?}", snapshot_path.unwrap()))));` doesnt work obviously

File: sdk/src/client/stronghold/mod.rs [hunk 7]
```diff
@@ -484,6 +494,16 @@ impl StrongholdAdapter {
     ///
     /// [`unload_stronghold_snapshot()`]: Self::unload_stronghold_snapshot()
     pub async fn write_stronghold_snapshot(&self, snapshot_path: Option<&Path>) -> Result<(), Error> {
+        if matches!(snapshot_path, Some(p) if p.is_dir()) {
+            // TODO: Add Error in 2.0 as its breaking.
+            // Issue #1197
+            return Err(std::io::Error::new(
+                std::io::ErrorKind::Other,
+                format!("Path is not a file: {:?}", snapshot_path.unwrap()),
```
Comment (thibault-martinez) [inline sdk/src/client/stronghold/mod.rs]: Do a proper match instead of `matches`

Comment (thibault-martinez) [reply sdk/src/client/stronghold/mod.rs]: Or put a comment for that unwrap, but unwrapping when we could match feels a bit dumb 🤷🏻‍♂️

Comment (kwek20) [reply sdk/src/client/stronghold/mod.rs]: you even resolved the conversation where we changed it: https://github.com/iotaledger/iota-sdk/pull/1187#discussion_r1331513450

Comment (kwek20) [reply sdk/src/client/stronghold/mod.rs]: so want me to revert to how it was before with 2 checks instead?

Comment (thibault-martinez) [reply sdk/src/client/stronghold/mod.rs]: Sorry my bad, I didn't see from the preview that there was an unwrap. Yes I would revert, I think it's worse than before.

Comment (thibault-martinez) [reply sdk/src/client/stronghold/mod.rs]: Or as I said, add a comment but it feels wrong to unwrap when there is a logic way to avoid it

Comment (kwek20) [reply sdk/src/client/stronghold/mod.rs]: reverted

**Review by Thoralf-M — DISMISSED** [review]

**Review by abdulmth — DISMISSED** [review]

File: cli/src/command/wallet.rs [hunk 8]
```diff
@@ -247,14 +247,22 @@ pub async fn node_info_command(storage_path: &Path) -> Result<Wallet, Error> {
...
+        let password = get_password("Stronghold password", false)?;
+        let secret_manager = SecretManager::Stronghold(
+            StrongholdSecretManager::builder()
+                .password(password.clone())
+                .build(snapshot_path)?,
+        );
+        builder = builder.with_secret_manager(secret_manager);
+    }
+
+    let wallet: Wallet = builder
```
Comment (thibault-martinez) [inline cli/src/command/wallet.rs]:
```suggestion
    let wallet = builder
```

**Review by thibault-martinez — APPROVED** [review]

File: cli/src/command/wallet.rs (hunk 8 above)
Comment (kwek20) [reply cli/src/command/wallet.rs]: uhg these things keep happening when i ctrl click on the type hint in vs code :/

**Review by abdulmth — APPROVED** [review]
