### PR TITLE
Remove generate_ed25519_addresses from Client, fix it in Python

### LINKED ISSUE #492: Remove generate address method from client and wallet
## Description

Remove generate address method from client? Method on the SecretManager should be enough, the only thing we lose is getting the bech32 hrp from the network by default, but that's easy to get and provide

## Motivation

Better to maintain, less confusion because of different options

### PR DESCRIPTION
**Pull request by Thoralf-M**
# Description of change

Remove generate_ed25519_addresses from Client, fix it in Python SecretManager

## Links to any relevant issues

Fixes #492 

## Type of change

- Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How the change has been tested

Running the examples and tests

## Change checklist

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

File: bindings/core/tests/combined.rs [hunk 1]
```diff
@@ -4,47 +4,11 @@
...
 
 use iota_sdk::{
-    client::{api::GetAddressesOptions, constants::SHIMMER_COIN_TYPE, secret::SecretManagerDto, ClientBuilder},
+    client::{constants::SHIMMER_COIN_TYPE, ClientBuilder},
     wallet::account::types::AccountIdentifier,
 };
 use iota_sdk_bindings_core::{AccountMethod, CallMethod, ClientMethod, Response, Result, WalletMethod, WalletOptions};
 
-#[tokio::test]
-async fn generate_ed25519_addresses() -> Result<()> {
```
Comment (thibault-martinez) [inline bindings/core/tests/combined.rs:13]: Should this test be replaced by secret manager?

Comment (Thoralf-M) [reply bindings/core/tests/combined.rs:13]: We already have one for the secret manager https://github.com/iotaledger/iota-sdk/blob/cb5a52ad82944e36e0209f85407906fe3cba66d9/bindings/core/tests/secrets_manager.rs#L11

Comment (thibault-martinez) [reply bindings/core/tests/combined.rs:13]: Assumed so, thanks

**Review by thibault-martinez — DISMISSED** [review]

**Review by thibault-martinez — APPROVED** [review]

**Review by DaughterOfMars — APPROVED** [review]

**Review by kwek20 — APPROVED** [review]
