### PR TITLE
Fix/utils parse bech32

### LINKED ISSUE #748: [Bug]: `Utils.parseBech32Address` fails on valid address
### Issue description

The function `Utils.parseBech32Address` in sdk-wasm fails on a valid address with a JSON conversion error.

### Version

`@iota/sdk-wasm` at version `1.0.0-rc.0`

### Expected behaviour

Successfully returns the address.

### Actual behaviour

Fails with this error:

```
SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at Function.parseBech32Address (/home/philipp/git/identity.rs/bindings/wasm/node_modules/@iota/sdk-wasm/out/lib/utils/utils.ts:174:16)
  ...
```

(Note that the line number in utils.ts might be off by a bit as I started to add some print statement for debugging).

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. Call `const addr = Utils.parseBech32Address("tst1qp8vegfcnf4vjcn0zj6a5wv4x0x6pmrw543a02gr50cqmrdtjf9cycygj6l")`

### Errors

_No response_

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### PR DESCRIPTION
**Pull request by kwek20**
# Description of change

parseBech32Address wasnt properly parsing the message_interface response. Now it does

## Links to any relevant issues

fixes #748

### CODE REVIEW

File: bindings/nodejs/lib/utils/utils.ts
Comment (thibault-martinez) [inline bindings/nodejs/lib/utils/utils.ts:1]: Some warnings in the file

Comment (kwek20) [reply bindings/nodejs/lib/utils/utils.ts:1]: hmm why didnt that show up in the comments here.. annoying

File: bindings/nodejs/examples/how_tos/accounts_and_addresses/create-address.ts [hunk 1]
```diff
@@ -26,9 +26,10 @@ async function run() {
         // To create an address we need to unlock stronghold.
         await wallet.setStrongholdPassword(process.env.STRONGHOLD_PASSWORD);
 
-        const address = (await account.generateEd25519Addresses(1))[0];
+        const accountAddress = (await account.generateEd25519Addresses(1))[0];
+        const address = Utils.parseBech32Address(accountAddress.address);
 
-        console.log(`Generated address:`, address.address);
+        console.log(`Generated address:`, address);
```
Comment (Thoralf-M) [inline bindings/nodejs/examples/how_tos/accounts_and_addresses/create-address.ts]: Shouldn't we show the bech32 address here?

Comment (kwek20) [reply bindings/nodejs/examples/how_tos/accounts_and_addresses/create-address.ts]: this will print:
```
Generated address: Ed25519Address {
  type: 0,
  pubKeyHash: '0x2435ee1fdc75f8fc8d3bcfa7140d334bbe378a1280423bff584989a92b341bbe'
}
```

Do you wnat it toprint the whole `AccountAddress`?

Comment (Thoralf-M) [reply bindings/nodejs/examples/how_tos/accounts_and_addresses/create-address.ts]: No no, just address.address as it was before?

Comment (Thoralf-M) [reply bindings/nodejs/examples/how_tos/accounts_and_addresses/create-address.ts]: In the python example also only print the bech32 address and most people don't care that much about the ed25519 representation

Comment (Thoralf-M) [reply bindings/nodejs/examples/how_tos/accounts_and_addresses/create-address.ts]: The toString() only prints the bech32 address or the full account address now?

Comment (kwek20) [reply bindings/nodejs/examples/how_tos/accounts_and_addresses/create-address.ts]: the address, see here: https://github.com/iotaledger/iota-sdk/blob/develop/bindings/nodejs/lib/types/block/address.ts#L46C15-L46C15

Comment (Thoralf-M) [reply bindings/nodejs/examples/how_tos/accounts_and_addresses/create-address.ts]: But this is for `Address` and the function returns `AccountAddress`?

**Review by Thoralf-M — APPROVED** [review]

**Review by thibault-martinez — APPROVED** [review]
