### PR TITLE
Flatten and fix ClientOptions in bindings

### LINKED ISSUE #1982: Bindings ClientOptions mismatch
In Rust we flattened the fields of the client options https://github.com/iotaledger/iota-sdk/blob/0683d80776ff909b578bff1bda257ed61ebbd741/sdk/src/client/builder.rs#L36-L39, but in the binding types not (only NodeManagerBuilder)
https://github.com/iotaledger/iota-sdk/blob/0683d80776ff909b578bff1bda257ed61ebbd741/bindings/nodejs/lib/types/client/client-options.ts#L28-L30
https://github.com/iotaledger/iota-sdk/blob/0683d80776ff909b578bff1bda257ed61ebbd741/bindings/python/iota_sdk/types/client_options.py#L102-L103

### PR DESCRIPTION
**Pull request by Thoralf-M**
# Description of change

Flatten and fix ClientOptions in bindings

## Links to any relevant issues

Fixes #1982 

## Type of change

- Bug fix (a non-breaking change which fixes an issue)

## How the change has been tested

```TS
import { Client } from '@iota/sdk';
import { assert } from 'console';

async function run() {
    const protocolParameters = {
        type: 0,
        version: 3,
        networkName: 'moon',
        bech32Hrp: 'moon',
        storageScoreParameters: {
            storageCost: '100',
            factorData: 1,
            offsetOutputOverhead: '10',
            offsetEd25519BlockIssuerKey: '100',
            offsetStakingFeature: '100',
            offsetDelegation: '100',
        },
        workScoreParameters: {
            dataByte: 500,
            block: 110000,
            input: 7500,
            contextInput: 40000,
            output: 90000,
            nativeToken: 50000,
            staking: 40000,
            blockIssuer: 70000,
            allotment: 5000,
            signatureEd25519: 15000,
        },
        manaParameters: {
            bitsCount: 63,
            generationRate: 1,
            generationRateExponent: 17,
            decayFactors: [
                4290989755, 4287015898, 4283045721, 4279079221, 4275116394,
            ],
            decayFactorsExponent: 32,
            decayFactorEpochsSum: 2262417561,
            decayFactorEpochsSumExponent: 21,
            annualDecayFactorPercentage: 70,
        },
        tokenSupply: '1813620509061365',
        genesisSlot: 5,
        genesisUnixTimestamp: '1708333647',
        slotDurationInSeconds: 10,
        slotsPerEpochExponent: 13,
        stakingUnbondingPeriod: 10,
        validationBlocksPerSlot: 10,
        punishmentEpochs: 10,
        livenessThresholdLowerBound: 10,
        livenessThresholdUpperBound: 15,
        minCommittableAge: 3,
        maxCommittableAge: 6,
        epochNearingThreshold: 8,
        congestionControlParameters: {
            minReferenceManaCost: '1',
            increase: '1',
            decrease: '1',
            increaseThreshold: 400000000,
            decreaseThreshold: 250000000,
            schedulerRate: 50000000,
            maxBufferSize: 1000,
            maxValidationBufferSize: 100,
        },
        versionSignalingParameters: {
            windowSize: 7,
            windowTargetRatio: 5,
            activationOffset: 7,
        },
        rewardsParameters: {
            profitMarginExponent: 8,
            bootstrappingDuration: 1079,
            rewardToGenerationRatio: 2,
            initialTargetRewardsRate: '616067521149261',
            finalTargetRewardsRate: '226702563632670',
            poolCoefficientExponent: 11,
            retentionPeriod: 384,
        },
        targetCommitteeSize: 32,
        chainSwitchingThreshold: 3,
    };
    const client = await Client.create({
        protocolParameters,
    });

    try {
        assert(
            JSON.stringify(protocolParameters) ==
                JSON.stringify(
                    (await client.getNetworkInfo()).protocolParameters,
                ),
        );
    } catch (error) {
        console.error('Error: ', error);
    }
}

void run().then(() => process.exit());
```

### CODE REVIEW

File: bindings/nodejs/lib/types/client/client-options.ts
Comment (Alex6323) [inline bindings/nodejs/lib/types/client/client-options.ts:1]: I know I have been forgetting this as well, but can you update the file header?

Comment (DaughterOfMars) [reply bindings/nodejs/lib/types/client/client-options.ts:1]: we should just do a find-and-replace all PR lol

File: bindings/nodejs/lib/types/client/network.ts [hunk 1]
```diff
@@ -59,4 +43,6 @@ export interface INode {
 export interface INetworkInfo {
     /** Protocol parameters */
     protocolParameters: ProtocolParameters;
+    /** The current tangle time */
+    tangleTime: number;
```
Comment (DaughterOfMars) [inline bindings/nodejs/lib/types/client/network.ts]: this isn't serialized in rust so I dunno if it needs to be here

Comment (Thoralf-M) [reply bindings/nodejs/lib/types/client/network.ts]: Ah missed that, not needed then

File: bindings/nodejs/lib/types/client/client-options.ts [hunk 2]
```diff
@@ -20,10 +22,23 @@ export interface IClientOptions {
...
+    useWs?: boolean;
+    /** Sets the port used for the MQTT operations. */
+    port?: number;
+    /** Sets the maximum number of reconnection attempts. 0 is unlimited. */
+    maxReconnectionAttempts?: number;
+    // NetworkInfo
+    /** Protocol parameters */
+    protocolParameters?: ProtocolParameters;
+    /** The current tangle time */
+    tangleTime?: number;
```
Comment (DaughterOfMars) [inline bindings/nodejs/lib/types/client/client-options.ts]: Probably also not needed here

**Review by DaughterOfMars — DISMISSED** [review]

**Review by DaughterOfMars — APPROVED** [review]

File: bindings/nodejs/lib/types/models/storage-score.ts [hunk 3]
```diff
@@ -10,25 +10,25 @@ export interface StorageScoreParameters {
     /**
      *  Defines the number of IOTA tokens required per unit of storage score.
      */
-    storageCost: u64;
+    storageCost: NumericString;
```
Comment (thibault-martinez) [inline bindings/nodejs/lib/types/models/storage-score.ts:13]: Is there no way having u64 behave as NumericString? What was the point of introducing it if we're removing it more and more?

Comment (Thoralf-M) [reply bindings/nodejs/lib/types/models/storage-score.ts:13]: It only works in classes, since we there can convert it during construction of the type, but the interfaces are just type hints, so no conversion possible (unless we change them to classes)

Comment (thibault-martinez) [reply bindings/nodejs/lib/types/models/storage-score.ts:13]: I hate this

Comment (thibault-martinez) [reply bindings/nodejs/lib/types/models/storage-score.ts:13]: Why not keep u64 anyway if conversion doesn't work?

Comment (Thoralf-M) [reply bindings/nodejs/lib/types/models/storage-score.ts:13]: image

Comment (Thoralf-M) [reply bindings/nodejs/lib/types/models/storage-score.ts:13]: > Why not keep u64 anyway if conversion doesn't work?

Because the returned type from getInfo() for example is a string, so u64/bigint would be wrong

Comment (thibault-martinez) [reply bindings/nodejs/lib/types/models/storage-score.ts:13]: Ok

**Review by thibault-martinez — APPROVED** [review]
