### PR TITLE
Fix: foundry destroy example

### LINKED ISSUE #524: Add an example of destroying a foundry when account owns all tokens
## Description

If an account has a foundry, and the foundry owns all tokens it made, we should be able to destroy the foundry

## Motivation

UX

## Requirements

1. find tokens created
2. check if we control all
3. Melt tokens
4. Destroy foundry

## Open questions (optional)

This could be overkill, or maybe split it up in 2?
Do we want to add it to the bindings then though?

## Are you planning to do it yourself in a pull request?

Yes/No.

### PR DESCRIPTION
**Pull request by kwek20**
# Description of change

Updates destroy foundry example to melt tokens first if there are some left

## Links to any relevant issues

fixes #524

## Type of change

- Enhancement (a non-breaking change which adds functionality)

### CODE REVIEW

File: sdk/examples/how_tos/native_tokens/destroy_foundry.rs [hunk 1]
```diff
@@ -34,12 +38,58 @@ async fn main() -> Result<()> {
...
             .set_stronghold_password(std::env::var("STRONGHOLD_PASSWORD").unwrap())
             .await?;
 
-        let transaction = account.burn(*foundry_id, None).await?;
+        // Check if all tokens are melted.
+        let native_tokens: Vec<&NativeTokensBalance> = balance
+            .native_tokens()
+            .iter()
+            .filter(|native_token| *native_token.token_id() == token_id)
+            .collect();
```
Comment (Thoralf-M) [inline sdk/examples/how_tos/native_tokens/destroy_foundry.rs]: I think this should just use `.find()`, so `native_tokens` is `Option<NativeTokensBalance>`, because there can only be one `NativeTokensBalance` for one native token

Comment (Thoralf-M) [reply sdk/examples/how_tos/native_tokens/destroy_foundry.rs]: Or actually `if let Some(native_token_balance) = ` is probably even better, so you don't need this `if native_tokens.len() > 0 {` or `-is_some()` after changing

File: sdk/examples/how_tos/native_tokens/destroy_foundry.rs [hunk 2]
```diff
@@ -34,12 +38,58 @@ async fn main() -> Result<()> {
...
+            if total != output.as_foundry().token_scheme().as_simple().circulating_supply() {
+                // We are not able to melt all tokens, because we dont own them or they are not unlocked.
+                println!("We dont own all remaining tokens, aborting foundry destruction.");
+                return Ok(());
+            }
+
+            println!("Melting remaining tokens..");
+            for native_token_balance in native_tokens {
+                // Melt all tokens so we can destroy the foundry.
+                let tx = account
```
Comment (Thoralf-M) [inline sdk/examples/how_tos/native_tokens/destroy_foundry.rs]:
```suggestion
                let transaction = account
```

File: sdk/examples/how_tos/native_tokens/destroy_foundry.rs (hunk 1 above)
Comment (kwek20) [reply sdk/examples/how_tos/native_tokens/destroy_foundry.rs]: yea i thought it could have duplicate token ids, fixed

File: sdk/src/types/block/output/token_scheme/mod.rs [hunk 3]
```diff
@@ -31,6 +31,18 @@ impl TokenScheme {
             Self::Simple(_) => SimpleTokenScheme::KIND,
         }
     }
+
+    /// Checks whether the token scheme is a [`SimpleTokenScheme`].
+    pub fn is_simple(&self) -> bool {
```
Comment (thibault-martinez) [inline sdk/src/types/block/output/token_scheme/mod.rs:36]: Changelog entry for these 2

File: sdk/examples/how_tos/native_tokens/destroy_foundry.rs [hunk 4]
```diff
@@ -34,12 +38,50 @@ async fn main() -> Result<()> {
...
 
-        let transaction = account.burn(*foundry_id, None).await?;
+        // Check if all tokens are melted.
+        let native_tokens: Option<&NativeTokensBalance> = balance
+            .native_tokens()
+            .iter()
+            .find(|native_token| *native_token.token_id() == token_id);
+        if let Some(native_token) = native_tokens {
+            let output = account.get_foundry_output(token_id).await?;
+            if native_token.available() != output.as_foundry().token_scheme().as_simple().circulating_supply() {
```
Comment (DaughterOfMars) [inline sdk/examples/how_tos/native_tokens/destroy_foundry.rs:52]: Oof, is there really no cleaner way than this?

File: sdk/examples/how_tos/native_tokens/destroy_foundry.rs [hunk 5]
```diff
@@ -34,12 +38,50 @@ async fn main() -> Result<()> {
...
             .await?;
 
-        let transaction = account.burn(*foundry_id, None).await?;
+        // Check if all tokens are melted.
+        let native_tokens: Option<&NativeTokensBalance> = balance
+            .native_tokens()
+            .iter()
+            .find(|native_token| *native_token.token_id() == token_id);
+        if let Some(native_token) = native_tokens {
+            let output = account.get_foundry_output(token_id).await?;
```
Comment (DaughterOfMars) [inline sdk/examples/how_tos/native_tokens/destroy_foundry.rs]:
```suggestion
        // Find the native tokens balance for this foundry if one exists
        let native_tokens: Option<&NativeTokensBalance> = balance
            .native_tokens()
            .iter()
            .find(|native_token| *native_token.token_id() == token_id);
        if let Some(native_token) = native_tokens {
            // Check if all tokens are melted.
            let output = account.get_foundry_output(token_id).await?;
```

File: sdk/examples/how_tos/native_tokens/destroy_foundry.rs [hunk 6]
```diff
@@ -34,12 +38,50 @@ async fn main() -> Result<()> {
...
+            let block_id = account
+                .retry_transaction_until_included(&transaction.transaction_id, None, None)
+                .await?;
+            println!(
+                "Block included: {}/block/{}",
+                std::env::var("EXPLORER_URL").unwrap(),
+                block_id
+            );
+
+            // Update account so input selection works instead of throwing `UnfulfillableRequirement`.
```
Comment (DaughterOfMars) [inline sdk/examples/how_tos/native_tokens/destroy_foundry.rs]: Weird comment

Comment (Thoralf-M) [reply sdk/examples/how_tos/native_tokens/destroy_foundry.rs]: Yeah I guess it should be rather be something like `Sync to make the foundry output available again, because it was used in the melting transaction`

File: sdk/examples/how_tos/native_tokens/destroy_foundry.rs (hunk 4 above)
Comment (kwek20) [reply sdk/examples/how_tos/native_tokens/destroy_foundry.rs:52]: I dont think so no 😢

**Review by Thoralf-M — DISMISSED** [review]

File: sdk/examples/how_tos/native_tokens/destroy_foundry.rs (hunk 4 above)
Comment (DaughterOfMars) [reply sdk/examples/how_tos/native_tokens/destroy_foundry.rs:52]: bummer

File: sdk/examples/how_tos/native_tokens/destroy_foundry.rs [hunk 7]
```diff
@@ -34,12 +38,51 @@ async fn main() -> Result<()> {
...
-        let transaction = account.burn(*foundry_id, None).await?;
+        // Find the native tokens balance for this foundry if one exists.
+        let native_tokens: Option<&NativeTokensBalance> = balance
+            .native_tokens()
+            .iter()
+            .find(|native_token| *native_token.token_id() == token_id);
+        if let Some(native_token) = native_tokens {
+            let output = account.get_foundry_output(token_id).await?;
+            // Check if all tokens are melted.
+            if native_token.available() != output.as_foundry().token_scheme().as_simple().circulating_supply() {
```
Comment (thibault-martinez) [inline sdk/examples/how_tos/native_tokens/destroy_foundry.rs:56]: Is this a sufficient check? What about already melted tokens?

File: sdk/examples/how_tos/native_tokens/destroy_foundry.rs [hunk 8]
```diff
@@ -12,7 +12,11 @@
 //! cargo run --release --all-features --example destroy_foundry
 //! ```
 
-use iota_sdk::{wallet::Result, Wallet};
```
Comment (thibault-martinez) [inline sdk/examples/how_tos/native_tokens/destroy_foundry.rs:15]: Can't comment above but `This is only possible if its circulating supply is 0` in the doc seems wrong

**Review by Thoralf-M — DISMISSED** [review]

**Review by thibault-martinez — APPROVED** [review]

**Review by Thoralf-M — APPROVED** [review]
