### PR TITLE
Db migration: Properly handle possibly null protocol params

### LINKED ISSUE #1089: DB Migrating to version 1 fails
Db crated with commit 37edd0706ee003a0d17c7da19ba974b17b365cfe fails to migrate from version 0 to version 1 with error
`Json(Error("invalid type: null, expected struct StringPrefix", line: 0, column: 0))`

Trace log
```
2023-08-28 09:47:11 (UTC) iota_sdk::wallet::core::builder            DEBUG [WalletBuilder]
2023-08-28 09:47:11 (UTC) iota_sdk::wallet::migration                INFO  Migrating to version 0 - 0.4.0 - 2023-06-14
2023-08-28 09:47:11 (UTC) iota_sdk::client::storage                  TRACE StorageAdapter::get "[0]"
2023-08-28 09:47:11 (UTC) iota_sdk::client::storage                  TRACE StorageAdapter::get "{\"index\":0,\"coinType\":4219,\"alias\":\"Alice\",\"publicAddresses\":[{\"address\":\"rms1qpllaj0pyveqfkwxmnngz2c488hfdtmfrj3wfkgxtk4gtyrax0jaxzt70zy\",\"keyIndex\":0,\"internal\":false,\"used\":false}],\"internalAddresses\":[],\"addressesWithUnspentOutputs\":[],\"outputs\":{},\"lockedOutputs\":[],\"unspentOutputs\":{},\"transactions\":{},\"pendingTransactions\":[],\"incomingTransactions\":{}}"
2023-08-28 09:47:11 (UTC) iota_sdk::wallet::migration                INFO  Migrating to version 1 - 0.4.0 - 2023-07-13
2023-08-28 09:47:11 (UTC) iota_sdk::client::storage                  TRACE StorageAdapter::get "[0]"
2023-08-28 09:47:11 (UTC) iota_sdk::client::storage                  TRACE StorageAdapter::get "{\"addressesWithUnspentOutputs\":[],\"alias\":\"Alice\",\"coinType\":4219,\"incomingTransactions\":{},\"index\":0,\"internalAddresses\":[],\"lockedOutputs\":[],\"outputs\":{},\"pendingTransactions\":[],\"publicAddresses\":[{\"address\":\"rms1qpllaj0pyveqfkwxmnngz2c488hfdtmfrj3wfkgxtk4gtyrax0jaxzt70zy\",\"internal\":false,\"keyIndex\":0,\"used\":false}],\"transactions\":{},\"unspentOutputs\":{}}"
2023-08-28 09:47:11 (UTC) iota_sdk::client::storage                  TRACE StorageAdapter::get "{\"client_options\":{\"primaryNode\":null,\"primaryPowNode\":null,\"nodes\":[\"https://api.testnet.shimmer.network/\"],\"permanodes\":null,\"nodeSyncEnabled\":true,\"nodeSyncInterval\":{\"secs\":15,\"nanos\":0},\"quorum\":false,\"minQuorumSize\":3,\"quorumThreshold\":66,\"network\":null,\"networkId\":null,\"bech32Hrp\":null,\"minPowScore\":null,\"localPow\":true,\"fallbackToLocalPow\":true,\"tipsInterval\":5,\"rentStructure\":null,\"apiTimeout\":{\"secs\":15,\"nanos\":0},\"remotePowTimeout\":{\"secs\":100,\"nanos\":0},\"offline\":false,\"powWorkerCount\":null},\"coin_type\":4219,\"storage_options\":{\"storage_path\":\"./check_existing_5_db_test\",\"storage_file_name\":null,\"storage_encryption_key\":null,\"manager_store\":\"Rocksdb\"}}"
2023-08-28 09:47:11 (UTC) iota_sdk::wallet::storage                  DEBUG drop Storage
```

Added a test with such a db in https://github.com/iotaledger/iota-sdk/tree/check_existing_db_5, feel free to push a fix to this branch

Related Firefly issue https://github.com/iotaledger/firefly/issues/7358

### PR DESCRIPTION
**Pull request by Thoralf-M**
# Description of change

Db migration: Properly handle possibly null protocol params

## Links to any relevant issues

#1089 

## Type of change

- Bug fix (a non-breaking change which fixes an issue)

## How the change has been tested

Added test

## Change checklist

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

File: sdk/tests/wallet/wallet_storage.rs [hunk 1]
```diff
@@ -316,6 +316,42 @@ async fn check_existing_db_4() -> Result<()> {
...
+    setup(storage_path)?;
+    // Copy db so the original doesn't get modified
+    copy_folder("./tests/wallet/fixtures/check_existing_5_db_test", storage_path).unwrap();
+
+    let wallet = Wallet::builder().with_storage_path(storage_path).finish().await?;
+
+    // Commented because it wasn't created with encrypt_work_factor 0
+    // wallet.set_stronghold_password("STRONGHOLD_PASSWORD".to_owned()).await?;
+
+    // TODO: Supposed to be 2 or was that a mistake?
```
Comment (thibault-martinez) [inline sdk/tests/wallet/wallet_storage.rs]: ?

Comment (DaughterOfMars) [reply sdk/tests/wallet/wallet_storage.rs]: The test @Thoralf-M created has 2 here but the data seems to only have 1, but I wanted to be sure that was correct and it's not breaking something.

File: sdk/src/wallet/migration/migrate_3.rs [hunk 2]
```diff
@@ -83,6 +73,20 @@ impl Migration<crate::client::stronghold::StrongholdAdapter> for Migrate {
     }
 }
 
+fn migrate_client_options(client_options: &mut serde_json::Value) -> Result<()> {
+    if let Some(params) = client_options
+        .get_mut("protocolParameters")
+        .map(|p| p.as_object_mut().unwrap())
```
Comment (thibault-martinez) [inline sdk/src/wallet/migration/migrate_3.rs:79]: Does this have 0 chance to panic ever? Otherwise maybe use and_then instead of map

Comment (DaughterOfMars) [reply sdk/src/wallet/migration/migrate_3.rs:79]: If the params are there then they must be an object. We could handle the various cases with errors instead, but this is how it was before so I left it.

File: sdk/tests/wallet/wallet_storage.rs (hunk 1 above)
Comment (Thoralf-M) [inline sdk/tests/wallet/wallet_storage.rs]:
```suggestion
```

Comment (Thoralf-M) [reply sdk/tests/wallet/wallet_storage.rs]: Yes sorry, initially I created a db with two accounts, but then recreated it with one because I changed the paths

**Review by thibault-martinez — APPROVED** [review]

**Review by abdulmth — APPROVED** [review]
