### PR TITLE
Restructure the client A BIT to reduce `Arc` usage

### LINKED ISSUE #299: Improve `Client` reference counting
## Description

The `Client` struct should be broken up into `Client` and `ClientInner` using a single `Arc` rather than one for each field.

## Motivation

Fewer reference counters is good for performance.

### PR DESCRIPTION
**Pull request by DaughterOfMars**
# Description of change

The main changes are moving the core client stuff into a `ClientInner` and wrapping it in a single `Arc`, then I restructured the relevant fns to pass the `Client` around instead of the internals. The change which blew up the diffs is making the `ClientBuilder::finish` fn async. It makes sense to do this because it means that it is not creating a new runtime if we are calling the fn from within an existing one. Speaking of runtimes, I removed it from the `Client` as it should not longer be necessary.

## Links to any relevant issues

- #63 
- Closes #299

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

File: sdk/src/client/builder.rs [hunk 1]
```diff
@@ -327,69 +326,77 @@ impl ClientBuilder {
...
-                    self.node_manager_builder.ignore_node_health,
-                );
-                (runtime, sync_handle)
-            })
-            .join()
-            .expect("failed to init node syncing process");
-            (Some(Arc::new(runtime)), Some(sync_handle))
-        };
+    #[cfg(not(target_family = "wasm"))]
+    pub async fn finish(self) -> Result<Client> {
```
Comment (thibault-martinez) [inline sdk/src/client/builder.rs:330]: Changelog 🙏🏻

File: sdk/CHANGELOG.md [hunk 2]
```diff
@@ -36,6 +36,7 @@ and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0
 - rename `Client::try_get_outputs()` into `Client::get_outputs_ignore_errors()`;
 - rename `Client::try_get_outputs_metadata()` into `Client::get_outputs_metadata_ignore_errors()`;
 - MQTT connections to a node using https will now use wss/tls with native certificates;
+- `ClientBuilder::finish` is now async.
```
Comment (thibault-martinez) [inline sdk/CHANGELOG.md]:
```suggestion
- `ClientBuilder::finish` is now async;
```

**Review by thibault-martinez — APPROVED** [review]

File: sdk/src/client/client.rs [hunk 3]
```diff
@@ -32,74 +31,55 @@ use crate::{
 /// An instance of the client using HORNET or Bee URI
 #[derive(Clone)]
 pub struct Client {
-    #[allow(dead_code)]
+    pub(crate) inner: Arc<ClientInner>,
     #[cfg(not(target_family = "wasm"))]
-    pub(crate) runtime: Option<Arc<Runtime>>,
+    pub(crate) _sync_handle: Arc<SyncHandle>,
```
Comment (Thoralf-M) [inline sdk/src/client/client.rs:36]: Why did you put an underscore here?

**Review by Thoralf-M — APPROVED** [review]
