### PR TITLE
Add check_existing_db_2 test and fix migration

### LINKED ISSUE #429: QA: Add more databases to check_existing_db
Generated at different history point.
Try to cover as much DTOs as possible.

Add dbs/strongholds from older versions with content that needs to be migrated and create a db with them/restore the backup to see if the migration works or if it fails

### PR DESCRIPTION
**Pull request by Thoralf-M**
# Description of change

Add check_existing_db_2 test and fix migration

## Links to any relevant issues

Closes #429 

## Type of change

- Bug fix (a non-breaking change which fixes an issue)

## How the change has been tested

Running the added test

## Change checklist

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by qrayven — DISMISSED** [review]

File: sdk/src/wallet/migration/migrate_0.rs [hunk 1]
```diff
@@ -74,8 +74,10 @@ fn migrate_account(account: &mut serde_json::Value) -> Result<()> {
         }
     }
 
-    for (_key, foundry) in account["nativeTokenFoundries"].as_object_mut().unwrap() {
-        migrate_native_token(foundry);
+    if let Some(native_token_foundries) = account.get_mut("nativeTokenFoundries") {
```
Comment (thibault-martinez) [inline sdk/src/wallet/migration/migrate_0.rs:96]: Oh it was added later, right?

Comment (Thoralf-M) [reply sdk/src/wallet/migration/migrate_0.rs:96]: Yes

Comment (qrayven) [reply sdk/src/wallet/migration/migrate_0.rs:96]: why we don't have the same for `incomingTransactions` and `transactions`?

Comment (thibault-martinez) [reply sdk/src/wallet/migration/migrate_0.rs:96]: You mean the `let Some`? Because they have always been there so no need to check if they exist or not, since they have to exist.

Comment (qrayven) [reply sdk/src/wallet/migration/migrate_0.rs:96]: aa ok, got it

**Review by thibault-martinez — DISMISSED** [review]

**Review by DaughterOfMars — APPROVED** [review]

**Review by thibault-martinez — APPROVED** [review]
