### PR TITLE
Move coin_type check to the WalletBuilder

### LINKED ISSUE #503: [Bug]: If backup restored with deviating coinType, account creation throws errors
### Issue description

When a backup is restored with deviating coinType, account creation throws the following error:

```
Error:  {
  type: 'invalidCoinType',
  error: 'invalid coin type for new account: 1, existing coin type is: 4218'
}
```

### Version

develop

### Expected behaviour

The account manager should create accounts with the coinType specified in the options if the `ignoreIfCoinTypeMismatch` is passed.

### Actual behaviour

Error is thrown

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

Stronghold file to reproduce error with:

[firefly-cointype-4218.stronghold.txt](https://github.com/iotaledger/iota-sdk/files/11598876/firefly-cointype-4218.stronghold.txt)

Script to reproduce error with:

```javascript
/**
 * This script throws the error
 */
const path = require('path')
require('dotenv').config({ path: path.resolve(__dirname, '.env') });
const { AccountManager } = require('@iota/wallet');
async function run() {
    try {
        const accountManagerOptions = {
            storagePath: './restore-database',
            clientOptions: {
                nodes: [{url: 'https://api.testnet.shimmer.network', disabled: false}],
                localPow: true,
            },
            coinType: 1,
            secretManager: {
                stronghold: { snapshotPath: './restore-database/wallet.stronghold'},
            },
        };

        const manager = new AccountManager(accountManagerOptions);


        // Add the path to the file from example 5-backup.js
        // for example: ./backup/2021-02-12T01-23-11-iota-wallet-backup-wallet.stronghold
        const path = ''//"input your backup file"
        await manager.restoreBackup(path, 'dp&79S!vZAsyaC4Ia3VL', true, 'rms');
        const account = await manager.createAccount({alias: 'Alice', bech32Hrp: 'smr'});
        console.log('Account:', account.getMetadata().alias);
        console.log('Addresses:', await account.addresses());
    } catch (error) {
        console.log('Error: ', error);
    }
    process.exit(0);
}

run();
```

### Errors

```
Error:  {
  type: 'invalidCoinType',
  error: 'invalid coin type for new account: 1, existing coin type is: 4218'
}
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### PR DESCRIPTION
**Pull request by Thoralf-M**
# Description of change

Move coin_type check to the WalletBuilder, if it's checked there, because of that the check for the AccountBuilder isn't required anymore, since we don't even get there with a different coin_type

## Links to any relevant issues

Fixes #503 

## Type of change

- Bug fix (a non-breaking change which fixes an issue)

## How the change has been tested

Changed test

## Change checklist

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

File: sdk/src/wallet/wallet/builder.rs [hunk 1]
```diff
@@ -178,16 +178,27 @@ impl WalletBuilder {
             self.coin_type.replace(coin_type);
         }
 
+        #[cfg(feature = "storage")]
+        let mut accounts = storage_manager.get_accounts().await?;
+        // Check against potential account coin type before saving the wallet data
+        #[cfg(feature = "storage")]
+        if let Some(account) = accounts.first() {
+            // Safe to unwrap, because we made sure that it's Some
```
Comment (thibault-martinez) [inline sdk/src/wallet/wallet/builder.rs]: Is this unwrap comment about the expect?

Comment (Thoralf-M) [reply sdk/src/wallet/wallet/builder.rs]: Yes, should I write expect?

Comment (thibault-martinez) [reply sdk/src/wallet/wallet/builder.rs]: Nah that's fine, was confused about something but got it

File: sdk/src/wallet/wallet/builder.rs [hunk 2]
```diff
@@ -178,16 +178,27 @@ impl WalletBuilder {
...
+            if *account.coin_type() != self.coin_type.expect("missing coin type") {
+                return Err(crate::wallet::Error::InvalidCoinType {
+                    new_coin_type: self.coin_type.expect("missing coin type"),
```
Comment (thibault-martinez) [inline sdk/src/wallet/wallet/builder.rs]: I would maybe expect it once and have a variable but nitpicking

**Review by thibault-martinez — DISMISSED** [review]

File: sdk/src/wallet/wallet/builder.rs [hunk 3]
```diff
@@ -166,27 +166,25 @@ impl WalletBuilder {
...
 
-        if self.coin_type.is_none() {
-            let coin_type =
-                read_manager_builder
-                    .and_then(|data| data.coin_type)
-                    .ok_or(crate::wallet::Error::MissingParameter(
-                        "coin_type (IOTA: 4218, Shimmer: 4219)",
-                    ))?;
+        let coin_type =
+            self.coin_type.map(Ok::<u32, crate::wallet::Error>).unwrap_or_else(|| {
```
Comment (Thoralf-M) [inline sdk/src/wallet/wallet/builder.rs]: Is there a way to do the same without `.map(Ok::<u32, crate::wallet::Error>)` or matching and just passing the Some() value?

Comment (DaughterOfMars) [reply sdk/src/wallet/wallet/builder.rs]: `.ok_or_else` I believe is the right fn.

Comment (Thoralf-M) [reply sdk/src/wallet/wallet/builder.rs]: That doesn't work because the error differs ```^ the trait `std::convert::From<std::result::Result<u32, _>>` is not implemented for `wallet::error::Error```

Could do this, but doesn't really look better
```Rust
        let coin_type = self
            .coin_type
            .or_else(|| {
                let coin_type = read_manager_builder.and_then(|data| data.coin_type);
                if let Some(coin_type) = coin_type {
                    // Update self so it gets stored
                    self.coin_type.replace(coin_type);
                }
                coin_type
            })
            .ok_or(crate::wallet::Error::MissingParameter(
                "coin_type (IOTA: 4218, Shimmer: 4219)",
            ))?;
```

Comment (DaughterOfMars) [reply sdk/src/wallet/wallet/builder.rs]: I prefer that tbh. More rusty

File: sdk/src/wallet/wallet/builder.rs [hunk 4]
```diff
@@ -166,16 +166,31 @@ impl WalletBuilder {
...
         }
 
-        if self.coin_type.is_none() {
-            let coin_type =
-                read_manager_builder
-                    .and_then(|data| data.coin_type)
-                    .ok_or(crate::wallet::Error::MissingParameter(
-                        "coin_type (IOTA: 4218, Shimmer: 4219)",
-                    ))?;
+        let coin_type = self
```
Comment (DaughterOfMars) [inline sdk/src/wallet/wallet/builder.rs]: I actually think there's a little cleaner way, after thinking on it.

```rust
if self.coin_type.is_none() {
  self.coin_type = read_manager_builder.and_then(|data| data.coin_type);
}
let coin_type = self.coin_type.ok_or(crate::wallet::Error::MissingParameter(
  "coin_type (IOTA: 4218, Shimmer: 4219)",
))?;
```

Comment (Thoralf-M) [reply sdk/src/wallet/wallet/builder.rs]: Yes looks better, thanks

**Review by thibault-martinez — APPROVED** [review]

**Review by DaughterOfMars — APPROVED** [review]
