### PR TITLE
FIx slow tests using work factor

### LINKED ISSUE #575: Use try_set_encrypt_work_factor where needed

### PR DESCRIPTION
**Pull request by DaughterOfMars**
# Description of change

Use the new work factor static to fix slow tests.

## Links to any relevant issues

- Closes #575 

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Enhancement (a non-breaking change which adds functionality)

### CODE REVIEW

**Review by Thoralf-M — APPROVED** [review]

**Review by thibault-martinez — APPROVED** [review]

File: sdk/tests/wallet/wallet_storage.rs [hunk 1]
```diff
@@ -14,6 +14,8 @@ use crate::wallet::common::{setup, tear_down};
 #[cfg(all(feature = "stronghold", feature = "rocksdb"))]
 #[tokio::test]
 async fn check_existing_db() -> Result<()> {
+    iota_stronghold::engine::snapshot::try_set_encrypt_work_factor(0).unwrap();
```
Comment (Thoralf-M) [inline sdk/tests/wallet/wallet_storage.rs:17]: Actually this shouldn't work if I understand it correct, but we'll see in the CI

Comment (Thoralf-M) [reply sdk/tests/wallet/wallet_storage.rs:17]: Nvm, the old stronghold had no age encryption yet
