### PR TITLE
fix(cli): fix wallet initialization

### LINKED ISSUE #361: [Bug]: Disallow account creation before storing a valid mnemonic on first run
### Issue description

If on first run one aborts during the prompt where the user is supposed to enter a mnemonic and then restart the wallet one can get passed this step and immediately create new account.

### Version

1.0.0-rc.2

### Expected behaviour

The user should - again - be requested to enter a mnemonic before proceeding to the initial account creation step.

### Actual behaviour

The user is allowed to create an initial account, but then runs into:
```sh
wallet error: `no mnemonic has been stored into the Stronghold vault`
```

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

_No response_

### Errors

```sh
wallet error: `no mnemonic has been stored into the Stronghold vault`
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### PR DESCRIPTION
**Pull request by Alex6323**
# Description of change

This fixes a bug with initialization of a new wallet. It ensures that a stronghold snapshot file is only created when a mnemonic has been successfully stored. Prior to that PR you could abort the dialoguer interaction with CTRL-C during mnemonic generation, and this would end up with a Stronghold file that has no mnemonic stored. An alternative would be to check whether the stronghold file contains a mnemnoic on start and re-request the user to provide a mnemonic, but the solution provided with this PR fixes the issue with minimal code changes.

## Links to any relevant issues

Fixes #361 

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Bug fix (a non-breaking change which fixes an issue)

## How the change has been tested

Running the cli-wallet binary.

### CODE REVIEW

File: cli/src/command/wallet.rs [hunk 1]
```diff
@@ -128,32 +128,41 @@ pub async fn init_command(
...
 
-    if let SecretManager::Stronghold(secret_manager) = &mut *wallet.get_secret_manager().write().await {
-        secret_manager.store_mnemonic(mnemonic).await?;
-    } else {
-        panic!("cli-wallet only supports Stronghold-backed secret managers at the moment.");
-    }
+    let secret_manager = StrongholdSecretManager::builder()
+        .password(&password)
+        .build(snapshot_path)?;
+    // TODO: allow providing the mnemonic in the builder?
```
Comment (thibault-martinez) [inline cli/src/command/wallet.rs]: We have an issue to remove TODOs so let's not add some more. Open an issue if you want to discuss that.

File: cli/src/command/wallet.rs [hunk 2]
```diff
@@ -128,32 +128,41 @@ pub async fn init_command(
...
+            storage_path.display()
+        )));
+    }
+    if snapshot_path.exists() {
+        return Err(Error::Miscellaneous(format!(
+            "cannot initialize: {} already exists",
+            snapshot_path.display()
+        )));
+    }
+    // Set up password.
```
Comment (thibault-martinez) [inline cli/src/command/wallet.rs]: Doesn't look like a very useful comment tbh

Comment (Alex6323) [reply cli/src/command/wallet.rs]: removed

File: cli/src/command/wallet.rs (hunk 1 above)
Comment (Alex6323) [reply cli/src/command/wallet.rs]: Done

File: cli/src/command/wallet.rs [hunk 3]
```diff
@@ -128,32 +128,37 @@ pub async fn init_command(
...
+            "cannot initialize: {} already exists",
+            storage_path.display()
+        )));
+    }
+    if snapshot_path.exists() {
+        return Err(Error::Miscellaneous(format!(
+            "cannot initialize: {} already exists",
+            snapshot_path.display()
+        )));
+    }
```
Comment (thibault-martinez) [inline cli/src/command/wallet.rs:142]: I'm a bit confused how this actually fixes #361, what about `The user should - again - be requested to enter a mnemonic before proceeding to the initial account creation step.` ?

Comment (Alex6323) [reply cli/src/command/wallet.rs:142]: this can no longer happen. If you fully run through `init` the stronghold will contain a mnemonic. What I describe in the issue is an alternative way to go about it. I explain in the PR description why I decided to do it differently (basically not allowing a stronghold file with a faulty state)

Comment (Alex6323) [reply cli/src/command/wallet.rs:142]: I verified that this PR fixes the issue. To reproduce it:
1. delete your wallet-db and stronghold snapshot
2. run the cli wallet witthout any args or with `--init`
3. you will be prompted to set up a password and a mnemonic
4. during the dialoguer "interrogation" hit CTRL-C
5. no wallet-db/snapshot file should be created
6. run the cli-wallet again (you should be requested to do all the steps again)

Comment (thibault-martinez) [reply cli/src/command/wallet.rs:142]: Ok, I trust you

Comment (Alex6323) [reply cli/src/command/wallet.rs:142]: The "thing" that actually fixes this issue is moving the `mnemonic` creation/importing step before the secret manager build!

**Review by thibault-martinez — APPROVED** [review]

**Review by qrayven — APPROVED** [review]

**Review by Thoralf-M — APPROVED** [review]
