### PR TITLE
Fix: send evm example

### LINKED ISSUE #592: Fix signEvm
## Description

PR to reproduce issue: https://github.com/iotaledger/iota-sdk/pull/591/files#diff-01878e48c3c3fa6cc4743c662d173b4530062f42652e0275d4411e00c55eabbb

At the moment, we are unable to use the sign EVM function for the Shimmer EVM. The main reason is twofold:
- We're lacking [EIP-155](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-155.md) compatibility.
- Tthe signature resolved from the v, r & s values resolves to different addresses if we try to get them using ethereum libraries.

## Motivation

It's important that the sdk provides ways to easily create transactions compatible with Shimmer EVM.

## Requirements

Write a list of what you want this feature to do.

1. Create signatures that are EIP-155 compatible
2. Sign Transactions
3. When we call the `getSenderAddress()` on a `Transaction` object, it should return the same address that `generateAddress` returns.

## Additional remarks

We added some remarks in the example PR that reproduces the issue described above:

- There is inconsistency between `generateEvmAddresses` & `signEvm` to pass in the correct address to sign with.
- Hardening keys shouldn't be done inside Typescript. Additionally, it should be hardened by default.
- The how to shows that `signEvm` is on secret manager but it is on the account?

## Are you planning to do it yourself in a pull request?

No.

### PR DESCRIPTION
**Pull request by Tuditi**
# Description of change

Adds an example for signing and sending EVM transactions using Stronghold.

## Links to any relevant issues

closes: https://github.com/iotaledger/iota-sdk/issues/592

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

I ran the examples.

Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

File: bindings/nodejs-old/examples/37-generate-evm-address.js [hunk 1]
```diff
@@ -0,0 +1,26 @@
+/**
+ * In this example we check if an output has only an address unlock condition and that the address is from the account.
```
Comment (Thoralf-M) [inline bindings/nodejs-old/examples/37-generate-evm-address.js]:
```suggestion
 * In this example we generate an EVM address.
```

File: bindings/nodejs-old/examples/38-sign-evm-transaction.js [hunk 2]
```diff
@@ -0,0 +1,130 @@
+/* eslint-disable @typescript-eslint/no-var-requires */
+/**
+ * In this example we check if an output has only an address unlock condition and that the address is from the account.
```
Comment (Thoralf-M) [inline bindings/nodejs-old/examples/38-sign-evm-transaction.js]:
```suggestion
 * In this example we sign and send an EVM transaction.
```

File: bindings/nodejs/examples/evm/send-evm-transaction.ts [hunk 3]
```diff
@@ -0,0 +1,171 @@
+/* eslint-disable @typescript-eslint/no-var-requires */
+
+// Run with command:
+// yarn run-example ./evm/send-evm-transaction.ts
+
+// In this example we will send an ERC-20 token transfer using Stronghold.
```
Comment (Thoralf-M) [inline bindings/nodejs/examples/evm/send-evm-transaction.ts]:
```suggestion
// In this example we will send an ERC-20 token transfer using a SecretManager.
```

File: bindings/nodejs/examples/evm/send-evm-transaction.ts [hunk 4]
```diff
@@ -0,0 +1,171 @@
...
+            hexSignedTransaction,
+        );
+        console.log('sent Transaction', sentTransaction);
+
+        // Testing: check sender address matches
+        strictEqual(
+            senderAddress,
+            signedTransaction.getSenderAddress().toString(),
+            'Mismatch in addresses',
+        );
```
Comment (Thoralf-M) [inline bindings/nodejs/examples/evm/send-evm-transaction.ts:95]: Shouldn't this be done before sending the transaction?

Comment (Tuditi) [reply bindings/nodejs/examples/evm/send-evm-transaction.ts:95]: Yeah, that makes sense. I updated the code.

**Review by Thoralf-M — DISMISSED** [review]

**Review by thibault-martinez — CHANGES_REQUESTED** [review]
CI is failing

File: bindings/nodejs-old/examples/38-sign-evm-transaction.js [hunk 5]
```diff
@@ -0,0 +1,131 @@
...
+const { Transaction } = require('@ethereumjs/tx')
+const { RLP } = require('@ethereumjs/rlp')
+const { fromRpcSig } = require('@ethereumjs/util')
+
+const { ERC_20_ABI } = require('./erc-20.abi')
+
+const RPC_ENDPOINT = 'https://json-rpc.evm.testnet.shimmer.network'
+const RECIPIENT_ACCOUNT_ADDRESS = '0x2fF33407c26E36c32cA50A4e63ce661b2eeED3dd'
+const CHAIN_ID = 1072
+const COIN_TYPE = 60
```
Comment (DaughterOfMars) [inline bindings/nodejs-old/examples/38-sign-evm-transaction.js]:
```
const ETHER_COIN_TYPE = 60
```

File: bindings/nodejs-old/examples/38-sign-evm-transaction.js [hunk 6]
```diff
@@ -0,0 +1,131 @@
...
+        const transaction = Transaction.fromTxData(txData, TX_OPTIONS)
+
+        // 2. Create messageToSign by external signer
+        const message = transaction.getMessageToSign(false)
+        const serializedMessage = Buffer.from(RLP.encode(message))
+        const messageToSign = '0x' + serializedMessage.toString('hex')
+        
+        // 3. Sign message with external signer
+        const bip44Path = {
+            coinType: 60,
```
Comment (DaughterOfMars) [inline bindings/nodejs-old/examples/38-sign-evm-transaction.js]: Didn't use the const

File: bindings/nodejs-old/examples/38-sign-evm-transaction.js [hunk 7]
```diff
@@ -0,0 +1,131 @@
...
+
+async function createTxData(provider, address) {
+    const erc20Contract = new provider.eth.Contract(ERC_20_ABI, TOKEN_CONTRACT_ADDRESS)
+    
+    const data = erc20Contract.methods.transfer(RECIPIENT_ACCOUNT_ADDRESS, provider.utils.toHex(AMOUNT)).encodeABI()
+    
+    const nonce = provider.utils.toHex(await provider.eth.getTransactionCount(address))
+
+    const _gasPrice = await provider.eth.getGasPrice()
+    const gasPrice = provider.utils.toHex(_gasPrice)
```
Comment (DaughterOfMars) [inline bindings/nodejs-old/examples/38-sign-evm-transaction.js]:
```suggestion
    const gasPrice = provider.utils.toHex(await provider.eth.getGasPrice())
```

File: bindings/nodejs-old/examples/abis/erc-20.abi.ts
Comment (DaughterOfMars) [inline bindings/nodejs-old/examples/abis/erc-20.abi.ts:1]: Just out of curiosity, where did these types come from? Is there not a lib that can be imported instead?

Comment (Tuditi) [reply bindings/nodejs-old/examples/abis/erc-20.abi.ts:1]: I got them from here: https://github.com/iotaledger/wasp/blob/28fcf96b3af5c33508ce00841dbc44b6de8a57c3/packages/evm/evmtest/ERC20Basic.abi.

I don't want to include another dependency just for this code. Trusted packages like Open Zeppelin only have the Solidity contracts, which need to be compiled to get the ABI. Additionally, it would bloat the example repository, since it includes a lot more than only the ERC-20 ABI. 

I don't expect other smart contract interaction in the wallet library, so I would say this is okay for now.

File: bindings/nodejs/examples/evm/send-evm-transaction.ts [hunk 8]
```diff
@@ -0,0 +1,171 @@
...
+        const transaction = Transaction.fromTxData(txData, TX_OPTIONS);
+
+        // 2. Create messageToSign by external signer
+        const message = transaction.getMessageToSign(false);
+        const serializedMessage = Buffer.from(RLP.encode(message));
+        const messageToSign = '0x' + serializedMessage.toString('hex');
+
+        // 3. Sign message with external signer
+        const bip44Path = {
+            coinType: 60,
```
Comment (thibault-martinez) [inline bindings/nodejs/examples/evm/send-evm-transaction.ts]: constant

**Review by thibault-martinez — APPROVED** [review]

**Review by Thoralf-M — APPROVED** [review]
